### ISSUE TITLE
How to config read data from slave servers?

### ISSUE THREAD

**Issue by canh-nguyen** [mrniko/redisson#107]

**Comment by mrniko** [comment]
read-only operations are always use slave servers

**Comment by canh-nguyen** [comment]
if i have 3 slave server(A, B,C), then client will read from server A, B or C?

**Comment by mrniko** [comment]
which server configuration do you use - master-slave, sentinel or cluster?

**Comment by mrniko** [comment]
> if i have 3 slave server(A, B,C), then client will read from server A, B or C?

Yes using random or roundrobin balancer which could be configured

**Comment by canh-nguyen** [comment]
Hi, could you please let me know how to define roundrobin balancer via config?

**Comment by mrniko** [comment]
Here is an example

````java
config.useMasterSlaveConnection()
    .setMasterAddress("127.0.0.1:6379")
    .setLoadBalancer(new RandomLoadBalancer())

**Comment by ldwnt** [comment]
useMasterSlaveConnection allows only single master. Can I use it together with useClusterServers and how? (I have a cluster of n masters & n * m slaves) @mrniko

**Comment by mrniko** [comment]
@ldwnt 

In Redis cluster you should use useClusterServers mode

**Comment by ldwnt** [comment]
> @ldwnt
> 
> In Redis cluster you should use useClusterServers mode

So in useClusterServers mode, I don't need to tell which nodes are masters/slaves, and when I set readFrom to slave and loadBalancer to random/round robin, redisson dispatches read-only requests to slave nodes only and the load is balanced as instructed?

**Comment by xingan** [comment]
@ldwnt 

How is your cluster managed? https://github.com/redisson/redisson/wiki/2.-Configuration#24-cluster-mode
