### ISSUE TITLE
Can't get Redisson 1.1.7 to work in an OSGi container

### ISSUE THREAD

**Issue by marto** [mrniko/redisson#109]
Apologies if this is not the right forum to raise this bug.

I have  been trying to deploy redisson to an OSGi container however I can't get v1.1.7 to work even though it's one of Radissons features. Here are some details of what I have so far found.

Redisson has a "provided" scoped maven dependency on kryo (com.esotericsoftware.kryo:kryo:2.24.0), but the OSGi manifest imports ```com.esotericsoftware.kryo,version=[2.24,3)```

This means that the radisson OSGi bundle won't start up as it depends on kryo 2.24.*  Unfortunately due to an OSGi issue in Kryo (https://github.com/EsotericSoftware/kryo/issues/189), there is no release of kryo after v2.24 that has the bug fixed (only v 3.0.0 which is too new according to the OSGi requirements of redisson - ```import com.esotericsoftware.kryo,version=[2.24,3)```) . This means that Redisson 1.1.7 won't and can't work in an OSGi environment unless it is manually hacked.

Kryo v 3.0.0 has been released that contains the OSGi fixes thus Redisson should probably be modified to utilise kryo v 3.0.0 to fix the OSGi issues. Also the dependency should be changed to be a compile time dependency (rather than provided) if radisson has a hard runtime depdency on kryo. 

If Kryo is not required at runtime (i.e. it's an optional dependency that can somehow be configured and sorry I haven't used radisson before so this is a newbie assumption) then the maven-bundle-plugin configuration could be changed to dynamically import kryo (see below) as and when it's needed. The upgrade to kryo v3.0.0 should still be considered.
```
           <configuration>
               <instructions>
                     <DynamicImport-Package>
                         com.esotericsoftware.kryo.*
                     </DynamicImport-Package>
               </instructions>
           </configuration>
```

Also note that kryo maven groupId has changed to ```com.esotericsoftware```.

I hope you can help... thanks

**Comment by mrniko** [comment]
Fixed. Please check
