### ISSUE TITLE
could redisson provide integration with netty5 snapshot ? 

### ISSUE THREAD

**Issue by bwzhang2011** [mrniko/redisson#112]
netty5 seems widely used and does many enhancement for last year. does any test or integration with redisson take into consideration or provide some small modification to make it compatible or provide some new branch for testing ? if any done it would be much appreciated.

**Comment by mrniko** [comment]
> netty5 seems widely used 

Where? There is no any stable build of netty5.

**Comment by bwzhang2011** [comment]
@mrniko, I just mean that though netty5 does not provide stable version for releasing but it did exactly widely used in many project though with the title snapshot. switching from netty4 to netty5 seems not very difficult maybe it could start a new brach for testing. so that's some suggestion compared with your stable idea with netty framework integration.

**Comment by mrniko** [comment]
I'll start integration with netty 5 when stable build with frozen api of this lib will be available

**Comment by bbrui** [comment]
replace channelUnregistered  method sign  of  handlerRemoved in CommandHandler.java,it can suport netty5.
and jar dependency is 
 <dependency>
	  	<groupId>io.netty</groupId>
	  	<artifactId>netty-all</artifactId>
	  	<version>5.0.0.Alpha1</version>
</dependency>
<dependency>
	  	 <groupId>com.fasterxml.jackson.core</groupId>
		  <artifactId>jackson-annotations</artifactId>
		  <version>2.1.4</version>
</dependency>
<dependency>
	  	<groupId>com.fasterxml.jackson.core</groupId>
	  	<artifactId>jackson-core</artifactId>
	  	<version>2.3.3</version>
 </dependency>
 <dependency>
	  	<groupId>com.fasterxml.jackson.core</groupId>
	  	<artifactId>jackson-databind</artifactId>
	  	<version>2.3.3</version>
</dependency>

**Comment by bwzhang2011** [comment]
@bbrui  thanks for review. please take a look at https://github.com/netty/netty/issues/2933 and give the last advice for redisson integration with netty5.

**Comment by mrniko** [comment]
It seems like netty5 has gone from official netty page as well as from github repo too
