### ISSUE TITLE
Does Redisson support BlockingQueue ? 

### ISSUE THREAD

**Issue by msimonin** [mrniko/redisson#117]
I just read the documentation, but in the documentation there is no mention of BlockingQueue. 
Does redisson support this ? I'm wondering because redis supports natively blocking operation on queues. Am I missing something ?

**Comment by mrniko** [comment]
Currently, reddison doesn't support this feature.

**Comment by pdeschen** [comment]
Hi @mrniko Accepting PR for this? I have an implementation of a `RedissonBlockingQueue` working.

**Comment by mrniko** [comment]
@pdeschen yea, i'll review it

**Comment by msimonin** [comment]
+1

**Comment by mrniko** [comment]
Done
