### ISSUE TITLE
Promise timeout (temporary) resource leak

### ISSUE THREAD

**Issue by danielchatfield** [mrniko/redisson#123]
When a promise has been fulfilled the timeout task should be cancelled. Currently this is not the case and means that the (potentially very large) amounts of data included in the promise will remain on the heap until the timeout fires.

An example:

 - A request is made for a large (millions of entries) dataset.
 - The promise is returned and then fulfilled
 - The data is consumed and the promise goes out of scope
 - repeat

What should happen is that the garbage collector should clean up the promise since it is now out of scope but this can't happen since the timeout task still has a reference to it so it remains in memory for 60 secs (deadline) and very quickly you get OOM.

cc @group-papa @priyeshpatel

**Comment by mrniko** [comment]
> as Redisson ignores the timeout set in a SingleServerConfig provided upon construction

This fixed here https://github.com/mrniko/redisson/issues/119

**Comment by mrniko** [comment]
fixed

**Comment by mrniko** [comment]
@danielchatfield i just added a timeout cancellation it should helps
