### ISSUE TITLE
Redisson and multiple like inserts

### ISSUE THREAD

**Issue by PashaTurok** [mrniko/redisson#130]
Lets suppose I have a list of some students - the current list has students with ids: 3,5,8. As I understand I don't need to use redis list here as I don't need to keep order. The order I don't need as it's clear it's just SOME of students. However I want to cache them.
I think I need to use here redis type string and do something like db:stundents:{id}. My question - how can I do multiple insert of these three stundents? To insert one I use Bucket.set().

**Comment by mrniko** [comment]
With Redisson 2.0 you could use batches. Example:

```java
RBatch batch = redisson.createBatch();
// all those commands will be executed as one
batch.getBucket('id1').setAsync('student1');
batch.getBucket('id1').setAsync('student1');
batch.getBucket('id1').setAsync('student1');
// execute all async operations in batch
batch.execute();
```
