### ISSUE TITLE
Redisson sorted set creates list in redis server

### ISSUE THREAD

**Issue by PashaTurok** [mrniko/redisson#131]
I do the following:
Redisson redisson = RedissonManager.getRedisson();
        RSortedSet<...> rSet;
        Set<...> set = new HashSet<>(list);//list to set
        rSet = redisson.getSortedSet("test");
        rSet.addAll(set);
but when I do
./redis-cli
type test 
it return "list". Why does redisson creates list and how can I do sorted set with scores using redisson?

**Comment by mrniko** [comment]
with current sort algorithm it uses list under the hood, it's hard to use sorting by score with java comparator.

**Comment by PashaTurok** [comment]
So redisson doesnt support redis sorted sets?

**Comment by mrniko** [comment]
it implements sorted set but not mapped to redis sorted set type
