### ISSUE TITLE
Storing RBucket<Map<Integer,String>> returns RBucket<Map<String,String>>

### ISSUE THREAD

**Issue by PashaTurok** [mrniko/redisson#132]
I store HashMap<Integer,String> but after taking it from redisson I get HashMap<String,String> or HashMap<Object,Object>. Checking it via cli I get 
"{\"@class\":\"java.util.HashMap\",\"3\":\"\xd0\x91\xd1\x83\xd1\x85\xd0\xb3\xd0\xb0\xd0\xbb\xd1\x82\xd0\xb5\xd1\x80\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd1\x83\xd1\x87\xd0\xb5\xd1\x82: \xd0\x9e\xd1\x82\xd1\x87\xd0\xb5\xd1\x82\xd0\xbd\xd0\xbe\xd1\x81\xd1\x82\xd1\x8c\",\"4\":\"\xd0\x91\xd1\x83\xd1\x85\xd0\xb3\xd0\xb0\xd0\xbb\xd1\x82\xd0\xb5\xd1\x80\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd1\x83\xd1\x87\xd0\xb5\xd1\x82: \xd0\xa1\xd1\x87\xd0\xb5\xd1\x82\xd0\xb0\"}"
How to fix it?

**Comment by mrniko** [comment]
Strange case, you need to patch `org.redisson.codec.JsonJacksonCodec` for this because it's hard to extract type from generics. And i have no idea for now how to do it.

It's better to use RMap in your case.

**Comment by PashaTurok** [comment]
Maybe this will help: http://stackoverflow.com/a/3687852/4568213

**Comment by mrniko** [comment]
related to #134
