### ISSUE TITLE
more than one decoder/encoder for redisson and auto Type detection.

### ISSUE THREAD

**Issue by doggie1989** [mrniko/redisson#134]
auto detection support will be nice, json,xml,protocolbuffer,kyro

**Comment by doggie1989** [comment]
@mrniko do you have any idea on this feature?

**Comment by Gladmir** [comment]
It would be nice to support some kind of runtime detection via optional serialisation sub-frameworks. Jersey Jax-RS implementation provides similar functionality.

**Comment by mrniko** [comment]
@Gladmir could you provide Jersey Jax-RS api example of this?

**Comment by Gladmir** [comment]
Jersey has a mechanism, well simply put, SPI via ServiceLoader. Any type of encoder/decoder can be developed and plugged in to core framework via generic Mime-Types.

So, at startup or lazily later on, redisson can lookup to its class path for encoding/decoding service providers, load/initialize and be ready to use them.

A simple collection access to redisson would be very easy later on with a specific provider's mime type paired with it. If no providers are available for requested mime type, proper exception handling should be done by the user.

ex: 
RMap<SomeJsonObject> jsonObjects = redisson.getMap ("someJsonMap", "application/json");
RMap<SomeBinaryObject> binaryObjects = redisson.getMap ("someBinaryMap", "binary/kyro");

I do admit, providing some obscure meta/media type is ugly but it provides the decoupling of redisson and its encoder/decoder providers.

Cheers

**Comment by mrniko** [comment]
@Gladmir "application/json", "binary/kyro" is a media type used in http server. I think it's improperly to use it in context of Redis client. Codec instance usage as parameter is obvious here.

**Comment by mrniko** [comment]
done
