### ISSUE TITLE
How to check if Redis Server is available ?

### ISSUE THREAD

**Issue by teknologist** [mrniko/redisson#138]
Hi,

This may be a stupid question but we fail to find a quick way to check if the Redis server is up & running before trying anything on it.

is there any quick and simple way to check for the servers connection ?

Many thanks in advance,

Cheers!

**Comment by mrniko** [comment]
Hi, do you use Redisson in single server mode? you may use redis PING command for this aim

**Comment by ahmedaswai** [comment]
So how could we check if the server is running ?

**Comment by mrniko** [comment]
use `redisson.getNodesGroup().pingAll` or use `redisson.getNodesGroup().getNodes().ping`
