### ISSUE TITLE
SortedSet needed

### ISSUE THREAD

**Issue by clive82** [mrniko/redisson#143]
It's inconvenience  to use sorted set like this:
			connectionManagerField = Redisson.class.getDeclaredField("connectionManager");
			connectionManagerField.setAccessible(true);
			connectionManager = (ConnectionManager) connectionManagerField.get(redisson);

		Double result = connectionManager.get(connectionManager.writeAsync(new ResultOperation<Double, E>() {
			@Override
			public Future<Double> execute(RedisAsyncConnection<Object, E> async) {
				return async.zincrby(stringKey, amount, member);
			}
		}));

**Comment by mrniko** [comment]
ScoreSortedSet will be added
