### ISSUE TITLE
Connection errors handling breaks redis watch/multi/exec semantics

### ISSUE THREAD

**Issue by AndrewKolpakov** [mrniko/redisson#145]
Let's look into org.redisson.RedissonMap#replace(K, V, V)
Good scenario:
watch -> ok
hexists -> ok
multi -> ok
hset -> queued
exec -> ok

Bad scenario:
watch -> ok
hexists -> ok
multi -> ok
hset -> operation timeout or other error handled by MasterSlaveConnectionManager#readAsync , retry on new connection, result ok
exec -> "exec without multi" failure

Impact: in bad scenario map content can be replaced with invalid value for key K

**Comment by AndrewKolpakov** [comment]
see #176

**Comment by mrniko** [comment]
i am going through your commits in https://github.com/setronica-dev/redisson/tree/rethrow_exception_on_op_failure
