### ISSUE TITLE
Long as Key in Hashs

### ISSUE THREAD

**Issue by ahmedaswai** [mrniko/redisson#146]
I tried to use the library then I started running  the next code , the map has K-->String(JSON)

RMap<Long, String> map = redisson.getMap("lst_pos");
map.fastPut(354330031528808L, jsonBuilder.toJson(pos));

but unfortunately  when I checked the redis I found the key stored  in the hash as String by the next format 
["java.lang.Long",354330031528808]

is there is any way to store the Key as Long to save space on my redis node

**Comment by ajbrown** [comment]
+1

**Comment by mrniko** [comment]
without type info it could lead to problem during deserialization - Integer confuses with Long

For example: you store 1L but Redisson will read it as integer because it doesn't know anything about it type.

**Comment by ahmedaswai** [comment]
Yeah , but now our java or Scala codes are the only can parse those keys , so if you have python or or ruby programmer , you should inform them that the keys are stored by Java class names

**Comment by AndrewKolpakov** [comment]
@ahmedaswai You can use custom codec - copy JsonJacksonCodec and remove `if (t.getRawClass() == Long.class)` from  TypeResolverBuilder.
But you shouldn't use longs for keys and values in map/list/queue structures.

**Comment by mrniko** [comment]
related to #134

**Comment by mrniko** [comment]
getMap(name, codec) method added
