### ISSUE TITLE
Use issues ----lock(long leaseTime, TimeUnit unit)

### ISSUE THREAD

**Issue by mekingshow** [mrniko/redisson#147]
when i run the method 

com.lambdaworks.redis.RedisException: ERR wrong number of arguments for 'set' command

How to solve this problem？

@Test
    public void testExpire() throws InterruptedException {
        RLock lock = redisson.getLock("lock");
        lock.lock(2, TimeUnit.SECONDS);

        final long startTime = System.currentTimeMillis();
        final CountDownLatch latch = new CountDownLatch(1);
        new Thread() {
            public void run() {
                RLock lock1 = redisson.getLock("lock");
                lock1.lock();
                long spendTime = System.currentTimeMillis() - startTime;
                Assert.assertTrue(spendTime < 2020);
                lock1.unlock();
                latch.countDown();
            };
        }.start();

        latch.await();

        lock.unlock();
    }

**Comment by mrniko** [comment]
please update your Redis server to 2.8 at least
