### ISSUE TITLE
[Question] What if I don't call Redission#shutdown()?

### ISSUE THREAD

**Issue by huylv** [mrniko/redisson#153]
Hi,
I'm using this library together with Storm. Since the connection should essentially be alive during streaming to be able to read/write continuously, I don't want to call `Redission#shutdown()`. I wonder what would happen to the connection? What if a node that uses the connection fails in the middle of a stream?
Thank you.
Huy

**Comment by mrniko** [comment]
You will have an open connections in ConnectionManager and live netty-threads.

**Comment by huylv** [comment]
How do I come over this?

**Comment by mrniko** [comment]
> What if a node that uses the connection fails in the middle of a stream?
if connection drops it will be reconnected by ConnectionWatchdog handler
