### ISSUE TITLE
Calling Publish On Topic in the Listener of Another Topic

### ISSUE THREAD

**Issue by ahmedaswai** [mrniko/redisson#154]
I have an issue related to publish message on topic inside the subscribe listener on another topic. I am getting this exception io.netty.util.concurrent.BlockingOperationException: DefaultPromise@6c7a158e(incomplete).

The code  
------------------------

private MessageListener<String> getMessageListener(){

        return new MessageListener<String>() {
            @Override
            public void onMessage(String msg) {
                redisCache.publishOnUserTopic(" Msg One 2 3 ", "ahmed");
                final Tuple<Position,LastPosition>posTuple=gsonBuilder.parsePosTuple(msg);

                final DbJob<Tuple>tupleDbJob=new DbJob<Tuple>(posTuple) {
                    @Override
                    public Boolean call() {
                        System.out.println("DB messages Counter----->" + Counter.COUNTER_DB.incrementAndGet());
                         boolean insertedSuccess=trackingDao.insertNewPosition(posTuple);

                        return insertedSuccess;

                    }
                };
                if(tupleDbJob.call()){
                    //redisCache.publishOnUserTopic(" Msg One 2 3 ", "ahmed");
                }

            }
        };
    }

**Comment by mrniko** [comment]
Tested with 2.0.0 version. All works correctly
