### ISSUE TITLE
[Question] Using Redission how to achieve LRU ?

### ISSUE THREAD

**Issue by dpdev3** [mrniko/redisson#158]
(1) Using Redission how to achieve LRU?

(2) How to set expiry for one particular object of the Bucket or List or Set ?

**Comment by mrniko** [comment]
> (1) Using Redission how to achieve LRU?

LRU support not yet implemented in Redisson. But you may read about Redis lru settings [here](http://redis.io/topics/lru-cache)

> (2) How to set expiry for one particular object of the Bucket or List or Set ? 

Each Redisson object has `expireAt` and `expire` methods.
