### ISSUE TITLE
suggest  StringCodec as default Codec

### ISSUE THREAD

**Issue by carlvine500** [mrniko/redisson#160]
JsonJacksonCodec performance is not so Good  , suggest  StringCodec as default Codec .

 JsonJacksonCodec VS StringCodec ：
-----------------------------------------------------
server 8core16G , one redis node , concurrent 200 ,total task 2000*1000,each task set 128byte to redis
 =====JsonJacksonCodec========
 Requests per second:	13479.335--QPS
======StringCodec=========
 Requests per second:	34479.335--QPS

**Comment by mrniko** [comment]
StringCode good for strings only. Jackson used to serialize any object
