### ISSUE TITLE
NPE in RedissonExpirable

### ISSUE THREAD

**Issue by rmalchow** [mrniko/redisson#161]
hi,

i keep seeing occasional null pointer exceptions in RedissonExpriable, line 37 (when i try to extend the lifetime of a bucket). i only see this in one environment, not on a second one and not on my local. i am assuming that i am having some connectivity issues there. could that be a cause? why is it an NPE?

**Comment by Gladmir** [comment]
@rmalchow : Could you provide the stack trace maybe?
