### ISSUE TITLE
will redisson support ASKING when migrating slot ? 

### ISSUE THREAD

**Issue by carlvine500** [mrniko/redisson#164]

**Comment by mrniko** [comment]
Where you would use this command?

**Comment by carlvine500** [comment]
after migrating key=a from one slot to another,  but the node-slots is not changed,
and we send (set a=1) to the old node, redis will tell me asking another node.
eg: after migrating a from 7001 to 7002 
127.0.0.1:7001> get a 
(error) ASK 15495 10.126.53.98:7002
127.0.0.1:7001> quit
[root@53 redis-3.0.0]# ./src/redis-cli -p 7002
127.0.0.1:7002> asking 
OK
127.0.0.1:7002> get a 
"3"

**Comment by mrniko** [comment]
fixed. please try it
