### ISSUE TITLE
RedisConnectionException when using Amazon ElastiCache

### ISSUE THREAD

**Issue by agrigoroi** [mrniko/redisson#165]
We encountered an issue when using Redisson to connect our application running on Ubuntu to Amazon ElastiCache for Redis.

When performing any operation Redisson throws a `RedisConnectionException`: `Unable to connect xxxx.cache.amazonaws.com/10.xxx.xxx.xxx:6379`. However, after installing the `redis-tools` package (using `apt-get`) the issue goes away and everything works correctly.

Does Redisson requires the `redis-cli` binary or the `redis-tools` package? Did anyone had a similar issue?

**Comment by mrniko** [comment]
ElastiCache support added in https://github.com/mrniko/redisson/pull/244
