### ISSUE TITLE
Redisson and leap second

### ISSUE THREAD

**Issue by savanpatel** [mrniko/redisson#174]
Hello,
I am using redis and redisson for my service deployed on Amazon server. Server has older kernel version that suffers from leap second bug. Will it affect redis or redisson lock in any manner? If so what is the possible solution to it?

**Comment by mrniko** [comment]
> leap second bug

What you mean? it it a bug in linux kernel?

**Comment by savanpatel** [comment]
Yes.

**Comment by mrniko** [comment]
Can't say anything about this problem. Sorry
