### ISSUE TITLE
Reddison tries to connect to a slave which is down

### ISSUE THREAD

**Issue by zsjoska** [mrniko/redisson#175]
Redisson library version: 1.2.1

Hi,

We are using SentinelServersConfig and during the tests we observed that if a slave is down, and sentinel properly reports this by putting the s_down flag, Redisson still considers it at initialization and during the operation tries to connect to it.
This affects badly the performance, since RoundRobin tries periodically send though that slave.
WARN  o.r.c.RoundRobinLoadBalancer - Can't connect to /192.168.150.163:6379, trying next connection!
As I see, the SentinelConnectionManager constructor does not check for the "s_down" flag when initializes the list of available slaves, thus the Redisson snapshot of slave status does not reflects the status of slave servers.

**Comment by mrniko** [comment]
could you write a full redis slave state string in this case?

**Comment by mrniko** [comment]
at SentinelConnectionManager:72 could you print a map object state?

**Comment by zsjoska** [comment]
Hi,

this is the value returned by get(connection.slaves(cfg.getMasterName())) at line 72

[{
	role-reported=slave,
	info-refresh=8386,
	last-ping-sent=0,
	role-reported-time=366955099,
	ip=192.168.150.161,
	flags=slave,
	slave-repl-offset=1351448313,
	master-port=6379,
	master-host=192.168.150.162,
	slave-priority=100,
	port=6379,
	pending-commands=0,
	name=192.168.150.161: 6379,
	last-ok-ping-reply=253,
	last-ping-reply=253,
	runid=144ccbb9dcf0a4e6fbda621c3e1e40d7cbab1194,
	master-link-status=ok,
	master-link-down-time=0,
	down-after-milliseconds=60000
},
{
	role-reported=slave,
	info-refresh=16311645,
	last-ping-sent=16304036,
	role-reported-time=366955099,
	ip=192.168.150.163,
	flags=s_down,
	slave,
	disconnected,
	slave-repl-offset=1328665522,
	master-port=6379,
	s-down-time=16243978,
	master-host=192.168.150.162,
	slave-priority=100,
	port=6379,
	pending-commands=0,
	name=192.168.150.163: 6379,
	last-ok-ping-reply=16304246,
	last-ping-reply=16304246,
	runid=6bca78e731a66ae4dc0b72053fb7f1318e2d2c45,
	master-link-status=ok,
	master-link-down-time=0,
	down-after-milliseconds=60000
}]

**Comment by mrniko** [comment]
fixed.

**Comment by zsjoska** [comment]
WOW, that was quick. We will try then the bleeding edge.
Thank you!
