### ISSUE TITLE
org.redisson.RedissonLock.tryLockInner  throw  java.lang.NullPointerException

### ISSUE THREAD

**Issue by lefay1982** [mrniko/redisson#178]
public class RedissonLock extends RedissonObject implements RLock {
    ...
    private Long tryLockInner() {
        final LockValue currentLock = new LockValue(id, Thread.currentThread().getId());
        currentLock.incCounter();

        return connectionManager.write(getName(), new SyncOperation<LockValue, Long>() {

            @Override
            public Long execute(RedisConnection<Object, LockValue> connection) {
                Boolean res = connection.setnx(getName(), currentLock);
                if (!res) {
                    connection.watch(getName());

in RedissonLock.java Line 291, if Boolean res is null, the 291 line if(!res)  throw java.lang.NullPointerException.

java.lang.NullPointerException
	at org.redisson.RedissonLock$2.execute(RedissonLock.java:291)
	at org.redisson.RedissonLock$2.execute(RedissonLock.java:286)
	at org.redisson.connection.MasterSlaveConnectionManager.write(MasterSlaveConnectionManager.java:274)
	at org.redisson.connection.MasterSlaveConnectionManager.write(MasterSlaveConnectionManager.java:263)
	at org.redisson.RedissonLock.tryLockInner(RedissonLock.java:286)
	at org.redisson.RedissonLock.tryLock(RedissonLock.java:349)
	at org.redisson.RedissonLock.tryLock(RedissonLock.java:397)

**Comment by mrniko** [comment]
which redis server do you use?

**Comment by lefay1982** [comment]
redis 3.0.1

# Server
redis_version:3.0.1
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:292a31d0e7b46805
redis_mode:standalone
os:Linux 3.13.0-32-generic x86_64
arch_bits:64
multiplexing_api:epoll
gcc_version:4.8.2
process_id:6517
run_id:412864481288253d6436e2951007589251cab1ed
tcp_port:7001
uptime_in_seconds:326996
uptime_in_days:3
hz:10
lru_clock:10099374

**Comment by lefay1982** [comment]
I used SentinelServersConfig 
SentinelServersConfig mssConfig = conf.useSentinelConnection();

**Comment by mrniko** [comment]
please try it with redisson 1.3.0 also
