### ISSUE TITLE
expose async operation to List Queue etc

### ISSUE THREAD

**Issue by hepin1989** [mrniko/redisson#180]
It worth to expose the async operation to these data straction eg:
```Future<V> popAsync(timeout)```,```Future<Collection> popAsync(Int maxNumber,timeout)``` etc,maybe add something like AsyncList,AsncQueue?

**Comment by hepin1989** [comment]
I found redisson is so exciting?!
so maybe next would be Reactive-Redission?

**Comment by mrniko** [comment]
done
