### ISSUE TITLE
How can i specify the redis database in Redisson?

### ISSUE THREAD

**Issue by ajianzheng** [mrniko/redisson#182]
How can i specify the redis database in Redisson?

Thanks for reading.

**Comment by mrniko** [comment]
Here is the sample configs used to connect to different redis servers configurations -  https://github.com/mrniko/redisson/wiki/Config-examples

**Comment by ajianzheng** [comment]
I mean that like the redis-cli command "select N". In jedis, when i init the pool，i can give a parameter to specify the database:
public JedisSentinelPool(String masterName, Set<String> sentinels, GenericObjectPoolConfig poolConfig, int timeout, String password, int database).

thanks!

**Comment by mrniko** [comment]
use `setDatabase` setting available for each server configuration. Example:
```
config.useSingleServer().setAddress("127.0.0.1:6379").setDatabse(1);
```

**Comment by chook** [comment]
I noticed that **ClusterServersConfig** doesn't have setDatabase - is this intentional?

**Comment by mrniko** [comment]
@chook Redis doesn't allow to set this parameter for cluster configuration

**Comment by chook** [comment]
got it, thx! and awesome response time 👍
