### ISSUE TITLE
New Redis client

### ISSUE THREAD

**Issue by mrniko** [mrniko/redisson#183]
The idea is go away from lettuce due to some api limitiations and absence of commands pipeline support. Also command handling - encoding/decoding should be implemented with lock free approach.

**Comment by Gladmir** [comment]
Which client impl. will you be using?

**Comment by mrniko** [comment]
My own. You can take a look in to "org.redisson.client" package

**Comment by mrniko** [comment]
Could anyone join to testing `2.0` branch?
