### ISSUE TITLE
add some java doc about the codec's method

### ISSUE THREAD

**Issue by hepin1989** [mrniko/redisson#191]
it would be great to  add some java doc here:
https://github.com/mrniko/redisson/blob/master/src/main/java/org/redisson/codec/RedissonCodec.java

**Comment by mrniko** [comment]
@hepin1989 - 2.0 is ready to test. Could you try it?

**Comment by hepin1989** [comment]
I will get my hands dirty after I finish my current work😩☁😞☁☁☁☁😞☁
☁💧☁☁☁☁💧☁
🌂🌂😞😞😞😞🌂🌂
🌂😞🌂🌂🌂🌂😞🌂
I feel so sad

**Comment by mrniko** [comment]
@hepin1989 oh! i wish you a much more shiny days
