### ISSUE TITLE
Compiled "java.util.regex.Pattern" gets corrupted 

### ISSUE THREAD

**Issue by aridechettali** [mrniko/redisson#192]
Look the below smaple code, the compiled Java Regex looses its flags once you keep your object in Redis.  The below code Prints 2 before put operation, But Prints 0 after put operation to Redisson Map.

import org.redisson.Redisson;
import org.redisson.core.RMap;
import java.util.regex.Pattern;

public class RedisExample
{
    public static void main(String[] args)
    {
        Redisson redisson = Redisson.create();
        RMap<String, MyObject> m = redisson.getMap("mymap");

        MyObject mo = new MyObject("pattern",Pattern.compile("testpattern", Pattern.CASE_INSENSITIVE));
        System.out.println(mo.getPattern().flags());

        m.put("test", mo);

        mo = m.get("test");
        System.out.println(mo.getPattern().flags());
    }
}

class MyObject
{
    private String name;
    private Pattern pattern;

    public MyObject()
    {
    }

    public MyObject(String name, Pattern p)
    {
        this.name = name;
        this.pattern = p;
    }

    public Pattern getPattern()
    {
        return pattern;
    }

    public void setPattern(Pattern pattern)
    {
        this.pattern = pattern;
    }
}

**Comment by mrniko** [comment]
Try to use SerializationCodec. In any case it strange to serialize a whole Pattern object. it's better to implement a once-creation logic in getPattern which creates Pattern from string state.

**Comment by sougatabh** [comment]
At any case why/how redison can change the object attribute? BTW Compiling pattern from String is time consuming operation, so we are storing the pre compiled pattern itself.

**Comment by mrniko** [comment]
have you tried an `SerializationCodec` as i wrote above?
