### ISSUE TITLE
How to set up the expired time of different object in RMap？

### ISSUE THREAD

**Issue by Dreampie** [mrniko/redisson#195]

**Comment by mrniko** [comment]
No, this is not possible. TTL lives on the key, not on the member. But i am planning to implement a RedissonDistributedMap which will contains members as objects so the member expire will be possible.

**Comment by mrniko** [comment]
1. test key pattern search for keys with string + binary data
2. add key decoder/encoder

**Comment by sslavic** [comment]
I'm interested in RedissonDistributedMap with TTL, or a RLock implementation where custom value, a lease token, can be associated with a lock, to enable releasing a lock by another thread, thread which has lease token; forceUnlock should still be possible, so without lease token; similarly lock TTL should still work.

**Comment by kag0** [comment]
:+1: Being able to expire items in the map would be quite useful.

**Comment by mrniko** [comment]
I introduced a new `RCache` object it implements map with ttl entries and based on two Redis structures: `zset` and `map`. Any feedback is welcome

**Comment by mrniko** [comment]
Done! Hope you enjoy it :)

**Comment by kag0** [comment]
Awesome, thanks!

**Comment by crafton** [comment]
Hi, do you have a repo to pull down 2.2.1 with maven? Would like to play with the RCache.

**Comment by mrniko** [comment]
RCache was renamed to RMapCache. Because I'm planning to implement RSetCache too.

**Comment by mrniko** [comment]
@crafton 2.2.1 release is scheduled for this Friday.

**Comment by crafton** [comment]
Ok great, thanks!

**Comment by mrniko** [comment]
New version in maven repo!
