### ISSUE TITLE
redisson client is connected

### ISSUE THREAD

**Issue by fadaytak** [mrniko/redisson#196]
any method to know if redisson client is connected or not? i have a "connection is closed" error and i don"t know when re-use the same client or should create new one...

com.lambdaworks.redis.RedisConnectionClosedException: Connection is closed
	at com.lambdaworks.redis.RedisAsyncConnection.dispatch(RedisAsyncConnection.java:1246)
	at com.lambdaworks.redis.RedisAsyncConnection.eval(RedisAsyncConnection.java:308)
	at org.redisson.RedissonScript$2.execute(RedissonScript.java:68)
	at org.redisson.async.ResultOperation.execute(ResultOperation.java:27)
	at org.redisson.connection.MasterSlaveConnectionManager.writeAsync(MasterSlaveConnectionManager.java:252)
	at org.redisson.connection.MasterSlaveConnectionManager.writeAsync(MasterSlaveConnectionManager.java:223)
	at org.redisson.RedissonScript.evalAsync(RedissonScript.java:65)
	at org.redisson.RedissonMap.putAsync(RedissonMap.java:248)
	at org.redisson.RedissonMap.put(RedissonMap.java:121)

**Comment by mrniko** [comment]
and redisson is not reconnecting in this case?

**Comment by fadaytak** [comment]
no not reconnecting, the problem how can i do some mechanism when i put in some map and i get a connection problem.. how can make a reconnecting system to force reconnecting and putting the same message..

cordially

**Comment by mrniko** [comment]
which redis servers configuration do you use?

**Comment by fadaytak** [comment]
Config config = new Config();
			config.useSingleServer().setAddress(PropertiesUtil.getProperties().get("REDIS_SERVER")+":"+PropertiesUtil.getProperties().get("REDIS_PORT"));
			config.useSingleServer().setRetryAttempts(3);
			config.useSingleServer().setTimeout(10000);
			config.useSingleServer().setConnectionPoolSize(500);
			config.useSingleServer().setRetryInterval(2000);
			redisson = Redisson.create(config);

**Comment by mrniko** [comment]
you can increase `retryAttempts` amount, set it to `Integer.MAX_VALUE`

**Comment by fadaytak** [comment]
any method to know the connection status?
like redisson.isconnected()?

and when i put in a map and he failed he will retry and put the same value or should i implement a retry system manually??

cordially

**Comment by mrniko** [comment]
> like redisson.isconnected()?
not yet. i'am planning to implement nodes status info method

> and when i put in a map and he failed he will retry and put the same value 

if retryAmount is not exhausted Redisson will just repeat your command again and again

**Comment by fadaytak** [comment]
okay so currently no mechanism system needed to be implemented just increase the value of setRetryAttempts to Integer.MAX_VALUE

**Comment by mrniko** [comment]
Create an Node object for each `RedisClient` with `isAlive` method. Sending a PING command to server during `isAlive` invocation and response is guarantee that server is alive.

**Comment by mrniko** [comment]
add new `Configuration.pingTimeout` setting

**Comment by mrniko** [comment]
use `redisson.getNodesGroup().pingAll` or use `redisson.getNodesGroup().getNodes().ping`

**Comment by INRIX-Cory-Bradshaw** [comment]
Will this ping fail if "RedisConnectionException:Can't aquire connection from pool! " is getting thrown during use of the client? Trying to find an easy way to test if connections are available for an application health check.

**Comment by alijaza** [comment]
This would be useful...
