### ISSUE TITLE
Infinispan redis integration

### ISSUE THREAD

**Issue by spaulg** [mrniko/redisson#202]
I'm contributing a redis integration to infinispan and am investigating the use of Redisson to use as the client.

I need an efficient way to retrieve a list of all keys and iterate over them for processing, but because Redis can store millions of records, I wanted to avoid a list/queue of data pulled from the Redis server and held in memory on the client as this could wind up exhausting resources on the client.

Will getBuckets, findKeysByPattern or findKeysByPatternAsync retrieve the keys in an efficient manor, like a database cursor stepping over each record, or is there another approach that is recommended to efficiently cater for this?

**Comment by mrniko** [comment]
There is no cursor for keys iteration. But if you find the way, please tell me

**Comment by spaulg** [comment]
The only way I've seen is that in the Lettuce client. It has a method whereby keys can be streamed; a callback is triggered for each key received. 

I haven't tested to see how effective it is. I presume it blocks the connection at a low level until the callback processes items in a fixed sized queue on the client, making more space to resume the connection.

**Comment by mrniko** [comment]
> I presume it blocks the connection at a low level until the callback processes items in a fixed sized queue on the client

But it's not atomic way. I mean there is a new keys could be created while you iterate your old keys.

**Comment by spaulg** [comment]
Though I'm by no means any expert in Netty or Redis, and I'm assuming both clients make the call to Redis using the same command, as I see it, once the command is issued to the server and the server has responded, the 'atomicity' of the command has already passed. How the client handles processing of the response, be it a stream or buffered response to a list, makes no difference if its all transferred over a network in the same way.

Even if the key list is buffered to a list on the client, the keys on the Redis server have probably changed by then anyway.

**Comment by spaulg** [comment]
Looking at the Redis documentation, I should be using scan, not keys, which is a cursor like implementation that allows batches of keys to be sent from the Redis server for production use.

**Comment by mrniko** [comment]
scan - nice command, i'll add support of it

**Comment by mrniko** [comment]
SCAN support added
