### ISSUE TITLE
ReentrantReadWriteLock implementation

### ISSUE THREAD

**Issue by mrniko** [mrniko/redisson#206]

**Comment by kevin1294** [comment]
any ETA on this feature?  This would be incredibly useful.  Thanks!

**Comment by mrniko** [comment]
@kevin1294 during this month, i hope

**Comment by mrniko** [comment]
I think to use follow state structure: {readLockCounter, writeLockCounter, writeOwnerThread}

**Comment by mrniko** [comment]
ReadWriteLock is fully implemented. Currently I'm writing a test for it.

**Comment by mrniko** [comment]
Done
