### ISSUE TITLE
Reactive Streams support

### ISSUE THREAD

**Issue by mrniko** [mrniko/redisson#210]

**Comment by mrniko** [comment]
@hepin1989 hi! could you review the implementation? may be you have any suggestions?

**Comment by hepin1989** [comment]
sorry I am not that familiar with rx-java :(.
I was thinking a Reactive-Stream.

**Comment by mrniko** [comment]
Why Reactive-Stream? i thought rx-java is a standard in this area

**Comment by hepin1989** [comment]
Anyway,it would be nice to have:)I am using akka/scala a lot ,maybe that:).

But once you implement RS,then you have RX for free,there is a bridge.

**Comment by mrniko** [comment]
> But once you implement RS,then you have RX for free,there is a bridge.

And not vice versa? is there a RX -> RS bridge?

**Comment by hepin1989** [comment]
I think noop,I will use rx-scala for leverage,thanks :)

**Comment by hepin1989** [comment]
BTW,Reactive-Stream will be Flow in JDK 9:)

**Comment by mrniko** [comment]
https://github.com/ReactiveX/RxJavaReactiveStreams - can convert rx to rs as i see.

**Comment by hepin1989** [comment]
Then it's bidi way:) nice,thanks for point out.

**Comment by mrniko** [comment]
Anyway i'll think about Reactive-Stream implementation. Thanks for info!

**Comment by mrniko** [comment]
@hepin1989 I finnaly switched to reactive streams! thanks for advice

**Comment by hepin1989** [comment]
@mrniko WOW,there is a tck so,https://github.com/reactive-streams/reactive-streams-jvm/tree/master/tck.

**Comment by mrniko** [comment]
@hepin1989 I finished with integration! It's based on `reactor-stream` lib from `projectreactor` project. What do you think should i expose `Stream` object instead of `Publisher` interface for each method?

**Comment by hepin1989** [comment]
@mrniko I think the Publisher is OK,but if you leverage RX I think you should.
cc @viktorklang,any help?

**Comment by viktorklang** [comment]
I guess it depends on whether you want to hide the fact that Reactor is used or not to the end user.
I'd probably expose Publisher but it depends on how you envision it to be used?

**Comment by mrniko** [comment]
ok, I'll use Publisher. So, integration is done and you may check it :)
