### ISSUE TITLE
extract drainToAsync ?

### ISSUE THREAD

**Issue by hepin1989** [mrniko/redisson#212]
this would be nice

**Comment by mrniko** [comment]
Done

**Comment by hepin1989** [comment]
wow,Thanks.I will upgrade to 2.1.1 later,you know what?the new async interface with scala's future implicit conversion and akka actor works very fine.thanks very much.

**Comment by mrniko** [comment]
> the new async interface with scala's future implicit conversion and akka actor works very fine.thanks very much.

Oh, knowledge of this it's a ray of sunshine for me. Thanks for using. You could tell me you project name and i'll add it to `Projects using Redisson` section if you want, of course.

**Comment by hepin1989** [comment]
@mrniko I want but it was a part of a mobile game server,the project name is "super heros".we are currently using the redis as a message queue and for the player's ranking lists with redisson.

really thanks for you work.I am sure we will find many other intersting part with this project.
:100:
