### ISSUE TITLE
Redis healthcheck using Redisson PING

### ISSUE THREAD

**Issue by nareshsankapellyfkrt** [mrniko/redisson#215]
Can you add ping in Redisson which helps in healthcheck?

**Comment by mrniko** [comment]
will be implemented in #196

**Comment by mrniko** [comment]
use `redisson.getNodesGroup().pingAll` or use `redisson.getNodesGroup().getNodes().ping`

**Comment by psakthisivram** [comment]
I used `redisson.getNodesGroup().pingAll()` to ping redis. This returns `true` although redis server is down. Can someone clarify ? Is there a better alternate ?
