### ISSUE TITLE
Opening new connections in org.redisson.CommandExecutorService#async

### ISSUE THREAD

**Issue by AmigoV** [mrniko/redisson#223]
Rmap.addAndGetAsync (and any *Async methonds) - as i understand it shouldn't lock the calling thread, and return value (Future) as soon as possible.
But if for any reason connection is not established yet the calling thread will be blocked.
And if redis server is not available at all it will be blocked for very long period of time.

Maybe i'm wrong but it doesn't look like async nor lock-free.

**Comment by mrniko** [comment]
You are right. Connection should be established in async too. But as i wrote the underlying Redis client used by Redisson is fully async and lock-free not the Redisson whole

**Comment by mrniko** [comment]
But if you check RBatch it's fully implemented with async-nature

**Comment by AmigoV** [comment]
thx, it seems RBatch suits me very well

**Comment by AmigoV** [comment]
No, it doesn't :)

Yes, RBatch allows me to queue updates without blocking.
But as soon as i try to execute them (RBatch#executeAsync) the same situation will happens again: the calling thread will be blocked till connection is established or till it fails to connect.

**Comment by mrniko** [comment]
done
