### ISSUE TITLE
Expirable RCountDownLatch

### ISSUE THREAD

**Issue by tburch** [mrniko/redisson#224]
Is there a reason that `RCountDownLatch` doesn't implement `RExpirable`? I'd like to be able to create a CountDownLatch that goes to 0 or is deleted if `countDown` isn't called the desired number of times before a timeout.

**Comment by mrniko** [comment]
Then CountDownLatch reaches the 0 it publish a `zeroCountMessage` via pub\sub. During expiration same message should be published too. There is no way in Redis to schedule a publish operation.

**Comment by xhga** [comment]
I have the same question, 
```
RCountDownLatch countDownLatch = redissonClient.getCountDownLatch(key);
        try {
            countDownLatch.trySetCount(1);
            // todo: I want to set the expiration time of the key here
            Thread.sleep(10000);
            boolean await = countDownLatch.await(10L, TimeUnit.SECONDS);
            return await + "";
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
```
