### ISSUE TITLE
Leak issues

### ISSUE THREAD

**Issue by ezs** [mrniko/redisson#239]
When using redisson, I'm occasionally getting errors like this: "LEAK: you are creating too many HashedWheelTimer instances".What are possible causes of this issue? 

I'm also seeing (probably related) errors like this: "LEAK: HashedWheelTimer.release() was not called before it's garbage-collected." I assume this is related to my problem, but I don't know where to look in my code for this leak. Could this be a bug?

Thanks!

**Comment by mrniko** [comment]
Each Redisson instance has one HashedWheelTimer. How many Redisson instances do you have simultaneously?

**Comment by mrniko** [comment]
Starting from https://github.com/mrniko/redisson/issues/134 you don't need to use multiple Redisson instances for each codec.
