### ISSUE TITLE
Read split feature in Sentinel mode

### ISSUE THREAD

**Issue by nareshsankapellyfkrt** [mrniko/redisson#240]
Hi, 

I have a setup with a master, 3 slaves and 3 sentinel nodes. I do not have too much data and cluster setup is not required. I should be able to support high throughput(400K Ops/sec). Most of them are read operations. Is there any way to split read requests among master and slaves? 

If there is no way to do this, can this feature be added? 

Thanks
Naresh

**Comment by jackygurui** [comment]
I think it is already doing so. SentinelConnectionManager by default is configured with RoundRobinLoadBalancer which rotates around the node group for each read ops.

**Comment by mrniko** [comment]
@nareshsankapellyfkrt all read operations will be executed on slave nodes if you mean that.

**Comment by nareshsankapellyfkrt** [comment]
Thanks. I did not know that. I'm not able to scale my application beyond 80K ops/second with 2 slaves. I will investigate further and come up with the exact numbers.

**Comment by mrniko** [comment]
@nareshsankapellyfkrt will wait for it

**Comment by nareshsankapellyfkrt** [comment]
I forgot to update this thread. I have been able to successfully scale up to 250K QPS. Closing this issue.

**Comment by mrniko** [comment]
Could you please specify you configuration? Hardware configuration, number of slave/master servers, cluster topology. And Redis servers mode you used?
