### ISSUE TITLE
Elasticache and failover; Redisson configuration question

### ISSUE THREAD

**Issue by scubasau** [mrniko/redisson#241]
We're using Redisson 2.1.1 on our production web cluster for session persistence: https://github.com/chexagon/redis-session-manager

Our redis implemention is AWS's ElastiCache where we have 2 nodes in a replication group. Elasticache provides 3 endpoints for this scenario:
* `foobar.elasticache.com` - always points to the primary (read/write) node of the cluster
* `foobar-001.elasticache.com` - direct connection to node1
* `foobar-002.elasticache.com` - direct connection to node2

Normally `node1` is the read/write master and `node2` is a read slave with `foobar.elasticache.com` pointing to `node1`. In a failover scenario (http://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/AutoFailover.html for more info) Elasticache promotes `node2` and repoints `foobar.elasticache.com` to now point at `node2`.

Our Redisson configuration is to use a `SingleServerConfig` with the endpoint of `foobar.elasticache.com`

Last night we experienced our first ever failover (exciting!). Unfortunately, this brought our application to a standstill with errors of
```org.redisson.client.RedisException: READONLY You can't write against a read only slave.. channel: [id: 0x????????, / 10.0.x.x:yyyyy => foobar.elasticache.com]```

The 10.0.x.x address listed is that of `node1` which was demoted to read slave when `node2` was promoted to master.

My belief is that using `SingleServerConfig` here is incorrect and led to this issue (i.e., redisson remained connected to `node1` and never reconnected to `foobar.elasticache.com` to now be connected to `node2`. Am I correct in this analysis?  If so, I can't really seem to figure out _which_ config is the proper one to use. `MasterSlaveServersConfig` seems logical at first glance, but looking through the code it appears only Sentinel and Cluster configurations invoke the paths that switch the master node.

Any help would be greatly appreciated.  Thanks!

**Comment by mrniko** [comment]
You are right, `SingleServerConfig` is not intended to use in master/slave server mode. In redis there are two modes - `Sentinel` and `Cluster` in which nodes auto-discovery is possible. Please use one of them.

**Comment by scubasau** [comment]
Unfortunately I'm not terribly familiar with the internal workings of ElastiCache but I don't believe it supports either `Cluster` or `Sentinel`:
```
SENTINEL
-ERR unknown command 'SENTINEL'
CLUSTER
-ERR unknown command 'CLUSTER'
```

Relevent portions from `INFO` if this helps shed any light on the internal workings:
```
INFO
$2033
# Server
redis_version:2.8.19
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:9b2cbadb8a7553e1
redis_mode:standalone
os:Amazon ElastiCache
arch_bits:64
multiplexing_api:epoll
gcc_version:0.0.0
process_id:1
run_id:b4322f47bc7d47c86bd6b4df5290bb324be1409a
tcp_port:6379
uptime_in_seconds:41964
uptime_in_days:0
hz:10
lru_clock:15837310
config_file:/etc/redis.conf
<snip>
# Replication
role:master
connected_slaves:1
slave0:ip=172.16.0.218,port=6379,state=online,offset=67220825141,lag=1
master_repl_offset:67220846535
repl_backlog_active:1
repl_backlog_size:1048576
repl_backlog_first_byte_offset:67219797960
repl_backlog_histlen:1048576
```

I will write some quick tests to see what is happening when I failover a slave and if `MasterSlaveServersConfig` will handle it or if I need something else.

**Comment by scubasau** [comment]
https://github.com/mrniko/redisson/pull/244 adds an alternative to the DNS polling introduced in https://github.com/mrniko/redisson/pull/243

**Comment by scubasau** [comment]
Thanks for the quick merges!
