### ISSUE TITLE
Feature Request: Redisson backed ObjectCodec (Object-Hash Mapping)

### ISSUE THREAD

**Issue by jackygurui** [mrniko/redisson#246]
Now, the ability to specify a different codec per object feature is added
mrniko/redisson@d484c1959859a97559e4e8d784fd5dfdcf9aeb11, this has paved the way to implement a new type of object codec that serialise each field of POJO object into a redis hash. 

Thinking it as a persistent layer for persisting an object to redis like the EntityManager does. Using reflection/javasisst to proxy the accessors of the POJO to read/write fields straight from/to redis.

It would allow different programs to be able to share sets of live data without needing to serialise and deserialise the entire object.

**Comment by jackygurui** [comment]
I think this request is fairly reasonable since there are a increasingly number of projects are/wanting to use redis as the main data store.

**Comment by mrniko** [comment]
I didn't get you. Could you provide an example of how this feature should looks in code from your vision of task? Or you need a Redis-based ORM with own EntityManager you may use a [Kundera](https://github.com/impetus-opensource/Kundera) in this case it supports Redis.

**Comment by mrniko** [comment]
And what about inner object, say collection?

**Comment by jackygurui** [comment]
Right, let me explain what I mean with a bit more detail with some code sample, but firstly please accept my apology for the vague request.

Lets be honest, when we write a POJO class, usually we use it to organise a collection of relevant information together. Although fundamentally, you could replace the POJO class with a hash map, it is less intuitive than the POJO method.

More times than not, we need to pass this collection of information, an instance of the POJO class, to other parts of the system, the information kept in the instance could be written to or read from concurrently by different threads / tasks. If the requirement for some parts of the system is to always keep up-to-date with the state of an instance, traditionally, it can be done by make fields in that instance volatile. However, it is not a easy task when you are running a system comprised of multiple micro services.

Since serialising the instance detaches it away from its state, to truly share a state-full information in such environment is to keep each field of the instance in a system like Redis. Obviously, thanks for you work, Redisson has provided a very convenient way to access the information stored in Redis. However, you can't keep an state-ful instance in Redis through Redisson. You have to replace the POJO class to a hash map. 

What I am requesting is to have a mechanism that does it for us.

I am going to illustrate what I mean with a piece of sample code:
```java
package com.example.code
....
public class ExampleCode {
    String field1;
    String field2;
}
```

Hypercritically, there are multiple instances of this class and they can be stored in Redis in two hash maps:

Hashmap | com.example.code.ExampleCode#field1 | com.example.code.ExampleCode#field2
------------ | ------------- | -------------
Field | instance1 ID | instance1 ID
Value | instance1 value | instance1 value
Field | instance2 ID | instance2 ID
Value | instance2 value | instance2 value
... | ... | ...
... | ... | ...
Field | instanceN ID | instanceN ID
Value | instanceN value | instanceN value

As for a inner object, if it is required, it can be stored the same way, the containing parent would have a value that represents the full class name and the id of the instance. or it could be serialised if the inner object is not required to be state-ful. 

For collection fields, depending on what type they are, can be stored in the similar way. For example: lets say field3 of the above class is a HashSet, you would have a Hashmap representing the field like this:

Hashmap | com.example.code.ExampleCode#field3
------------ | -------------
Field | instance1 ID
Value | java.util.HashSet:hashset1 ID
Field | instance2 ID
Value | java.util.HashSet:hashset2 ID
... | ... 
... | ... 
Field | instanceN ID 
Value | java.util.HashSet:hashsetN ID 

Then you would have some Redis Sets with the name as "java.util.HashSet:hashset1 ID", "java.util.HashSet:hashset2 ID", "java.util.HashSet:hashsetN ID", etc. With in them, they can have values of simple data types or could have other inner objects or collections.

**Comment by jackygurui** [comment]
Have been thinking about this again, this feels like Aerospike's Records and Bins in someway but less like the Kundera. I hope my explanation has cleared all the confusions you had.

**Comment by mrniko** [comment]
Yeah, it's a great idea. You have a bright head! :) Thanks for your full explanation. With such feature we don't need to lock a whole object to change only one field, for example.

**Comment by jackygurui** [comment]
You're right, with this feature in the library, for us the developer, it would be like having a shared/clustered heap space between VMs. It would reduce the complexity of creating micro services by a lot.

**Comment by mrniko** [comment]
Done!
