### ISSUE TITLE
Add serialization codec for java Number

### ISSUE THREAD

**Issue by Master-chan** [mrniko/redisson#247]
By default any Number class descendants is serialized as ["java.lang.Long",1843] for example.

**Comment by mrniko** [comment]
`LongCodec` already implemented

**Comment by Master-chan** [comment]
Sorry for not clearly explaining, I mean set this codec as default for any java primitive wrapper objects.

**Comment by mrniko** [comment]
then, for example, there is no way to distinguish `Integer` and `Long`.

**Comment by Master-chan** [comment]
Well, I clearly don't understand how codecs work now. Btw I'm only using String and Long objects in my project so can I safely set codec to StringCodec.INSTANCE or LongCodec.INSTANCE in my Redisson config?

**Comment by mrniko** [comment]
if you use `RMap` there key stored as Long type and value as String. You need to extend `getMapKeyDecoder` and `getMapKeyEncoder` methods of `StringCodec` in this case.

**Comment by Master-chan** [comment]
Is there any way to register more than one Codec for Redisson instance?
For example in Gson I can do
```java
GsonBuilder gson = new GsonBuilder();
gson.registerTypeAdapter(MyType.class, new MySerializer());
gson.registerTypeAdapter(MyType.class, new MyDeserializer());
```

Sorry for inconvenience but I can't find any guides\examples for this.

**Comment by mrniko** [comment]
You can use objects with different codecs. This feature implemented in `master` branch.
For example like this `getMap("map", StringCodec.INSTANCE)`

**Comment by Master-chan** [comment]
Big thanks for the answers.
