### ISSUE TITLE
Redis master change is not detected properly.

### ISSUE THREAD

**Issue by mgreenstein** [mrniko/redisson#250]
Redisson does not seem to be detecting Redis master change in failover scenario.  (We are using Redisson 2.1.3).

I have 2 questions regarding this.

1. After the 60-second timeout (described below) everything started working again, although not in the original configuration.  Can this timeout be changed (lowered) and done so safely?

2. Should Redisson should be able to detect and react to this last master change back to our original configuration?  We were assuming that it should.

Details are below.  

I can provide the redis commands we used to reconfigure Redis if they will help.

Thank you very much.

--Michael

========== 

In testing redis failover we have discovered that moving a master instance frmo one instance to another causes all our servers to hang.  We have reproduced the issue several times with the following process.

We are running 3 Redis servers (redis-01, redis-02, and redis-03).  Each server is running both a redis master and a redis slave.  Each master is associated with a slave on one of the other redis servers.

Start multiple work sessions on our application servers running light load
- On redis-01, get a list of the redis instances running on this server (ps -ef | grep redis)

- kill -9 <redis process pids>
[At this point everything appears great - the test continues to run.  The slave instance has taken over the responsibilities for the failed redis node.  run "redis-cli cluster nodes" for a list of all the nodes, the reassigned master and a list of the failed shards.]

- restart redis on the "failed" server - "service redis_master start" "service redis_slave start"
[After 60 seconds, we see our first indication of trouble - we get a redis connection timeout exception on each of the application servers.  If you look at the "cluster node" output you should see the two instances back in the list, however at this point they are both slave nodes.  Another server will have two master instances on it.]

- rebalance the redis nodes - on the server that you just restarted the services, run "redis-cli cluster failover" this tells redis to failover the remote master to this instance.  After this step you should be back to the original configuration with one master and one slave instance on each server, with no master/slave combination on the same server.

This is where our application servers seem to hang.  From yourkit we see several of these:

++++++++++

 http-bio-7001-exec-1 [WAITING] [DAEMON]
java.lang.Object.wait() Object.java:503
io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly() DefaultPromise.java:286
io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly() DefaultPromise.java:32
org.redisson.CommandExecutorService.get(Future) CommandExecutorService.java:181
org.redisson.RedissonObject.get(Future) RedissonObject.java:48
org.redisson.RedissonBucket.set(Object, long, TimeUnit) RedissonBucket.java:58
com.artfact.am2.service.MemoryManager.setValue(String, Object, long, TimeUnit) MemoryManager.java:154

----------

**Comment by mrniko** [comment]
> After the 60-second timeout (described below) everything started working again, although not in the original configuration. Can this timeout be changed (lowered) and done so safely?

**Comment by mgreenstein** [comment]
Thanks for the timeout explanation.  What about detecting and reacting to the change in master? (It is a separate issue from the timeout.)  Thanks again.

**Comment by mrniko** [comment]
Let me clarify the test case:

1. run 3 master instances and 3 slave instances in one cluster
2. kill one master and related slave node
3. restart master and slave nodes from step 2
4. run "redis-cli cluster failover" for master and slave nodes from step 2

Am i right?

**Comment by mgreenstein** [comment]
[cid:image003.png@01D0FA96.A4E0D1E0]




________________________________

**Comment by mgreenstein** [comment]
I believe this is correct.  

![capture](https://cloud.githubusercontent.com/assets/10212091/10171913/68138516-66aa-11e5-8115-ef90d4abbb8b.PNG)

**Comment by mrniko** [comment]
Why did you closed it?

**Comment by mgreenstein** [comment]
I didn't mean to.  I did it by mistake.  Sorry about that.


________________________________

**Comment by mgreenstein** [comment]
Closed by mistake.

**Comment by mgreenstein** [comment]
We did more testing in a slightly different way and still see this issue.  Also wanted to make sure we were running Redisson 2.1.3.  Here is a stack trace from yourkit if it will help.  (Looks something like the last issue we reported.)  Thanks.

 http-bio-7001-exec-8 [WAITING] [DAEMON]
java.lang.Object.wait() Object.java:503
io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly() DefaultPromise.java:286
io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly() DefaultPromise.java:32
org.redisson.CommandExecutorService.get(Future) CommandExecutorService.java:181
org.redisson.RedissonObject.get(Future) RedissonObject.java:48
org.redisson.RedissonBucket.get() RedissonBucket.java:38
com.artfact.am2.service.MemoryManager.getValue(String) MemoryManager.java:103
com.artfact.am2.model.Auction.isOpen() Auction.java:302
com.artfact.am2.service.CommandProcessor.checkAuction(Auction, Command) CommandProcessor.java:255
com.artfact.am2.service.CommandProcessor.getAuction(String, Command) CommandProcessor.java:235
com.artfact.am2.service.CommandProcessorSell.execute(String, Command, String) CommandProcessorSell.java:25
com.artfact.am2.service.AuctionControllerService.doPosts(HttpServletRequest, HttpServletResponse, String, String) AuctionControllerService.java:712
com.artfact.am2.controller.AuctionController.doPostsAuction(HttpServletRequest, HttpServletResponse) AuctionController.java:42
java.lang.Thread.run() Thread.java:745

**Comment by mrniko** [comment]
Could you check please, does "CLUSTER NODES" command returns the same config as it was at redisson init after redis nodes rebalance?

**Comment by mgreenstein** [comment]
We did use "CLUSTER NODES" initially and after rebalancing.

Question: Does the order of nodes matter when making this call initially? 

config.useClusterServers().addNodeAddress()

We call this method 3 times, one for each node.  We randomize the order of the nodes prior to the call.  This randomization shouldn't matter, should it?

**Comment by mrniko** [comment]
The sequence of node addition is doesn't matter

**Comment by mrniko** [comment]
@mgreenstein could you check it again with master branch? I have made some improvements applied to master change problem in #264 issue

**Comment by mgreenstein** [comment]
We retested using the master branch (2.1.4-SNAPSHOT) today.  It appears to work properly.  Thank you very much.

**Comment by mrniko** [comment]
Good news! Thanks for your patience!
