### ISSUE TITLE
Can i use redisson for the “mget/mset” multi-command?

### ISSUE THREAD

**Issue by deep011** [mrniko/redisson#263]
I can not find “mget/mset” api in redisson, whether redisson support those multi-command? and for redis cluster mode?

**Comment by mrniko** [comment]
You can use it via `Redisson.createBatch` method. It accumulates all invoked commands in one batch command.

**Comment by deep011** [comment]
yeah, i know! thank you very much!

**Comment by flashas8** [comment]
Hi @mrniko. I don't think that's the proper solution. Is there a cause why there is no usage of redits MGET?

**Comment by mrniko** [comment]
Hi @flashas8. I can add follow method to `RedissonClient` interface, which will use MGET operation:
```java
<V> List<RBucket<V>> getBuckets(List<String> keys);
```

That do you think about it?

**Comment by flashas8** [comment]
That would be absolutely awesome!

**Comment by mrniko** [comment]
@flashas8 I thought about this feature again and decided to return value Map instead of `RBucket` objects. Because `RBucket` it always a live view of object state and it would be wrong to initialize it with already loaded value. So my suggestion to return `Map<Key, Value>`:
```java
<V> Map<String, V> loadBucketValues(List<String> keys)
```
Any comments are welcome

**Comment by flashas8** [comment]
Sounds great!

**Comment by mrniko** [comment]
I created #330 for it

**Comment by flashas8** [comment]
Cool stuff! But what do you think about the insert with `MSET`?

**Comment by mrniko** [comment]
@flashas8 I moved this task to separate issue https://github.com/mrniko/redisson/issues/336

**Comment by ToryZhou** [comment]
> 对于Mget，用的是 redissonClient.getBuckets(new StringCodec()).get( new String [] );
> 这里codec要自己制定，默认是jackson的格式，返回是map

这个方法解决拉, 还是中国人善于解决问题

**Comment by benweizhu** [comment]
redissonClient.getBuckets(new StringCodec()).get( new String [] );
look inside, seems @Chanllenger is correct
```
    @Override
    public RBuckets getBuckets(Codec codec) {
        return new RedissonBuckets(codec, connectionManager.getCommandExecutor());
    }
    @Override
    public <V> Map<String, V> get(String... keys) {
        RFuture<Map<String, V>> future = getAsync(keys);
        return commandExecutor.get(future);
    }

```
