### ISSUE TITLE
A serious mistake for redisson cluster!

### ISSUE THREAD

**Issue by deep011** [mrniko/redisson#264]
hi, @mrniko 

when i execute the "cluster nodes" command, and displays like "7189722a77350361478f826e549e13270499261c 127.0.0.1:6309 master - 0 1445484940172 5 connected 0-299 5761-10922", then the redisson will go wrong:

org.redisson.client.RedisEmptySlotException: No node for slot: 9842
	at org.redisson.connection.MasterSlaveConnectionManager.connectionWriteOp(MasterSlaveConnectionManager.java:481)
	at org.redisson.CommandExecutorService.async(CommandExecutorService.java:434)
	at org.redisson.CommandExecutorService$5.run(CommandExecutorService.java:421)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:581)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:655)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:367)
	at java.lang.Thread.run(Thread.java:745)

i review the parse() function in ClusterConnectionManager.java, and it only parses one pair start_slot and end_slot. 

Is it right, or my understanding is wrong?

**Comment by mrniko** [comment]
As I see there are two ranges for one node. I didn't take into account this

**Comment by mrniko** [comment]
fixed

**Comment by deep011** [comment]
hello @mrniko , thanks for the quick reply, and did you test it for that you fixed?
It is always wrong!
It only added the last range for the node in the parsePartitions() function!
Please give me the courage to use redisson for redis cluster. I neet it hurriedly!

**Comment by deep011** [comment]
Besides, the "cluster nodes" command can be display like the follows:

"7189722a77350361478f826e549e13270499261c 127.0.0.1:6309 master - 0 1445484940172 5 connected 0-299"
"7189722a77350361478f826e549e13270499261c 127.0.0.1:6309 master - 0 1445484940172 5 connected 0-299 5761-10922"
"7189722a77350361478f826e549e13270499261c 127.0.0.1:6309 master - 0 1445484940172 5 connected 0-299 5761 10000-10922"
"7189722a77350361478f826e549e13270499261c 127.0.0.1:6309 master - 0 1445484940172 5 connected 0-298 5761 10000-10922 [299->-9a4244103035a0fa494d9a375fb13b8cadb3fc4f]"
"7189722a77350361478f826e549e13270499261c 127.0.0.1:6309 master - 0 1445484940172 5 connected 0-298 5761 10000-10922 [300-<-9a4244103035a0fa494d9a375fb13b8cadb3fc4f]"

**Comment by deep011** [comment]
code possible be like flollows

In the parsePartitions() function:
            String id = clusterNodeInfo.getNodeId();
            if (clusterNodeInfo.getFlags().contains(Flag.SLAVE)) {
                id = clusterNodeInfo.getSlaveOf();
            }
            ClusterPartition partition = partitions.get(id);
            if (partition == null) {
                partition = new ClusterPartition();
                partitions.put(id, partition);
            }
            else if(partition.getStartSlot() != clusterNodeInfo.getStartSlot())
            {
            	partition = new ClusterPartition();
            }

            if (clusterNodeInfo.getFlags().contains(Flag.FAIL)) {
                partition.setMasterFail(true);
            }

in the parse() function:
            if(parts.length == 1)
            {
                    node = new ClusterNodeInfo(node);
                    node.setStartSlot(Integer.valueOf(parts[0]));
                    node.setEndSlot(Integer.valueOf(parts[0]));
                    nodes.add(node);
            }
            else if(parts.length == 2)
            {
                    node = new ClusterNodeInfo(node);
                    node.setStartSlot(Integer.valueOf(parts[0]));
                    node.setEndSlot(Integer.valueOf(parts[1]));
                    nodes.add(node);
             }
             else
             {
                     continue;
             }

**Comment by mrniko** [comment]
Sorry i don't have such cluster config. So i didn't test it correctly. Could you give me redis configs for this case?

**Comment by deep011** [comment]
You can use "redis-trib.rb reshard --slots" command.

**Comment by deep011** [comment]
And i find redisson do not deal "ASK" error, so when i migrate the slots redisson maybe go wrong.

**Comment by mrniko** [comment]
Do you migrate slots with "redis-trib.rb reshard --slots" command?

**Comment by deep011** [comment]
yes, i use the command.

**Comment by mrniko** [comment]
@deep011 could you please check it again?

**Comment by mrniko** [comment]
@deep011 ASK handling in progress

**Comment by mrniko** [comment]
Done
