### ISSUE TITLE
receiving multiplied PubSub messages

### ISSUE THREAD

**Issue by lake4790k** [mrniko/redisson#276]
Little modification to the testHeavyLoad reveals the problem I encountered when having a single listener processing many messages sent at the same time (in latest version):

    volatile long counter;

    @Test
    public void testHeavyLoad() throws InterruptedException {
        final CountDownLatch messageRecieved = new CountDownLatch(1000);

        Redisson redisson1 = BaseTest.createInstance();
        RTopic<Message> topic1 = redisson1.getTopic("topic");
        topic1.addListener(new MessageListener<Message>() {
            @Override
            public void onMessage(String channel, Message msg) {
                Assert.assertEquals(new Message("123"), msg);
                messageRecieved.countDown();
                counter++;
            }
        });

        Redisson redisson2 = BaseTest.createInstance();
        RTopic<Message> topic2 = redisson2.getTopic("topic");
        topic2.addListener(new MessageListener<Message>() {
            @Override
            public void onMessage(String channel, Message msg) {
                Assert.assertEquals(new Message("123"), msg);
                messageRecieved.countDown();
            }
        });

        for (int i = 0; i < 500; i++) {
            topic2.publish(new Message("123"));
        }

        messageRecieved.await();

        Thread.sleep(1000);

        assertEquals(500, counter);

        redisson1.shutdown();
        redisson2.shutdown();
    }

Running the test will fail for me many (but not every) time saying the listener got like 9000 messages instead of the 500 sent.

**Comment by mrniko** [comment]
it seems like it's a bug in CommandDecoder. I'm working on fix

**Comment by mrniko** [comment]
Fixed

**Comment by lake4790k** [comment]
Looks good now, thanks for the superfast fix!
