### ISSUE TITLE
RLock.isLocked() get hung when I disable/enable my local network

### ISSUE THREAD

**Issue by zuanfan** [mrniko/redisson#285]
I was crashed into a blocking issue when I was doing some configuration on my windows laptop. RLock.isLocked()  got hung forever with callstack as following:

```
Callstack:
Object.wait(long) line: not available [native method]	
DefaultPromise<V>(Object).wait() line: 503	
DefaultPromise<V>.awaitUninterruptibly() line: 286	
DefaultPromise<V>.awaitUninterruptibly() line: 32	
CommandExecutorService.get(Future<V>) line: 145	
CommandExecutorService.read(String, Codec, RedisCommand<T>, Object...) line: 160	
CommandExecutorService.read(String, RedisCommand<T>, Object...) line: 155	
RedissonLock.isLocked() line: 389	
```

The issue is repreduceable. Steps to reproduce the issue:

Code:

```
 RLock mRLock = //initialize the redisson lock
 if (mRLock.isLocked()) {
 }
```

My os is windows, and I haven't tested it on linux. 
Steps: disable network.  Then enable network. The program will be blocked with the callstack I pasted

**Comment by mrniko** [comment]
Ok. I'll check it

**Comment by mrniko** [comment]
I got timeout error after 60 seconds (could be changed via timeout config param).

org.redisson.client.RedisTimeoutException: Command execution timeout for /127.0.0.1:7002
	at org.redisson.client.RedisConnection.await(RedisConnection.java:104)
	at org.redisson.client.RedisConnection.sync(RedisConnection.java:119)

Redisson version is 2.1.4

**Comment by mrniko** [comment]
It seems like you used an old version, because code line positions in your stack trace differ from latest Redisson version.
