### ISSUE TITLE
Where is ZRANGEBYSCORE command 

### ISSUE THREAD

**Issue by damacheng009** [mrniko/redisson#290]
I can not find anything in RScoredSortedSet class...

**Comment by mrniko** [comment]
This command is used in `RedissonScoredSortedSet.valueRange` and `entryRange` command and other variations of such commands.

**Comment by damacheng009** [comment]
@Test
    public void testValueRange() {
        RScoredSortedSet<Integer> set = redisson.getScoredSortedSet("simple");
        set.add(0, 1);
        set.add(1, 2);
        set.add(2, 3);
        set.add(3, 4);
        set.add(100, 5);
        set.add(200, 5);

        Collection<Integer> vals = set.valueRange(100, 200);
        MatcherAssert.assertThat(vals, Matchers.contains(5));
    }

It fail...

**Comment by damacheng009** [comment]
RedissonScoredSortedSet.valueRange and entryRange base on index, not score...

**Comment by mrniko** [comment]
How about this method `valueRange(double startScore, boolean startScoreInclusive, double endScore, boolean endScoreInclusive)` ?

**Comment by mrniko** [comment]
please take a look closely, also a new methods was added to this class from this request https://github.com/mrniko/redisson/pull/282

**Comment by damacheng009** [comment]
<groupId>org.redisson</groupId>
<artifactId>redisson</artifactId>
<version>2.1.4</version>

I use this version..
I looking forward the new version：）

**Comment by mrniko** [comment]
those methods are not the part of 2.1.4 version

**Comment by mrniko** [comment]
Did you find it?

**Comment by damacheng009** [comment]
I did，Thanks：）
