### ISSUE TITLE
What does RBatch.execute() return?

### ISSUE THREAD

**Issue by joshattr** [mrniko/redisson#293]
Hello. I have an RBatch variable that I've added some commands to. I noticed if I tax redis a bunch sometimes it has trouble writing a backup file (this might be the fault of my weak vm). At any rate, I'd like to detect this failure mode and tell the user about it if it ever happens. 

I'm trying to figure out what RBatch.execute returns. There [aren't any javadocs](https://github.com/mrniko/redisson/blob/f3a3a4a82d0e3e879943252a1a5da6d4990326ee/src/main/java/org/redisson/core/RBatch.java#L177) on this. I either get one of two responses:
```
[null, true, false, true, false ...]
```
or
```
[null, null, null, null, null ...]
```
The second one indicates failure.

[The wiki](https://github.com/mrniko/redisson/wiki/Usage-examples#multiple-commands-batch-commands-pipelining) suggests these are responses to the specific commands, which agrees with what I would assume from [`EXEC`](http://redis.io/commands/exec), but I'm not sure why I'm getting boolean results, because the commands I'm running should all be add commands (like `HSET`, `ZADD`, etc).

Do you mind updating the javadoc, and do you know why I'm getting booleans back (and what they mean) instead of ints?

**Comment by mrniko** [comment]
Thank you for report! It was a bug. Now errors during batch execution are handing correctly and RedisException will be raised.

**Comment by mrniko** [comment]
Which Redisson methods do you execute in batch? Each command result type will be equal to type of executed Redisson method.

**Comment by mrniko** [comment]
> because the commands I'm running should all be add commands (like HSET, ZADD, etc).

I intend to fix it in https://github.com/mrniko/redisson/issues/296

**Comment by joshattr** [comment]
About the booleans... this was my mistake. I'm casting the list. It was a long Friday :smile:. Let me know if you need more info from me for #296.
