### ISSUE TITLE
Duplicate values are returned with redisson.getSet

### ISSUE THREAD

**Issue by nareshsankapellyfkrt** [mrniko/redisson#300]
Hi, 

I'm getting duplicate entries with redisson.getSet. 

Redis command "SMEMBERS pSet" returns the following. 
1) "\"MOBD5G7DDCRHQCHS\""
 2) "\"MOBE4G6GTTD33ZUT\""
 3) "\"MOBEY39PGWFVQHQE\""
 4) "\"9788129135728\""
 5) "\"MOBDP6W6MCUWCFGV\""
 6) "\"MOBDDA5Y6BKX6VHR\""
 7) "\"MOBDA3N2XBF74DSJ\""
 8) "\"MOBE4G2SKSQJSPGJ\""
 9) "\"MOBEBZPYZEVYCYWM\""
10) "\"MOBDGY7DGAAN7SZY\""
11) "\"MOBDCAJJJ55SCWBY\""
12) "\"MOBEBZZGKH7QGZKH\""

redisson.getSet is returning the following values. 
"MOBEBZPYZEVYCYWM",
   "MOBE4G6GTTD33ZUT",
   "MOBDDA5Y6BKX6VHR",
   "9788129135728",
   "MOBEY39PGWFVQHQE",
   "MOBDCAJJJ55SCWBY",
   "MOBD5G7DDCRHQCHS",
   "MOBE4G2SKSQJSPGJ",
   "MOBDGY7DGAAN7SZY",
   "MOBDP6W6MCUWCFGV",
   "MOBEBZPYZEVYCYWM",
   "MOBDP6W6MCUWCFGV",
   "MOBDDA5Y6BKX6VHR",
   "MOBDA3N2XBF74DSJ",
   "MOBDGY7DGAAN7SZY",
   "MOBDCAJJJ55SCWBY",
   "MOBEBZZGKH7QGZKH"

Please notice that MOBDGY7DGAAN7SZY is repeated.

**Comment by mrniko** [comment]
Hi!

Which Redisson version do you use?

**Comment by nareshsankapellyfkrt** [comment]
1.3.0

**Comment by mrniko** [comment]
Can't reproduce it with 2.1.5. Please upgrade to this version.

**Comment by nareshsankapellyfkrt** [comment]
Sure. I will upgrade and check.

**Comment by mrniko** [comment]
have you checked it?

**Comment by nareshsankapellyfkrt** [comment]
Yes. It worked fine.
