### ISSUE TITLE
Ping fails if requirePass is set

### ISSUE THREAD

**Issue by Kindrat** [mrniko/redisson#304]
Can't ping single node either with ping or pingAll commands - getting `NOAUTH Authentication required`

Piece of code
```java
Collection<Node> nodes = redisson.getNodesGroup().getNodes();
Map<Node, Boolean> statuses = mapToMap(nodes, k -> k, Node::ping);
boolean dbIsReady = !statuses.values().stream().filter(bool -> !bool).findFirst().isPresent();
if (!dbIsReady) {
    List<InetSocketAddress> hosts = nodes.stream().map(Node::getAddr).collect(toList());
    log.warn("Could not reach redis nodes : {}", hosts);
    return;
}
```
Full exception
`DefaultPromise@1409814d(failure(org.redisson.client.RedisException: NOAUTH Authentication required.. channel: [id: 0x3299d81d, /127.0.0.1:35080 => /127.0.0.1:6379] command: CommandData [promise=DefaultPromise@1409814d(incomplete), command=(PING), params=[], codec=null])`

*ENV*
Server: 3.0.3
Client: 2.1.5

**Comment by mrniko** [comment]
Fixed. And i suggest you to use `getNodesGroup().pingAll()` method instead.

**Comment by Kindrat** [comment]
Needed info for each node to include into spring actuator healthcheck, so `pingAll` is not suitable.

**Comment by mrniko** [comment]
so, does it work now?

**Comment by Kindrat** [comment]
Fixed. Is there snapshot repository for redisson?

**Comment by mrniko** [comment]
Redisson 2.1.6 released!

**Comment by Kindrat** [comment]
Just a proposal - can't redisson use connection from pool to perform ping? Creating new connection each time may be expensive in some cases.
