### ISSUE TITLE
Redisson shutdown hangs if redis server was down

### ISSUE THREAD

**Issue by Kindrat** [mrniko/redisson#307]
*Env:*
  Server: 3.0.3
  Client: 2.1.6

*Steps to reproduce:*
* Start redis server
* Create redisson bean
* Stop on a breakpoint inside test
* Shutdown redis server
* call redisson.shutdown()

What I see is that ConnectionWatchdog is scheduling tryReconnect indefinitely incrementing attempts and connection is not closing. But if I put break point in ConnectionWatchdog#channelInactive (line 64) and stop there, connections are closing properly. Perhaps there is race condition somewhere?

**Comment by mrniko** [comment]
which server configuration do you use?

**Comment by Kindrat** [comment]
https://gist.github.com/Kindrat/e42fb077cd3cfdeaa281

**Comment by mrniko** [comment]
It seems like you using Redisson in single server mode, am I right?

**Comment by Kindrat** [comment]
yes

**Comment by mrniko** [comment]
will check it

**Comment by mrniko** [comment]
Can't reproduce it. ConnectionWatchdog stops attempt to reconnect during shutdown. Redisson exits normally

**Comment by mrniko** [comment]
Anyway i made shutdown state check in `channelInactive` method. Does it help you?

**Comment by Kindrat** [comment]
Tried to reproduce my issue with simple clean project using some of original logic without that fix, but no luck. But now everything is fine in my original build.
