### ISSUE TITLE
RedissonClient `isShutdown` check

### ISSUE THREAD

**Issue by thrau** [mrniko/redisson#323]
I'm somehow missing a possibility to check whether the current Redisson instance has been shut down already.

Are there some run-state flags that one could check? Would a `isShutdown` method  make sense in the `RedissonClient` interface? Would this be possible with the changes required for #299 ?

**Comment by mrniko** [comment]
Hi!
I agree with you. It's important to add some methods to check shutdown state. I suggest to add follow methods to `RedissonClient` and `RedissonReactiveClient` interfaces:
1. `isShuttingDown` - returns `true` if Redisson instance is being shutdown or has been shutdown already.
2. `isTerminated` - return `true` if Redisson instance has been shutdown.

**Comment by mrniko** [comment]
Done
