### ISSUE TITLE
bug! expire expireAsync use toSeconds with PEXPIRE

### ISSUE THREAD

**Issue by flym** [mrniko/redisson#324]
@Override
    public boolean expire(long timeToLive, TimeUnit timeUnit) {
        return commandExecutor.get(expireAsync(timeToLive, timeUnit));
    }

    @Override
    public Future<Boolean> expireAsync(long timeToLive, TimeUnit timeUnit) {
        return commandExecutor.writeAsync(getName(), StringCodec.INSTANCE, RedisCommands.PEXPIRE, getName(), timeUnit.toSeconds(timeToLive));
    }

the code above timeUnit.toSeconds is wrong,shoud be toMillis

**Comment by flym** [comment]
version 2.2.1

**Comment by mrniko** [comment]
It's terrible mistake. Thanks for reporting!
