### ISSUE TITLE
Auto Deploy Redis Clusters function.

### ISSUE THREAD

**Issue by doggie1989** [mrniko/redisson#326]
Redisson.createCluster.node(ipAddress,sshUsername,sshpassword).node(ipAddress,sshUsername,sshpassword).node(ipAddress,sshUsername,sshpassword).deploy();

**Comment by doggie1989** [comment]
@mrniko 
Any ideas about this one?

**Comment by mrniko** [comment]
I'll start to work on it during May-June, I think.

**Comment by doggie1989** [comment]
This function I think is very useful. I saw so many people have difficulties in deploying redis cluster.
Many Thanks!

**Comment by mrniko** [comment]
Have you received my letter?

**Comment by doggie1989** [comment]
@mrniko 
Yes! I got your letter!

**Comment by mrniko** [comment]
Nice!

**Comment by mrniko** [comment]
Do you mean only redis binaries deploy is needed including building or `./redis-trib.rb create` lunch is need too?

**Comment by doggie1989** [comment]
Before redisson, we need to learn redis cmd. Now, without knowing redis cmd,our team can still easily use redis via redisson(very simple and familiar api).

Like a lot of distributed things like hadoop,spark,redis cluster...

if you have 10 new linux machines, you need to login into each machine and config them...
if redisson could provide a way to deploy redis cluster automatically,that will be very easy to quickly have a redis cluster.
more: if the ram is not enough,we can add nodes via redisson just like redisson.addNodeToCluster(ip,sshname,sshpassword/key);
That is fantastic!!!

**Comment by mrniko** [comment]
Done https://github.com/mrniko/redisson/wiki/13.-Tools
