### ISSUE TITLE
BlockingQueue questions

### ISSUE THREAD

**Issue by jonhkr** [mrniko/redisson#327]
Hello,
I have some questions about BlockingQueue, if I have two different consumers, can I be sure that an object in the queue won't be consumed by both consumers at the same time? Does it implement any locking mechanism to prevent that?

**Comment by mrniko** [comment]
Hi!

Redis guarantees that it's impossible to pop same value by multiple clients.

**Comment by jonhkr** [comment]
Oh, nice :).

Thank you for the awesome library.
