### ISSUE TITLE
an error in RedissonSortedSet 

### ISSUE THREAD

**Issue by SaroLain** [mrniko/redisson#328]
RedissonSortedSet(Codec codec, CommandExecutor commandExecutor, String name) without 
"this.commandExecutor = commandExecutor;" 
cause throw NullPointerException at loadComparator()。

    protected RedissonSortedSet(CommandExecutor commandExecutor, String name) {
        super(commandExecutor, name);
        this.commandExecutor = commandExecutor;

        loadComparator();

        commandExecutor.write(getName(), StringCodec.INSTANCE, RedisCommands.SETNX, getCurrentVersionKey(), 0L);
    }

----

     public RedissonSortedSet(Codec codec, CommandExecutor commandExecutor, String name) {
        super(codec, commandExecutor, name);

        loadComparator();

        commandExecutor.write(getName(), StringCodec.INSTANCE, RedisCommands.SETNX, getCurrentVersionKey(), 0L);
    }

**Comment by mrniko** [comment]
`RedissonSortedSet` but it can't work without commandExecutor

**Comment by mrniko** [comment]
@SaroLain Fixed.
