### ISSUE TITLE
Suspected Memory Leak under load

### ISSUE THREAD

**Issue by optisoftjh** [mrniko/redisson#339]
Version 2.2.3 under load doing simple asynchronous set operation with small string value is running out of heap.  Heap dump shows a large number of promise objects.  I will post more details soon.

**Comment by mrniko** [comment]
Hi! This issue related to https://github.com/mrniko/redisson/issues/338

**Comment by optisoftjh** [comment]
Still seems to be the same issue.  Use around 200 connections and just do async SET operations.  Heap steadily grows until application becomes unstable due to long GC pauses.
![redisson - mem](https://cloud.githubusercontent.com/assets/16357314/11931944/af7696d6-a7bf-11e5-9824-14bd156878ba.png)
![redisson](https://cloud.githubusercontent.com/assets/16357314/11931945/af773abe-a7bf-11e5-952b-f8fff92eea8f.png)

**Comment by mrniko** [comment]
why do you think this is a memory leak? You sent much more command than could be processed. On each command Redisson creates two DefaultPromises. Even i reduce DefaultPromises to one this not resolve your problem. It seems some kind of RateLimiter needed https://github.com/mrniko/redisson/issues/75

**Comment by optisoftjh** [comment]
I can throttle the rate if required but then I am reducing the throughput of my system for only the reason that the Redis cache layer / Redisson cannot keep up.  Is there not a way to prevent those objects from mounting?  I wouldn't consider it huge throughput - currently this is around 40-50K tps.

**Comment by mrniko** [comment]
Which server mode do you use?

**Comment by optisoftjh** [comment]
Sorry - not sure I understand.  I create a client like this:
 client = new RedisClient(new NioEventLoopGroup(), NioSocketChannel.class, "localhost", 6379, 3);
 conn = future.get(1000, TimeUnit.MILLISECONDS);
then do SETS like this:
conn.async(ByteArrayCodec.INSTANCE, RedisCommands.SET, key, toBytes(value));

My service layer is also fronted with Netty.  So incoming HTTP requests get translated into some byte[] array and then we want to store those in Redis.  Thanks!

**Comment by mrniko** [comment]
You should use at least cluster config to spread keys across several masters then you achieve more than 50K tps

**Comment by mrniko** [comment]
Low level `RedisClient` usage doesn't help here

**Comment by mrniko** [comment]
Here is an config example for your case:
```java
Config config = new Config();
config.setCodec(ByteArrayCodec.INSTANCE);
config.useClusterServers().addNodeAddress("127.0.0.1:7004", "127.0.0.1:7001", "127.0.0.1:7000");
RedissonClient redisson = Redisson.create(config);
redisson.getBucket(key).set(yourData);
```

**Comment by optisoftjh** [comment]
So just so I understand - you are saying the throughput of the Redis server is the limiting factor?  This is surprising since I was under the impression a single Redis server could do much more than 50K tps.

**Comment by mrniko** [comment]
Limiting factor depends on network latency, for example. Because we can't write and forget. Redisson need to receive reply for each command before it can send next. I achieved 26K tps on local machine.

**Comment by mrniko** [comment]
I also can suggest you to try `Redisson.createBatch` object. It can execute multiple commands at one time.

**Comment by optisoftjh** [comment]
OK, I will test under some different load scenarios.  Batching might be an option.  I am also testing on just a local machine with my server implementation and Redis.

**Comment by mrniko** [comment]
For example you can accumulate commands to batch every `500ms` and send it.

**Comment by optisoftjh** [comment]
Unfortunately my SLA is 50ms or less.  So I need items into Redis within 1ms or so of being received. :-)

**Comment by mrniko** [comment]
Anyway I'm interesting to see results of your new tests.

**Comment by mrniko** [comment]
@optisoftjh you might be interested in this [PRO edition](https://redisson.pro)
