### ISSUE TITLE
Aliyun redis use 2.8.19 and not support LUA script

### ISSUE THREAD

**Issue by lefay1982** [mrniko/redisson#340]
Aliyun(http://www.aliyun.com/?spm=5176.383338.278239.2.N5cZbC&lang=en) redis use redis v2.8.19 and not support LUA script(eg. command EVAL EVALSHA SCRIPT EXISTS SCRIPT FLUSH SCRIPT KILL SCRIPT LOAD),  Redisson's RLock RList RMap use EVAL command, so I
 can not use Redisson in the Aliyun redis. 

How can I do a branch from  redisson v2.1.3 and remove the LUA script to resolve this problem ?

**Comment by mrniko** [comment]
why 2.1.3 version? branch the latest version. Here is the git command:

`git branch <newbranchname>`
