### ISSUE TITLE
topic listener decode error

### ISSUE THREAD

**Issue by jupitergao** [mrniko/redisson#341]
RBucket<String> bucket = redis.getBucket("aa");
bucket.set("aaa");
bucket.expire(10, TimeUnit.SECONDS);
RTopic<String> topic = redis.getTopic("__keyevent@0__:expired");
topic.addListener(new MessageListener<String>(){
	@Override
	public void onMessage(String channel, String msg) {
		log.debug(channel+":"+msg);
	}
});

An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception. (io.netty.channel.DefaultChannelPipeline) 
io.netty.handler.codec.DecoderException: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'aa': was expecting ('true', 'false' or 'null')
 at [Source: io.netty.buffer.ByteBufInputStream@1f3211c1; line: 1, column: 5]

Is it an issue ? or a mistake made by me? thx

**Comment by mrniko** [comment]
Please use `StringCodec` for this case. It happens because json strings are always framed with double quotes. Usage example:

`redis.getTopic("keyevent@0:expired", StringCodec.INSTANCE)`

**Comment by jupitergao** [comment]
Thank you ,work well
