### ISSUE TITLE
How to not throw an exception on connection error and retry infinitely

### ISSUE THREAD

**Issue by knguyen142** [mrniko/redisson#343]
I'm add Redis as a non-crucial data store (application can survive without it). However, when redis is down, the application will not start and will throw `Exception in thread "main" org.redisson.client.RedisConnectionException: Can't init enough connections amount!`. I would like the application to continue as usual, ideally to retry infinitely. I couldn't find this setting, and it seems like there's no way to catch the exception. Any ideas?

**Comment by mrniko** [comment]
@knguyen142 fixed. Now Redisson always throws RedisConnectionException if connection can't be established.
