### ISSUE TITLE
Redisson MasterSlaveMode with weighted load

### ISSUE THREAD

**Issue by lefay1982** [mrniko/redisson#344]
can you add this feature with load balance control between serveral slaves.

this is important when the cluster have non uniform performance.

**Comment by mrniko** [comment]
Do you need a loadBalancer with config like:
```java
Map<String, Integer> config = new HashMap<>();
config.put('12.49.1.1:3821', 0.2); // 20% requests forwards here
config.put('181.1.0.1:3811', 0.1); // 10% requests forwards here
config.put('15.1.4.1:3831', 0.7); // 70% requests forwards here
LoadBalancer balancer = new PercentWeightBalancer(config);
```
Am I right?

**Comment by lefay1982** [comment]
yes, does this feature already exsits?

**Comment by mrniko** [comment]
Not yet, will implement for you :)

**Comment by lefay1982** [comment]
LOL, thanks.

**Comment by mrniko** [comment]
http://www.cisco.com/c/en/us/support/docs/interfaces-modules/content-switching-module/28580-lb-algorithms.html

**Comment by lefay1982** [comment]
Yes, use sum of all weight, then   target weight / sum  , so I need not calculate to 100%

**Comment by mrniko** [comment]
Done

**Comment by lefay1982** [comment]
Well Done, Thanks.
