### ISSUE TITLE
Spring cache integration

### ISSUE THREAD

**Issue by mrniko** [mrniko/redisson#346]

**Comment by doggie1989** [comment]
Now I am using Redisson with Spring like below

 @Bean(destroyMethod = "shutdown")
  public Redisson getRedisson() {

    Config config = new Config();
    config.useSingleServer().setConnectionPoolSize(50)
        .setAddress("127.0.0.1:6379");
    Redisson redisson = Redisson.create(config);
    return redisson;
  }

**Comment by mrniko** [comment]
I would like to add spring cache implementation. But think about Redisson object creation too.

**Comment by mrniko** [comment]
`org.redisson.spring.cache.RedissonSpringCacheTest` for usage example
