### ISSUE TITLE
A problem

### ISSUE THREAD

**Issue by damacheng009** [mrniko/redisson#350]
This is a simple code:
        
        Config config = new Config();
	config.setCodec(new JsonJacksonCodec());
        config.useSingleServer().setAddress("127.0.0.1:6379");
        
        RedissonClient redisson = Redisson.create(config);
        
        RMap<String, Integer> map = redisson.getMap("getAll");
        map.put("str", 100);

        Integer res = map.addAndGet("str", 12);
        System.out.println(res);
        res = map.get("str");
        System.out.println(res);
        
        RMap<String, Double> map2 = redisson.getMap("getAll2");
        map2.put("str", new Double(100.2));

        Double res2 = map2.addAndGet("str", new Double(12.1));
        System.out.println(res2);
        res2 = map2.get("str");
        System.out.println(res2);
        
        redisson.shutdown();
 
        Look at the attach picture..RMap<String, Integer> generate two key:str and "str", It seems to be a bug..But RMap<Integer, Integer> will be all right..
        
![problem](https://cloud.githubusercontent.com/assets/2639932/12060142/0838ff02-afa4-11e5-9371-f83f3113f4fb.png)

**Comment by mrniko** [comment]
Fixed

**Comment by damacheng009** [comment]
Great!
