### ISSUE TITLE
hello i got a server error when i use redisson to connet AliyunRedis

### ISSUE THREAD

**Issue by Joycai** [mrniko/redisson#356]
the error like this:
"ERR unknown command eval. channel: [id: 0x73e1562f, /10.47.102.114:35465 => 126748df08bd4eea.m.cnhza.kvstore.aliyuncs.com/100.99.113.11:6379] command: CommandData [promise=DefaultPromise@40a65eef(incomplete), command=(EVAL), params=[local v = redis.call('hget', KEYS[1], ARGV[1]); redis.call('hset', KEYS[1], ARGV[1], ARGV[2]); return v, 1, loginInfo, admin, com.expresscne.parcelconfig.data.model.UserAndPermission.UserPermissionObject@175b609e], codec=org.redisson.codec.JsonJacksonCodec@5bcaeaef]",
  "path": "/system/userPermissionEndPoint"

I ask Ali's tech support about it. He told me this issue was caused by AliyunRedis not supported EVAL operation. 
How can I do?

**Comment by mrniko** [comment]
hi! Sorry but eval is necessary operation for Redisson. But you can try old version 1.2.1 it doesn't use eval commands but losing performance.

**Comment by mrniko** [comment]
Maybe it would be better try another hosting with full-featured redis support?

**Comment by Joycai** [comment]
Ok! thank you！I got it！
