### ISSUE TITLE
I found a bug when using RMap! infinity loop!

### ISSUE THREAD

**Issue by Joycai** [mrniko/redisson#357]
Here is the code:
        RMap<String, Objcet> pool = redisson.getMap("test");

        Iterator<String> iterator = pool.keyIterator();
        while (iterator.hasNext()) {
            System.out.println(key);
        }

the loop is endless!!! I am sure there is only one Object in this map because program prints same key in the console !!
How to deal with it!?

**Comment by mrniko** [comment]
I don't see `iterator.next()` method call inside your loop

**Comment by Joycai** [comment]
oh sorry i delete it . i just wanna it simple to read. 
Here is the real code in project
        RMap<String, Object> loginInfos = getRedisson().getMap("loginInfo");
        Iterator<String> itr = loginInfos.keyIterator();

        while (itr.hasNext()) {
            String key = itr.next();
            System.out.println(key);
        }

**Comment by mrniko** [comment]
i tested it like this:

```java
        RMap<Integer, Integer> map = redisson.getMap("getAll");
        map.put(1, 2);
        Iterator<Integer> iter = map.keyIterator();
        while (iter.hasNext()) {
            System.out.println(iter.next());
        }
```

All works fine

**Comment by Joycai** [comment]
Redis 3.0.6 redisson 2.2.4

**Comment by mrniko** [comment]
Could you provide your test data?

**Comment by Joycai** [comment]
key:"AB1234"

value:

{
    "@class": "com.expresscne.parcelconfig.data.model.UserAndPermission.UserPermissionObject",
    "expired": false,
    "icId": 71,
    "ip": "127.0.0.1",
    "modifyTime": 1452010348717,
    "permissionList": [
        "java.util.ArrayList",
        [
            {
                "@class": "com.expresscne.parcelconfig.data.model.UserAndPermission.DBPermissionObject",
                "create": true,
                "delete": true,
                "modify": true,
                "pageCode": "sDBUser",
                "read": true
            },
            {
                "@class": "com.expresscne.parcelconfig.data.model.UserAndPermission.DBPermissionObject",
                "create": true,
                "delete": true,
                "modify": true,
                "pageCode": "oSingleEnter",
                "read": true
            },
            {
                "@class": "com.expresscne.parcelconfig.data.model.UserAndPermission.DBPermissionObject",
                "create": true,
                "delete": true,
                "modify": true,
                "pageCode": "oPrintConfig",
                "read": true
            },
            {
                "@class": "com.expresscne.parcelconfig.data.model.UserAndPermission.DBPermissionObject",
                "create": true,
                "delete": true,
                "modify": true,
                "pageCode": "oDataSearch",
                "read": true
            },
            {
                "@class": "com.expresscne.parcelconfig.data.model.UserAndPermission.DBPermissionObject",
                "create": true,
                "delete": true,
                "modify": true,
                "pageCode": "oOrderList",
                "read": true
            },
            {
                "@class": "com.expresscne.parcelconfig.data.model.UserAndPermission.DBPermissionObject",
                "create": true,
                "delete": true,
                "modify": true,
                "pageCode": "oBatchImport",
                "read": true
            },
            {
                "@class": "com.expresscne.parcelconfig.data.model.UserAndPermission.DBPermissionObject",
                "create": true,
                "delete": true,
                "modify": true,
                "pageCode": "sNotifyListView",
                "read": true
            },
            {
                "@class": "com.expresscne.parcelconfig.data.model.UserAndPermission.DBPermissionObject",
                "create": true,
                "delete": true,
                "modify": true,
                "pageCode": "oOrderSearch",
                "read": true
            }
        ]
    ],
    "userName": "AB1234"
}

**Comment by mrniko** [comment]
oh, I think i got the cause. Tomorrow I'll try to fix it.

**Comment by Joycai** [comment]
oh！thx！i am waitting for that！

**Comment by mrniko** [comment]
Fixed. Please check too
