### ISSUE TITLE
RedissonList add LTRIM Command

### ISSUE THREAD

**Issue by lefay1982** [mrniko/redisson#364]
Can you add the method in RList?

**Comment by lefay1982** [comment]
I want to exec RedisCommands.LTRIM directly, but in Redisson class can not get CommandExecutor commandExecutor, it is private;

**Comment by lefay1982** [comment]
The Wiki about "Low level Redis client" in current Redisson how to do?

**Comment by mrniko** [comment]
I think your issue related to this task https://github.com/mrniko/redisson/issues/60. Because it's more convenient to use TRIM via List.subList api. For example:
```java
RList list = redisson.getList("list");
list.subList(20, 1000).clear(); // invokes LTRIM list 20 1000
```

**Comment by mrniko** [comment]
> The Wiki about "Low level Redis client" in current Redisson how to do? 

I didn't get you. Do you mean that code example from Wiki page is not helpful?

**Comment by lefay1982** [comment]
Yes, the Wiki page's code is changed in current Redisson.

**Comment by lefay1982** [comment]
```java
RList list = redisson.getList("list");
list.subList(20, 1000).clear(); // invokes LTRIM list 20 1000
```
the RList run  LRANGE and DEL_SINGLE two commands, and transfer subList data to client. 

I want a method to do
```java
RList list = redisson.getList("list");
list.trim(1000, -1); // invokes LTRIM list 1000 -1 (del 0 ~ 1000 data)
```
this is run one commands, and no data transfer.

**Comment by lefay1982** [comment]
If not have the trim method.
I can invoke getCommandExecutor() to execute LTRIM command, so the RList can add getCommandExecutor() to get the CommandExecutor to execute the LTRIM directly.

**Comment by lefay1982** [comment]
I use lua script solved this problem.

**Comment by mrniko** [comment]
This task will be implemented in #60

**Comment by mrniko** [comment]
@lefay1982 I have implemented `list.subList(20, 1000).clear();` as you requested. Please use it.

**Comment by lefay1982** [comment]
I use lua script solved this problem.
```java
	public boolean RListLTRIM(String key, int start, int stop) {
		String res = getClient().getScript().eval(Mode.READ_WRITE,
				"return redis.call('ltrim', KEYS[1], ARGV[1], ARGV[2]);",
				ReturnType.STATUS, Arrays.toList((Object) key), start, stop);
		return boolConvertor.convert(res);
	}
```

**Comment by mrniko** [comment]
@lefay1982 OK, as you like.

**Comment by mrniko** [comment]
Add `RList.trim` command

**Comment by mrniko** [comment]
@lefay1982 done! use `RList.trim` command

**Comment by lefay1982** [comment]
OK, thanks.
