### ISSUE TITLE
A RMap error in 2.2.5

### ISSUE THREAD

**Issue by SaroLain** [mrniko/redisson#370]
Config config = new Config();
        config.setCodec(StringCodec.INSTANCE);
        config.useSentinelServers()
                .setMasterName("mymaster")
                .setDatabase(1)
                .setMasterConnectionPoolSize(200)
                .setSlaveConnectionPoolSize(200)
                .setTimeout(6000)
                .addSentinelAddress("192.168.1.200:26379");
        RedissonClient redisson = Redisson.create(config);

        RMap<String, String> rmap = redisson.getMap("TestRMap01");
        rmap.delete();
        rmap.put("A", "1");
        rmap.put("B", "1");

        System.out.println("************** *****************");
        System.out.println("A:" + rmap.get("A"));
        System.out.println("B:" + rmap.get("B"));

        System.out.println("************** *****************");
        Iterator<Map.Entry<String, String>> iterator = rmap.entrySet().iterator();
        while (iterator.hasNext()) {
            Map.Entry<String, String> next = iterator.next();
            System.out.println(next.getKey() + ":" + next.getValue());
        }

        redisson.shutdown();

these codes work right in 2.2.4,but  in 2.2.5 will throw Exception:

Exception in thread "main" io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1177)
	at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1120)
	at io.netty.buffer.AbstractByteBuf.getByte(AbstractByteBuf.java:337)
	at io.netty.buffer.ByteBufUtil.hashCode(ByteBufUtil.java:188)
	at io.netty.buffer.AbstractByteBuf.hashCode(AbstractByteBuf.java:1077)
	at java.util.HashMap.hash(HashMap.java:338)
	at java.util.HashMap.put(HashMap.java:611)
	at org.redisson.RedissonMapIterator.convert(RedissonMapIterator.java:66)
	at org.redisson.RedissonMapIterator.hasNext(RedissonMapIterator.java:53)

**Comment by mrniko** [comment]
Fixed

**Comment by tepsl** [comment]
The same error as of 2.2.6.
Not fixed yet.

**Comment by mrniko** [comment]
@tepsl Please provide your testcase. Because testcase provided works well with 2.2.5 and 2.2.6 version

**Comment by mrniko** [comment]
@SaroLain Can you confirm that it works?

**Comment by tepsl** [comment]
@mrniko My example code provided at https://github.com/mrniko/redisson/issues/258#issuecomment-158093350 fails the second time, that is the condition where trying to enumerate 'map' when 'map' is not empty.
With 2.2.4, it works.

**Comment by mrniko** [comment]
@tepsl There is a little bug with `keyDecoder` in `SimpleSerializationCodec`. Some logic that marks read bytes needed. So `keyDecoder.decoder` method should looks like this:
```java
@Override
public Object decode(ByteBuf buf, State state) throws IOException {
      String str = buf.toString(CharsetUtil.UTF_8);
      buf.readerIndex(buf.readableBytes());
      return str;
}
```

**Comment by tepsl** [comment]
Now it works.
Thanks.
