### ISSUE TITLE
Can't init enough connections amount

### ISSUE THREAD

**Issue by elebelesam** [mrniko/redisson#371]
Hi,

I am trying to connect to redis using RedissonClient. When I create the client without any configuration it works. However, whenever I try to pass the configuration as parameter it gives the following error,

" org.redisson.client.RedisConnectionException: Can't init enough connections amount! from /127.0.0.1:6397"

By default it is using the same port and host. But when I try to enter it using the config param it gives me the error.
Following is the code snippet,

Config config = new Config();
String address = "127.0.0.1:6397";
config.useSingleServer().setAddress(address).setConnectionPoolSize(10);

client = Redisson.create(config);

Redis version : 3.0.6
Redisson version: 2.2.4
Jdk 1.8

Any suggestion?

Thanks.

**Comment by mrniko** [comment]
oh! it seems like you have misprint in port number `6397` but default port is `6379`

**Comment by elebelesam** [comment]
Thanks. How silly it was!!
