### ISSUE TITLE
RSet add getAll(SMEMBERS)  method.

### ISSUE THREAD

**Issue by lefay1982** [mrniko/redisson#374]
RedissonSet  has toArray() method to invoke readAllAsync (SMEMBERS) , it is return Arrays.
I want add a method directly return Set<T> or List<T> to local, then I can use these collections in local, don't need to access the redis anymore.

**Comment by lefay1982** [comment]
```jave
    RSet<String> ignoreKeys = r.getSet(someKey);
    Set<String> setIgnore = Arrays.toSet(ignoreKeys.toArray(new String[] {}));
```
it's so ugly.

**Comment by mrniko** [comment]
Done!
