### ISSUE TITLE
How can I use mget/mset in redis cluster?

### ISSUE THREAD

**Issue by uryyyyyyy** [mrniko/redisson#378]
Hi.
I want to use this -> http://redis.io/topics/cluster-spec#multiple-keys-operations
but when cluster mode, `RedissonClient#loadBucketValues` return unsupported error.
how can I use it?

thanks!

**Comment by mrniko** [comment]
Hi!

I pondered your needs and decided to to remove cluster restrictions for such methods. But then any CROSSLOT errors handling is up to you.

**Comment by uryyyyyyy** [comment]
Thanks!

I'm looking forward to new release!
