### ISSUE TITLE
Healthcheck for Redisson

### ISSUE THREAD

**Issue by vivekkothari** [mrniko/redisson#381]
I am using this client in a dropwizard service and I want to add a healthcheck. Jedis has a PING command, here using the RedissonClient I can't issue a ping command. I need to create a instance of RedisClient for the same. I should be able to retrieve instance of RedisClient from RedissonClient, or suggest me a way to perform a healthCheck for the same.

**Comment by mrniko** [comment]
You can use `RedissonClient.getNodesGroup.pingAll()` or invoke `ping` method on each `Node` from `RedissonClient.getNodesGroup.getNodes` list.
