### ISSUE TITLE
An exception when upgrade from 2.2.5 to 2.2.6

### ISSUE THREAD

**Issue by SaroLain** [mrniko/redisson#387]
Caused by: org.redisson.client.RedisException: ERR unknown command 'SELECT'. channel: [id: 0x9d9fb2c3, /192.168.1.112:7378 => /192.168.1.200:26379] command: CommandData [promise=DefaultPromise@36a98b5d(incomplete), command=(SELECT), params=[1], codec=null]

***********************************************
i do "mvn clean" before start tomcat
redis version：Redis-x64-3.0.500

    private RedissonClient createRedissonClient() {
        Config config = new Config();
        config.setCodec(objectCodec);
        config.useSentinelServers()
                .setMasterName(this.masterName)
                .setDatabase(this.database)
                .setMasterConnectionPoolSize(this.masterConnectionPoolSize)
                .setSlaveConnectionPoolSize(this.slaveConnectionPoolSize)
                .setTimeout(this.timeout)
                .addSentinelAddress(sentinelAddress);
        RedissonClient redisson = Redisson.create(config);
        return redisson;
    }

**Comment by mrniko** [comment]
Fixed
