### ISSUE TITLE
RedissonCacheManager use custom Codec and must be more simply

### ISSUE THREAD

**Issue by SaroLain** [mrniko/redisson#388]
build CacheConfig Map is hard and more code，I expect use these config:

    <bean id="redisCacheManager" class="org.redisson.spring.cache.RedissonCacheManager"
          c:_0-ref="redisson"
          c:_1-ref="myCustomCodec"
          c:_2="classpath*:/redissonCacheConfig.json">
    </bean>

**Comment by mrniko** [comment]
Done
