### ISSUE TITLE
Redisson

### ISSUE THREAD

**Issue by soelvar** [mrniko/redisson#394]
Hi mrniko,

since upgrading to 2.2.6 from 2.1.4, suddenly the Rmap only returns 10 elements - although it reports size correctly to 1000. Below is my test scenario - please help! I have attached output log.

Map<String, Object> properties = new HashMap<>();
        properties.put("redis.hostname", "127.0.0.1");
        properties.put("redis.port", "6379");
        properties.put("redis.pool.size", "100");
        properties.put("redis.compression", "false");
        properties.put("redis.localslave", "false");
        properties.put("redis.registration", "true");

        RedissonRepository redissonRepository = RedissonRepository.getInstance(properties);
        RMap rMap = redissonRepository.getMap("123",new JsonJacksonCodec());

        for (int i = 0; i < 1000; i++) {
            rMap.put(i,i);
        }

        int counter = 0;
        for (Object key : rMap.keySet()) {
            System.out.println("key = " + key);
            counter++;
            System.out.println(counter);
        }

[redisson.txt](https://github.com/mrniko/redisson/files/116908/redisson.txt)

**Comment by mrniko** [comment]
Fixed

**Comment by soelvar** [comment]
Thanks a lot for the quick reponse:0)

**Comment by mrniko** [comment]
@soelvar All for you! :)

**Comment by soelvar** [comment]
Hi again mrniko,

Firstly again thanks for your fix earlier, it seems to have addressed the issue - however it also seems we are experiencing a different maybe related issue. I haven't created a test case for it yet, but when I shutdown the system, it seems like Redisson keep sending the same requests repeatedly  in the background - please see below.

1455018512.248507 [0 10.118.10.150:55167] "HGET" "DTRR|203921" "\x03-2253_7661723\xb0"
1455018512.248529 [0 10.118.10.143:58317] "HGET" "DTRR|2000286" "\x03-2834_14306713\xb3"
1455018512.248578 [0 10.118.10.143:58255] "HGET" "LTTRR|200045_200073" "\x03-210_7664061\xb5"
1455018512.248672 [0 10.118.10.142:40363] "HGET" "LTTRR|200069_200058" "\x03-2469_7602854\xb2"
1455018512.248722 [0 10.118.10.143:58246] "HGET" "LTTRR|2000439_2000437" "\x03-2172_13793941\xb3"
1455018512.248959 [0 10.118.10.150:49338] "HGET" "LTTRR|200069_200058" "\x03-2319_7511276\xb2"
1455018512.248968 [0 10.118.10.150:49264] "HGET" "DTRR|206730" "\x03-2184_14249613\xb5"
1455018512.248974 [0 10.118.10.148:39705] "HGET" "LTTRR|200045_200073" "\x03-2883_7664063\xb3"
1455018512.248981 [0 10.118.10.149:54248] "HGET" "LTTRR|200045_200073" "\x03-2686_7664150\xb3"
1455018512.249009 [0 10.118.10.150:54539] "HGET" "LTTRR|200069_200058" "\x03-2469_7602854\xb2"
1455018512.249019 [0 10.118.10.148:41129] "HGET" "LTTRR|200045_200073" "\x03-2860_14249541\xb8"
1455018512.249062 [0 10.118.10.143:58319] "HSCAN" "DTRR|2000286" "0"
1455018512.249086 [0 10.118.10.150:49209] "HGET" "DTRR|203921" "\x03-2692_7635180\xb2"
1455018512.249093 [0 10.118.10.143:58225] "HGET" "LTTRR|200045_200073" "\x03-2381_13304282\xb2"
1455018512.249127 [0 10.118.10.142:42414] "HGET" "LTTRR|200069_200058" "\x03-2190_2232273\xb3"
1455018512.249224 [0 10.118.10.143:58250] "HGET" "LTTRR|2000439_2000437" "\x03-2204_13793941\xb4"
1455018512.249494 [0 10.118.10.150:49259] "HGET" "LTTRR|200069_200058" "\x03-2293_4032475\xb1"
1455018512.249509 [0 10.118.10.148:39767] "HGET" "LTTRR|200045_200073" "\x03-2265_7646726\xb5"
1455018512.249541 [0 10.118.10.148:39696] "HGET" "LTTRR|200045_200073" "\x03-2941_8865726\xb3"
1455018512.249554 [0 10.118.10.150:49260] "HSCAN" "DTRR|206730" "0"
1455018512.249591 [0 10.118.10.149:54260] "HGET" "LTTRR|200045_200073" "\x03-2860_14249541\xb8"
1455018512.249616 [0 10.118.10.150:49363] "HGET" "LTTRR|200069_200058" "\x03-248_96611\xb6"
1455018512.249641 [0 10.118.10.143:58254] "HGET" "LTTRR|200045_200073" "\x03-2304_7646726\xb3"
1455018512.249675 [0 10.118.10.142:40374] "HGET" "LTTRR|200069_200058" "\x03-2417_7514665\xb4"
1455018512.249690 [0 10.118.10.143:59627] "HSCAN" "LTTRR|2000439_2000437" "0"
1455018512.249848 [0 10.118.10.150:49198] "HSCAN" "DTRR|203921" "0"
1455018512.249864 [0 10.118.10.143:58293] "HGET" "DTRR|2000286" "\x03-2552_7639610\xb8"
1455018512.249950 [0 10.118.10.150:49258] "HGET" "LTTRR|200069_200058" "\x03-2319_7511276\xb2"
1455018512.249970 [0 10.118.10.148:39697] "HGET" "LTTRR|200045_200073" "\x03-2860_14249541\xb8"
1455018512.249984 [0 10.118.10.148:40148] "HGET" "LTTRR|200045_200073" "\x03-2623_14249647\xb3"
1455018512.250047 [0 10.118.10.149:54250] "HGET" "LTTRR|200045_200073" "\x03-210_7664061\xb5"
1455018512.250120 [0 10.118.10.150:49357] "HGET" "LTTRR|200069_200058" "\x03-2308_7511260\xb9"
1455018512.250161 [0 10.118.10.150:49261] "HGET" "DTRR|206730" "\x03-2355_14306766\xb2"
1455018512.250213 [0 10.118.10.142:40333] "HGET" "LTTRR|200069_200058" "\x03-2319_7511276\xb2"
1455018512.250230 [0 10.118.10.143:59652] "HGET" "LTTRR|2000439_2000437" "\x03-2204_13793941\xb4"
1455018512.250242 [0 10.118.10.143:59653] "HGET" "LTTRR|200045_200073" "\x03-231_7646709\xb9"
1455018512.250282 [0 10.118.10.143:58288] "HGET" "DTRR|2000286" "\x03-2393_14272535\xb9"
1455018512.250376 [0 10.118.10.148:39701] "HGET" "LTTRR|200045_200073" "\x03-210_7664061\xb5"
1455018512.250406 [0 10.118.10.148:40833] "HGET" "LTTRR|200045_200073" "\x03-2304_7646726\xb3"
1455018512.250422 [0 10.118.10.150:54554] "HGET" "LTTRR|200069_200058" "\x03-2415_4039551\xb4"
1455018512.250529 [0 10.118.10.149:54249] "HGET" "LTTRR|200045_200073" "\x03-2752_14249707\xb5"
1455018512.250629 [0 10.118.10.150:49201] "HGET" "DTRR|203921" "\x03-2253_7661723\xb0"
1455018512.250704 [0 10.118.10.150:54539] "HGET" "DTRR|206730" "\x03-2184_14249613\xb5"
1455018512.250734 [0 10.118.10.142:40370] "HGET" "LTTRR|200069_200058" "\x03-212_14365758\xb3"
1455018512.250759 [0 10.118.10.143:58246] "HGET" "LTTRR|2000439_2000437" "\x03-2755_13916048\xb9"
1455018512.250773 [0 10.118.10.143:58313] "HGET" "DTRR|2000286" "\x03-2850_14397572\xb2"
1455018512.250796 [0 10.118.10.150:54559] "HGET" "LTTRR|200069_200058" "\x03-2417_7514665\xb4"
1455018512.250809 [0 10.118.10.143:58255] "HGET" "LTTRR|200045_200073" "\x03-2265_7646726\xb5"
1455018512.250856 [0 10.118.10.148:39692] "HGET" "LTTRR|200045_200073" "\x03-2236_7664062\xb0"
1455018512.250880 [0 10.118.10.148:39795] "HGET" "LTTRR|200045_200073" "\x03-2310_14249537\xb7"
1455018512.250907 [0 10.118.10.150:49264] "HGET" "LTTRR|200069_200058" "\x03-2131_4850428\xb2"
1455018512.250939 [0 10.118.10.149:54252] "HGET" "LTTRR|200045_200073" "\x03-2883_7664063\xb3"
1455018512.251071 [0 10.118.10.150:49199] "HGET" "DTRR|203921" "\x03-2692_7635180\xb2"
1455018512.251155 [0 10.118.10.150:49259] "HGET" "DTRR|206730" "\x03-2138_12866269\xb3"
1455018512.251202 [0 10.118.10.143:58317] "HGET" "DTRR|2000286" "\x03-2721_7639582\xb4"
1455018512.251241 [0 10.118.10.142:42435] "HGET" "LTTRR|200069_200058" "\x03-277_96686\xb4"
1455018512.251265 [0 10.118.10.150:49341] "HGET" "LTTRR|200069_200058" "\x03-2293_4032475\xb1"
1455018512.251273 [0 10.118.10.148:39705] "HGET" "LTTRR|200045_200073" "\x03-2789_7664063\xb2"
1455018512.251301 [0 10.118.10.148:40832] "HGET" "LTTRR|200045_200073" "\x03-2381_13304282\xb2"
1455018512.251378 [0 10.118.10.143:58250] "HGET" "LTTRR|200045_200073" "\x03-2310_14249537\xb7"
1455018512.251401 [0 10.118.10.149:54248] "HGET" "LTTRR|200045_200073" "\x03-2789_7664063\xb2"
1455018512.251438 [0 10.118.10.143:58225] "HGET" "LTTRR|2000439_2000437" "\x03-2172_13793941\xb3"
1455018512.251570 [0 10.118.10.150:49258] "HSCAN" "DTRR|206730" "0"
1455018512.251598 [0 10.118.10.150:49260] "HGET" "LTTRR|200069_200058" "\x03-212_14365758\xb3"
1455018512.251639 [0 10.118.10.143:58319] "HGET" "DTRR|2000286" "\x03-2834_14306713\xb3"
1455018512.251665 [0 10.118.10.150:49210] "HSCAN" "DTRR|203921" "0"
1455018512.251678 [0 10.118.10.142:40363] "HGET" "LTTRR|200069_200058" "\x03-2433_7511252\xb2"
1455018512.251685 [0 10.118.10.148:39696] "HGET" "LTTRR|200045_200073" "\x03-2265_7646726\xb5"
1455018512.251763 [0 10.118.10.148:41129] "HGET" "LTTRR|200045_200073" "\x03-231_7646709\xb9"
1455018512.251803 [0 10.118.10.150:49345] "HGET" "LTTRR|200069_200058" "\x03-2190_2232273\xb3"
1455018512.251876 [0 10.118.10.143:58254] "HGET" "LTTRR|200045_200073" "\x03-2860_14249541\xb8"
1455018512.251947 [0 10.118.10.143:59627] "HSCAN" "LTTRR|2000439_2000437" "0"
1455018512.251994 [0 10.118.10.149:54260] "HGET" "LTTRR|200045_200073" "\x03-2236_7664062\xb0"
1455018512.252036 [0 10.118.10.143:58293] "HGET" "DTRR|2000286" "\x03-2196_7639584\xb1"
1455018512.252124 [0 10.118.10.150:49261] "HGET" "DTRR|206730" "\x03-2355_14306766\xb2"
1455018512.252133 [0 10.118.10.142:42414] "HGET" "LTTRR|200069_200058" "\x03-2415_4039551\xb4"
1455018512.252141 [0 10.118.10.148:39697] "HGET" "LTTRR|200045_200073" "\x03-231_7646709\xb9"
1455018512.252179 [0 10.118.10.150:54554] "HGET" "LTTRR|200069_200058" "\x03-2433_7511252\xb2"
1455018512.252224 [0 10.118.10.148:39767] "HSCAN" "LTTRR|200045_200073" "0"
1455018512.252259 [0 10.118.10.150:55167] "HGET" "DTRR|203921" "\x03-2253_7661723\xb0"
1455018512.252294 [0 10.118.10.150:49338] "HGET" "LTTRR|200069_200058" "\x03-2469_7602854\xb2"
1455018512.252342 [0 10.118.10.143:59653] "HGET" "LTTRR|200045_200073" "\x03-2752_14249707\xb5"
1455018512.252405 [0 10.118.10.149:54250] "HGET" "LTTRR|200045_200073" "\x03-2941_8865726\xb3"
1455018512.252436 [0 10.118.10.143:59652] "HGET" "LTTRR|2000439_2000437" "\x03-2755_13916048\xb9"
1455018512.252467 [0 10.118.10.143:58288] "HGET" "DTRR|2000286" "\x03-2725_7639583\xb1"
1455018512.252555 [0 10.118.10.142:40374] "HSCAN" "LTTRR|200069_200058" "0"

**Comment by mrniko** [comment]
@soelvar I have fixed it there https://github.com/mrniko/redisson/issues/402

**Comment by mrniko** [comment]
@soelvar Sorry, I hurried and didn't try it before the fix. Can't reproduce it with such test:
```java
    public void testCommandsSendDuringShutdown() throws InterruptedException {
        final RedissonClient r = Redisson.create();
        Thread t = new Thread() {
            public void run() {
                for (int i = 0; i < 10000000; i++) {
                    r.getAtomicLong("test").incrementAndGet();
                    System.out.println("i" + i);
                }
            };
        };
        t.start();
        t.join(1000);

        r.shutdown();
        t.join();
    }
```
Redisson always known about shutdown moment and throws `java.lang.IllegalStateException: Redisson is shutdown`

**Comment by soelvar** [comment]
@mrniko thanks for your reply - we have progressed a little in our investigation, and it seems that a query we were using to iterate a map in the past would have pre-fetched some element, where as in the new version it us only getting one at a time. Is there any way to pre-fetched - a method that use hgetall?

I am not sure why it keeps making the same requests though...I guess either all the queries queue up or the same request is retried repeatedly - I will let you know if I find out.

**Comment by mrniko** [comment]
> Is there any way to pre-fetched - a method that use hgetall?

There are several methods for it: `RMap.readAllKeySet`, `RMap.readAllValues` and `RMap.readAllEntrySet`.

**Comment by soelvar** [comment]
Hi Nikita,

Thanks - I found it this morning:0) I think the trouble we were facing
second round was the new library - the way we did previously sent from
fetching all to lazy, but with this method, everything looks good. Thanks
again for all your help!

Cheers,
Jesper

**Comment by mrniko** [comment]
@soelvar You're welcome. I may join to Redisson chat https://gitter.im/mrniko/redisson for further discussion of any problems
