### ISSUE TITLE
Lots of string allocations by exception

### ISSUE THREAD

**Issue by musachy** [mrniko/redisson#397]
Doing some load testing I found that this line:

 exceptionRef.set(new RedisTimeoutException("Command execution timeout for command: " + command + " with params: " + Arrays.toString(params)));
       
in CommandExecutorService can do a lot of string allocation and generate garbage. Could this exception be improved so the array is only built when necessary?

thanks

**Comment by mrniko** [comment]
Which version do you use? it was fixed some versions ago.

**Comment by musachy** [comment]
Ah my bad, I will update to the latest version. Thanks for this awesome library.
