### ISSUE TITLE
an exception of RedissonSpringCacheManager 

### ISSUE THREAD

**Issue by SaroLain** [mrniko/redisson#405]
spring config:

    <bean id="cacheCodec" class="org.redisson.codec.JsonJacksonCodec"/>
    <bean id="redisCacheManager" class="org.redisson.spring.cache.RedissonSpringCacheManager"
          c:_0-ref="redisson"
          c:_1="classpath:config/redissonCacheConfig.json"
          c:_2-ref="cacheCodec">
    </bean>

> org.redisson.client.RedisException: ERR Error running script (call to f_286dd696309f4ab2005d9df55e2410a1170fe3b3): @user_script:1: @user_script: 1: -READONLY You can't write against a read only slave.   . channel: [id: 0x1fa180db, /192.168.1.112:9026 => /192.168.1.200:6380] command: CommandData [promise=DefaultPromise@2ef37b25(incomplete), command=(EVAL), params=[local value = redis.call('hget', KEYS[1], ARGV[2]); if value == false then return nil; end; local t, val = struct.unpack('dLc0', value); local expireDate = 92233720368547758; local expireDateScore = redis.call('zscore', KEYS[2], ARGV[2]); if expireDateScore ~= false then expireDate = tonumber(expireDateScore) end; if t ~= 0 then local expireIdle = redis.call('zscore', KEYS[3], ARGV[2]); if expireIdle ~= false then if tonumber(expireIdle) > tonumber(ARGV[1]) then local value = struct.pack('dLc0', t, string.len(val), val); redis.call('hset', KEYS[1], ARGV[2], value); redis.call('zadd', KEYS[3], t + tonumber(ARGV[1]), ARGV[2]); end; expireDate = math.min(expireDate, tonumber(expireIdle)) end; end; if expireDate <= tonumber(ARGV[1]) then return nil; end; return val; , 3, C:UserProfile, redisson__timeout__set__{C:UserProfile}, redisson__idle__set__{C:UserProfile}, 1455593900905, 206aa20c5a737744edb1f8e0e05084ae88], codec=org.redisson.codec.JsonJacksonCodec@6bf1e09f]
> 	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:190)
> 	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:105)
> 	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:376)
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293)
> 	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293)
> 	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293)
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:840)
> 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
> 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
> 	at java.lang.Thread.run(Thread.java:745)
>

**Comment by SaroLain** [comment]
master:6379 ; slave:6380,6381
```
private RedissonClient createRedissonClient() {
        Config config = new Config();
        config.setCodec(objectCodec);
        config.useSentinelServers()
                .setMasterName(this.masterName)
                .setDatabase(this.database)
                .setMasterConnectionPoolSize(this.masterConnectionPoolSize)
                .setSlaveConnectionPoolSize(this.slaveConnectionPoolSize)
                .setTimeout(this.timeout)
                .addSentinelAddress(sentinelAddress);
        RedissonClient redisson = Redisson.create(config);
        return redisson;
    }
```

**Comment by mrniko** [comment]
Fixed
