### ISSUE TITLE
Batch/Pipeline operations support

### ISSUE THREAD

**Issue by mrniko** [mrniko/redisson#42]
Operates with `async` methods only. Code example:
```java
RBatch batch = redisson.createBatch();

RMap<Integer, Integer> map = redisson.getMap("map");
map.fastPutAsync(1, 2);
map.putAsync(2, 3);
map.fastPutAsync(3, 4);

List<Future<?>> futures = batch.execute();
// or
Future<List<Future<?>>> futures = batch.executeAsync();

```

**Comment by enghch** [comment]
Shouldn't it be more like this:

RBatch batch = redisson.createBatch();

RMap<Integer, Integer> map = batch.getMap("map");
Future<?> future1 = map.fastPutAsync(1, 2);
Future<?> future2 = map.putAsync(2, 3);
Future<?> future3 = map.fastPutAsync(3, 4);

List<Future<?>> futures = batch.execute();
// or
Future<List<Future<?>>> futures = batch.executeAsync();
