### ISSUE TITLE
Missing entries in RMapAsync using single redis server and multiple web servers in servlet enviornment

### ISSUE THREAD

**Issue by giantninja** [mrniko/redisson#425]
I am testing out using RMapAsync to store connected users to our web service in a servlet environment with two or more web servers and one redis server.  When a user creates or removes a session, I'm adding/removing to the RMapAsync like so:

```java
public void addUser(User user) {
    if (user != null) {
        try {
            RMapAsync<Long, User> map = redisson.getMap("users");
            map.fastPutAsync((user.getLongKey()), user);
        } catch (Exception e) {
            _logger.warn("Exception caught in addUser: {}", e.getMessage());
        }
    }
}
```

and similarly, when a session is removed:
```java
public void removeUser(User user) {
    if (user != null) {
        try {
            RMapAsync<Long, User> map = redisson.getMap("users");
            map.fastRemoveAsync(user.getLongKey());
        } catch (Exception e) {
            _logger.warn("Exception caught in removeUser: {}", e.getMessage());
        }
    }
}
```

I am seeing that there are a few hundred missing with a total user count of 3K or so.  Is this possibly because the same redis key/hashmap is being altered simultaneously from more than one server?  Is it best to get the map and edit it like I'm doing here? or would it be better to have one class member instance of the map in my class and just add remove in the relevant methods (so I'm not continuously calling get map for every add/remove)?  What's the best practice for a setup like this if this isn't a bug, but a misuse of the RMapAsync?  (awesome project btw)

**Comment by mrniko** [comment]
First of all, you should add exception handling to Future object instead of simple try ... catch.

>  Is this possibly because the same redis key/hashmap is being altered simultaneously from more than one server? 

No, redis structures are thread-safe due to operation executed in single thread.

> would it be better to have one class member instance of the map in my class and just add remove in the relevant methods 

It doesn't matter how do you get RMap instance.

> few hundred missing with a total user count of 3K or so

Could you clarify it, please. You can add listener to Future object, like:

```java
Future<Void> f = fastPutAsync((user.getLongKey()), user);
f.addListener(new FutureListener() {
   public void operationComplete(Future f) {
         if (f.isSuccess()) {
            // log user added...
         }
   } 
});

f.addListener(new Future<Void>() {
})
```

and compare it with redis state.

**Comment by giantninja** [comment]
I updated my code to this, and they are still off from what's expected, but not seeing any of the failure warnings from the future listener in my logs.

```java
public void addUser(User user) {
    if (user != null) {
        try {
            RMapAsync<Long, User> map = redisson.getMap("users");
            Future<Boolean> f = map.fastPutAsync((user.getLongKey()), user);
            f.addListener((Future<Boolean> future) -> {
                if (future.isSuccess()) {
                    _logger.debug("addUser fastPutAsync success: {}", user);
                } else {
                    try {
                        throw future.cause();
                    } catch (Throwable throwable) {
                        _logger.warn("addUser fastPutAsync failed: {}\n{}", user, throwable.getMessage());
                    }
                }
            });
        } catch (Exception e) {
            _logger.warn("Exception caught in addUser: {}", e.getMessage());
        }
    } else {
        _logger.warn("null user passed to addUser:");
    }
}
```

not sure where the discrepancies in the user count's are coming from

**Comment by jackygurui** [comment]
Just out of interests, how is the total user count worked out? Are you comparing this with sessions counts? As far as I know, it is possible to have multiple sessions created by the same user at the same time. i.e. the same user logged in from different browser/devices. 

Since the user's long key (I guess it is the user identifier like UID or some sort), if your code is removing the user from the map as soon as the first session expires. It would remove him/her from the list even when other sessions are still alive. 

Similarly, when a user logged in via a second session, it would not be added to the users map again since the entry already exists.

Like you mentioned:
> When a user creates or removes a session, I'm adding/removing to the RMapAsync like so:

I think this is where the problem is.

**Comment by jackygurui** [comment]
My suggestion would be tracking the total sessions for each user and only remove the user from the users map when ALL of his/her sessions are expired.

**Comment by giantninja** [comment]
> Just out of interests, how is the total user count worked out? Are you comparing this with sessions counts? As far as I know, it is possible to have multiple sessions created by the same user at the same time. i.e. the same user logged in from different browser/devices.

I am using CometD as a push service, and it has a distributed class "Seti" that keeps track of userIds (and which node they belong to), and that count is always accurate (well you know, should always be accurate)

>  when a user logged in via a second session, it would not be added to the users map again since the entry already exists.
> 
> Like you mentioned:
> 
> When a user creates or removes a session, I'm adding/removing to the RMapAsync like so:
> I think this is where the problem is.

I think you are right, thank you!.  I'm putting together a test to make sure, but I was able to recreate the miss match of user counts by opening up another browser tab and then closing it.  I am able to determine if the session removed was the last session for a user, or an extra session, so I will only remove from the RMap if it was the last session for a user.  I'll report back once I've verified (or disproved that)

**Comment by jackygurui** [comment]
Glad to be of help.
Please let me know either way, thanks.

**Comment by giantninja** [comment]
So that was the problem indeed.  Thanks for the quick replies and help on this one.  Didn't even think about multiple sessions (sometimes you gotta take a step back and see the whole picture).

Thanks again, and awesome project, love it.  Keep up the great work!

**Comment by jackygurui** [comment]
Glad it worked for you.

**Comment by giantninja** [comment]
Sweet.  Looks pretty cool.  I will have to play around with that one weekend.

**Comment by jackygurui** [comment]
Good luck

**Comment by mrniko** [comment]
@jackygurui Thanks for you support!
