### ISSUE TITLE
Read Write lock cannot be correctly unlocked 

### ISSUE THREAD

**Issue by milesandnick** [mrniko/redisson#436]
in ReadLock and WriteLock,  the unlock method use thread id to determine whether it is owned by this thread. it works fine for a single machine.
However, when it is used in a distributed processing framework such as MapReduce, the Read and Write lock cannot be correctly unlocked.
I browse the source codes and find that the UUID is generated in the lock, I think it is better to use UUID as lock id  istead of thread id or provides a way to let users to set a unque id.

**Comment by mrniko** [comment]
ReadLock and WriteLock should be tied to thread which invoked `lock` method. Same thread should be used for `unlock` method, this is a rule for all locks in java.

**Comment by milesandnick** [comment]
I cannot fully understarnd your comment, does it mean that redission cannot be used across different JVMs or different machines.
I used redission in MapReduce framework and each mapper executes codes like this
redission.getReadWriteLock("lock").readLock().lock();
....
redission.getReadWriteLock("lock").readLock().unlock();

however I often got IllegalMonitorStateException  which tells me that the lock is not owend by this thread.
I make sure that there is no error in my codes and the unlock and lock method can be executed in pairs.

I have modified the codes of redission codes and added field in RedissionLock, RedissionWriteLock and RedissionLock to store my own generated unque id. It works fine temporarily, but I think it is better for redission to provides a better mechnism.

I also have tried to modify source codes of JDK Thread class to set my own thread id, but I gave up as there are native methods in the source codes.
I think it would be an improvent for redission to support locks that can work well across different machines.

**Comment by mrniko** [comment]
ReadWriteLock does work in distributed env. But if you locked any lock in one thread you should use same thread for unlocking. This is the rule of thumb.

**Comment by milesandnick** [comment]
I wonder whether you have test redission lock in a distributed environment.
In a distributed environment, two threads in different machines may have the same thread Id. In this case, how does Redission check which thread is holding this lock.
If Redission does work in distributed environment, can you tell me why the codes does not work in my case?

I used redission in MapReduce framework and each mapper executes codes like this
redission.getReadWriteLock("lock").readLock().lock();
....
redission.getReadWriteLock("lock").readLock().unlock();

however I often got IllegalMonitorStateException which tells me that the lock is not owend by this thread.
I make sure that there is no error in my codes and the unlock and lock method can be executed in pairs.

I have modified the codes of redission codes and added field in RedissionLock, RedissionWriteLock and RedissionLock to store my own generated unque id. It works fine.

**Comment by mrniko** [comment]
Lock contains info about RedissonClient (UUID) and thread in format uuid:threadId

**Comment by mrniko** [comment]
Redisson Lock objects is proven by usage in cluster by many Redisson customers. It's the first object which they used in Redisson.

**Comment by mrniko** [comment]
It's possible that you using another RedissonClient with same thread for unlock. Then you will get same issue.

**Comment by jackygurui** [comment]
> I used redission in MapReduce framework and each mapper executes codes like this
redission.getReadWriteLock("lock").readLock().lock();
....
redission.getReadWriteLock("lock").readLock().unlock();


@milesandnick Just wondering how many Redisson instances to you have in total in the program? Am I right to assume you have one Redisson instance per mapper?

**Comment by milesandnick** [comment]
@jackygurui  Yes, I have one Redission instance per mapper. Does this  cause this kind of problems?

**Comment by milesandnick** [comment]
@mrniko  I use only one RedissonClient per mapper, so there would not be another client with the same thread.

**Comment by jackygurui** [comment]
@milesandnick Are you using the same redisson instance to do the unlock?

**Comment by mrniko** [comment]
@milesandnick Also I think it's easy to see the cause of problem if you add some logging thread and UUID info to lock and unlock methods

**Comment by mrniko** [comment]
@milesandnick have you resolved it?

**Comment by milesandnick** [comment]
I guess that  may be the lock exceeds the expire time and be unlocked automically.
@mrniko

**Comment by mrniko** [comment]
It could be so
