### ISSUE TITLE
Optimization on interactions between Redis and Redission

### ISSUE THREAD

**Issue by milesandnick** [mrniko/redisson#444]
I have seen the source codes and found that many codes use java string join parameter.
I think it is not inefficient.
May be use StringBuffer of use static string values, so that the interactions between Redis and Redission can be more efficient.

**Comment by mrniko** [comment]
> I have seen the source codes and found that many codes use java string join parameter.

All such strings will be optimized in compiler time to String constant if there was no any other objects in concatenation besides strings
