### ISSUE TITLE
Is Redisson a good candidate for session manager?

### ISSUE THREAD

**Issue by ziadloo** [mrniko/redisson#451]
I know my question is not an issue but I couldn't find a better way to get an answer, sorry!

Would you recommend Redisson as a session manager (as in HttpSession)?

Spring Session comes with a clustered version using Redis but it does not support locks (AFAIK) and personally I find that useless. Then I found this project and it sounds suitable but there's so much to consider and trying to get advise from the community I thought this is the best place to ask.

**Comment by mrniko** [comment]
Hi!

Session manager is not implemented yet. You can use Map object with TTL (RMapCache object) for this. Also you can help with Redisson integration to Spring Session project. Like made [here](https://github.com/spring-projects/spring-session/tree/2592905b41e76ca6e5444d64a91f867d847f7fea/spring-session/src/main/java/org/springframework/session/hazelcast).

**Comment by ziadloo** [comment]
Thanks, perhaps it's better to close this issue and pursue this from the other new issue.
