### ISSUE TITLE
Long latency issue while call Redis.

### ISSUE THREAD

**Issue by zhxjouc** [mrniko/redisson#455]
I use Redisson 2.2.10 to implement distributed lock in my project. And then I run load test for this distributed lock using SINGLE redis mode. But I found there are many long latency APIs and it's wired that almost all the long latency APIs are a little greater than 1000ms. The average latency and 99 percent latecy is about 15ms and 30ms respectively. And then I used `jstack` to get the call stack and found most of the threads are WAITING at the same place just as the following

    "Processor-35" prio=10 tid=0x00007f61900e3800 nid=0x2614 in Object.wait() [0x00007f61027e5000]
     java.lang.Thread.State: WAITING (on object monitor)
           at java.lang.Object.wait(Native Method)
           at java.lang.Object.wait(Object.java:503)
           at io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly(DefaultPromise.java:286)
           - locked <0x0000000600aa3e50> (a io.netty.util.concurrent.DefaultPromise)
           at io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly(DefaultPromise.java:32)
           at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:84)
           at org.redisson.RedissonObject.get(RedissonObject.java:49)
           at org.redisson.RedissonLock.tryAcquire(RedissonLock.java:139)
           at org.redisson.RedissonLock.tryLock(RedissonLock.java:225)
           at com.mytest.lock.impl.redis.BaseRedisLockClientImpl.tryLock(BaseRedisLockClientImpl.java:72)

Meanwhile, during the test, I dumped the network packages using `tcpdump` and found that it took about 1000ms before the first package was sent to Redis. And in Redis server, I didn't find any slow query whose latency is more than 10ms. So I think, for the long latency API, most of the time might be cost in the project not the network. So can you help me to have a check or give me some suggestion about this issue?  Many thanks.

**Comment by mrniko** [comment]
Can you try it with `master` branch version? I have tuned perf today

**Comment by zhxjouc** [comment]
I sync the latest the master branch(2.2.11-SNAPSHOT) and build it by myself. But it might have no improvement for the long latency issue. Is this issue caused by netty or is it possible that we have missed some configurations about netty?

**Comment by mrniko** [comment]
> almost all the long latency APIs are a little greater than 1000ms. The average latency and 99 percent latecy is about 15ms and 30ms respectively

I didn't get you. You wrote latency is 1000ms but at the same moment tells about 15ms and 30ms.

**Comment by zhxjouc** [comment]
I'm sorry about the confusion. I mean the average latency of all the calls is about 15ms. But there are also some calls whose latency is more than 1000ms. The percentage of these long latency calls is about 0.3%. And these long latency calls might not be caused by network or Redis server according to our research.

**Comment by mrniko** [comment]
Could you provide your test case?

**Comment by zhxjouc** [comment]
The project is very heavy and has lots of components. So I don't know how to give you the test case more significant. But here is how we implement our lock service.
1. create redission client using given config
2. implement lockClient using redission client
3. implement lockService using the lockClient
4. create a simple API which will lock and unlock the random String using the lock service
    The random string is uuid, so they should be unique
5. startup the application and call that API using jmeter

The following are the some sample codes..
Build redission client


    public RedissonClient buildSingleRedissonClient() {
        Config config = new Config();
		config.useSingleServer().setAddress("redis_ip").setPassword("####").
		setConnectionMinimumIdleSize(10)
                .setConnectionPoolSize(40).setIdleConnectionTimeout(3000000)
                .setConnectTimeout(1000).setTimeout(1000);
        return Redisson.create(config);
       }

Lock client

    public class BaseRedisLockClientImpl implements LockClient {
        RedissonClient redisson;    
        public BaseRedisLockClientImpl(RedissonClient redisson) {
            this.redisson = redisson;
        }
    @Override
    public void lock(String value) {
        redisson.getLock(value).lock();
    }
    @Override
    public void lock(String value, long leaseMillis) {
        redisson.getLock(value).lock(leaseMillis, TimeUnit.MILLISECONDS);
    }
    @Override
    public void unlock(String value) {
        redisson.getLock(value).unlock();
    }
    @Override
    public boolean isLocked(String value) {
        return redisson.getLock(value).isLocked();
    }
    @Override
    public boolean isHeldByCurrentThread(String value) {
        return redisson.getLock(value).isHeldByCurrentThread();
    }
    @Override
    public int getHoldCount(String value) {
        return redisson.getLock(value).getHoldCount();
    }
    @Override
    public boolean tryLock(String value) {
        return redisson.getLock(value).tryLock();
    }
    @Override
    public boolean tryLock(String value, long timeoutMills) {
        return tryLock(value, timeoutMills, DEFAULT_LEASE_TIME);
    }
    @Override
    public boolean tryLock(String value, long timeoutMills, long leaseMillis) {
        try {
            return redisson.getLock(value).tryLock(timeoutMills, leaseMillis, TimeUnit.MILLISECONDS);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
     }
    }

Lock service
  
    LockClient  client;
    ThreadLocal<Boolean> isTransactional;
    //...
    @Override
    public boolean lock(String key) throws LockException {
        return lockWithTimeout(key, DEFAULT_EXPIRATION_TIME_IN_MILLIS);
    }
    @Override
    public boolean lockWithTimeout(String lockKey, long timeoutMills) throws LockException {
        boolean retValue;
        try {
            retValue = client.tryLock(lockKey, timeoutMills, lockTTLInRedis);
            if (retValue && client.getHoldCount(lockKey) == 1) {
                handleIsTransactional(lockKey);
            }
        } catch (Exception e) {
            //...
        }
        return retValue;
    }

    private void handleIsTransactional(String lockKey) {
        isTransactional.set(TransactionSynchronizationManager.isActualTransactionActive());
        if (isTransactional.get()) {
			//The current operation is in a transaction and will release the lock automatically while transaction completes
                        //...
        } else {
            //The lock operation is not in a transaction and release the lock manually
        }
    }

    @Override
    public boolean unlock(String lockKey) {
        try {
            if (isTransactional.get()) {
                logger.warn("Manual unlock  in transaction is not support and will unlock automatically after the transaction complete");
            } else {
                if (client.isHeldByCurrentThread(lockKey)) {
                    client.unlock(lockKey);
                } else {
                    logger.warn("The lock: " + lockKey + " is not held by current thread and will do nothing for this unlock operation");
                }
            }
        } catch (Exception e) {
            //
        }
        return true;
    }
`
Here is the callBack for transaction

    class LockTransactionCallBack extends TransactionSynchronizationAdapter{
    //...
    @Override
    public void afterCompletion(int status) {
	try {
		if (client.isHeldByCurrentThread(lockKey)) {
			while (client.isLocked(lockKey)) {
				client.unlock(lockKey);
			}
		} else {
			//...
		}

	} catch (Exception e) {
		/...
	}
    //...
    }

**Comment by mrniko** [comment]
At the first glance I don't see any potential problems in your code

**Comment by mrniko** [comment]
You can try to tune `Bootstrap` object options via `ChannelOption` settings

**Comment by mrniko** [comment]
Any news about it?

**Comment by mrniko** [comment]
Could you please check it again? I think I found the cause

**Comment by mrniko** [comment]
@zhxjouc ping

**Comment by mrniko** [comment]
@zhxjouc Fixed. Please check
