### ISSUE TITLE
Exception occurred. org.redisson.client.RedisTimeoutException: Redis server response timeout for command: (HGET) with params:

### ISSUE THREAD

**Issue by nareshsankapellyfkrt** [mrniko/redisson#462]
Hi, 

I have setup Redis in sentinel mode with 4 slaves and 1 master. As I increase the number of read requests, Redission is throwing RedisTimeoutException. The TimeOut is set to 5 sec and retry count is set to 5. Will increasing the number of slaves help?

**Comment by mrniko** [comment]
Which version do you use? 5 sec is too high for response, check your network please.

**Comment by nareshsankapellyfkrt** [comment]
I increased the number of slaves to 6 and was able to handle 400K reads per second without any timeout issue.

**Comment by mrniko** [comment]
It's impressive!

**Comment by mrniko** [comment]
@nareshsankapellyfkrt could you please share your redis servers configuration incl. hardware info and redisson instances amount you were used?
