### ISSUE TITLE
RedisTimeoutException with "large" objects

### ISSUE THREAD

**Issue by smigfu** [mrniko/redisson#466]
I have a simple setup with a SingleServer connected to a ElasticCache-Redis instance. I upload various sizes of bytes to measure the performance between those. Small objects up to 3 MB perform fine but above that I receive this error:

```
Exception in thread "main" org.redisson.client.RedisTimeoutException: Command execution timeout for command: (SETEX) with params: [da515c20-cba8-42ca-bd18-66249f4e06d9, 60, StorageObject@255d177b]
	at org.redisson.command.CommandAsyncService$5.run(CommandAsyncService.java:403)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:581)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:655)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:367)
	at java.lang.Thread.run(Thread.java:745)
```

In "Batch" mode is also see this:

```
Exception in thread "main" org.redisson.client.RedisTimeoutException: Batch command execution timeout
	at org.redisson.command.CommandBatchService$3.run(CommandBatchService.java:243)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:581)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:655)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:367)
	at java.lang.Thread.run(Thread.java:745)
```

My setup for connecting looks as following (I have a similar setup with redisson-reactive showing the same problem):

```
        final Config config = new Config();

        config.useSingleServer().setSubscriptionConnectionMinimumIdleSize(1);
        config.useSingleServer().setSubscriptionConnectionPoolSize(5);
        config.useSingleServer().setSubscriptionsPerConnection(5);
        config.setCodec(new SerializationCodec());
        config.useSingleServer().setAddress(configuration.getString("redis.endpoint"));
        config.useSingleServer().setDatabase(configuration.getInt("redis.database"));
        config.useSingleServer().setConnectionPoolSize(configuration.getInt("redis.pool.max"));
        config.useSingleServer().setConnectionMinimumIdleSize(configuration.getInt("redis.pool.min"));
        config.useSingleServer().setTimeout(60000);

        redissonClient = Redisson.create(config);

        // single
        redissonClient.getBucket(storageObject.getId()).set(storageObject, 60, SECONDS);

        // batch
        final RBatch batch = redissonClient.createBatch();
        for (final StorageObject storageObject : storageObjects)
        {
            batch.getBucket(storageObject.getId()).setAsync(storageObject, 60, SECONDS);
        }
        batch.execute();
```

I have tried using the latest versions (release + HEAD). I have debugged the issue but haven't found any obvious problem. The only thing I found is the timeout in "new HashedWheelTimer(minTimeout, TimeUnit.MILLISECONDS);" which is set to a 100ms (from MasterSlaveConfig) and seems to be the reason for cancelling the commands? Though I tried changing this without success.

Somebody has an idea about what might be causing the timeouts? Can I configure those to be suitable for bigger objects?

**Comment by mrniko** [comment]
Increase `setRetryInterval` timeout

**Comment by smigfu** [comment]
Thanks, increasing it to 60000 did the trick :) Could you quickly tell me why this affects that particular case with "large" objects?

**Comment by mrniko** [comment]
which objects size do you use? 3MB. network delay + serialization delay. Anyway it's hard to tell more precisely without deep investigation.

**Comment by smigfu** [comment]
I meant more like what does the ```setRetryInterval``` really do? The JavaDoc states ```Time interval after which another one attempt to send Redis command will be executed.``` Does this mean that if the command is not successfully finished within this timeframe it will restart the command?

As for the sizes I have two scenarios: ```{1, 10, 100, 1000, 10000, 100000, 350000, 1000000, 2000000, 3000000, 10000000} ```bytes locally (1 MB upload speed to Redis) as well as directly from a m4.2xlarge EC2-instance directly. Both of these in single and batch mode. The local mode start to fail with ~2-3 MB single whereas the EC2 case fails with 10.000.000 batch mode. I perform this comparison b/c we are currently investigating a proper storage-backend for our system (Redis, Postgres, S3, DynamoDB). I can share some numbers if you like.

**Comment by mrniko** [comment]
> The JavaDoc states Time interval after which another one attempt to send Redis command will be executed.

A new attempt to send Redis command will be executed if it wasn't sent during <code>retryInterval</code>. I will fix this comment.

> I perform this comparison b/c we are currently investigating a proper storage-backend for our system (Redis, Postgres, S3, DynamoDB). I can share some numbers if you like.

It would be nice to see

**Comment by smigfu** [comment]
These tests where performed from an EC2-instance (m4.2xlarge) to Postgresql (m4.2xlarge /w PIOPS), Redis (cache.m3.xlarge), DynamoDB, and S3. As described above there were single and batch (if supported by the API x 10 objects) tests for reading and writing. The filename denotes the amount of bytes being written/read. Since we were interested in the overall performance, these numbers do include the serializing/deserializing time of the "object" being stored. Postgres => JPA, Redis => SeriazationCodec, DynamoDB => manual creation of Maps, S3 => Java Serialization. The object being stored is rather simple and consists of an String ID and byte-Array. The sample rate is n=60.


![readbatch](https://cloud.githubusercontent.com/assets/1654912/14428626/1f551382-fffa-11e5-8fbb-0619b183b0d1.png)

---

![readsingle](https://cloud.githubusercontent.com/assets/1654912/14428631/24a7cfaa-fffa-11e5-9910-f2effc33c2db.png)

---

![writebatch](https://cloud.githubusercontent.com/assets/1654912/14428640/27ad7984-fffa-11e5-9668-4b0f17bc8032.png)

---

![writesingle](https://cloud.githubusercontent.com/assets/1654912/14428644/2c2d7716-fffa-11e5-9763-5185fbaea425.png)

**Comment by smigfu** [comment]
Thanks for the explanation of the retry-param.

**Comment by mrniko** [comment]
Oh, it looks like scientific work. Great! Anyway, use FstCodec it's much faster than SeriazationCodec. Which Redisson version did you use?

**Comment by smigfu** [comment]
The version for these tests is 2.2.11, I have also tried with the FST codec (as it sounded promising), though it doesn't run out of the box in our app-server (which is an OSGi server) due to class-path issues. I guess I need to ask the FST guys to add the "dynamic-import" (as I did for this project some time ago :-)).

**Comment by mrniko** [comment]
According to your tests Postgres has same speed as Redis. Was it run with ramdisk?

**Comment by smigfu** [comment]
No, we don't use ramdisk but Postgres has a significant amount of PIOPS. I think the main advantage of Postgres in that case is that the serialization via JPA works more efficient as the SerialiazionCodec used in the Redis case.

**Comment by jackygurui** [comment]
Technically, JPA only serialise the value of entity fields. It generates insert statements for new(detached) entity objects, and update statements for existing(attached) entity objects. These statements doesn't usually have all the schema information since they are already defined in the database. i.e. insert statements does not usually specify column names and update statements only mention changed fields.

On the other hand with any NoSQL schemaless DBMS, to "persist" a piece of information, you would usually have to specify the schema along with the value it represents. This is the trade off for being schemaless.

Since you really have to compare the performance between PostgreSQL to Redis, I'd make the test fairer by serialize the objects to byte[] first before send them to each database.
