### ISSUE TITLE
IllegalStateException while iterating over RMapCache using an iterator

### ISSUE THREAD

**Issue by nel10000** [mrniko/redisson#468]
While iterating over an RMapCache object with an iterator, an "IllegalStateException" occurs  on the second removal of an entry from the map.
The map structure is RMapCache<String, List<Object>>.
The iterator is received via cacheMap.entrySet().iterator().
The iterator removes successfully the first entry, but upon the second entry removal it fails with the exception mentioned above.
Please note this code used to work fine with a regular Java Map.
Here is the code:
	`	
	
	private long clearExpiredItems(RMapCache<String, List<ItemInfo>> mapCache) {
		long maximalExpirationTime = 0;
		Iterator<Entry<String, List<ItemInfo>>> mapCacheIterator = mapCache.entrySet().iterator();
		while (mapCacheIterator.hasNext()) {
			Entry<String, List<ItemInfo>> userMapCacheEntry = mapCacheIterator.next();
			List<ItemInfo> userMapCache = userMapCacheEntry.getValue();
			for (Iterator<ItemInfo> iterator = userMapCache.iterator(); iterator.hasNext();) {
				ItemInfo itemInfo = iterator.next();
				long tempMaximalExpirationTime = itemInfo.getExpirationTime();
				if (itemInfo.getExpirationTime() < System.currentTimeMillis() / 1000) {
					tempMaximalExpirationTime = 0;
					iterator.remove();
				}
				maximalExpirationTime = tempMaximalExpirationTime > maximalExpirationTime ? tempMaximalExpirationTime : maximalExpirationTime;
			}
			if (userMapCache.isEmpty()) {
				mapCacheIterator.remove();
			}
		}
		return maximalExpirationTime;
	}`

And here is the relevant stack trace:

> java.lang.IllegalStateException
	at java.util.HashMap$HashIterator.remove(HashMap.java:1441) ~[?:1.8.0_40]
	at org.redisson.RedissonBaseMapIterator.remove(RedissonBaseMapIterator.java:117) ~[redisson-2.2.10.jar:?]
	at org.redisson.RedissonMapIterator.remove(RedissonMapIterator.java:23) ~[redisson-2.2.10.jar:?]

**Comment by mrniko** [comment]
Fixed. Please check
