### ISSUE TITLE
In Cluster when master goes down and his slave becomes a master, Redisson does not recognize the new master

### ISSUE THREAD

**Issue by ybonda** [mrniko/redisson#474]
Hi, 

I configured Redisson, see below, and it works, but when I shutdown one redis master and his slave on other machine becomes a master (in 5 sec) Redisson cannot recognize the new master and the request seems like still go to the old master which is not exist.
Please assist ASAP.

Thanks!

Redisson.json:
{
   "clusterServersConfig":{
      "idleConnectionTimeout":10000,
      "pingTimeout":1000,
      "connectTimeout":1000,
      "timeout":1000,
      "retryAttempts":3,
      "retryInterval":1000,
      "reconnectionTimeout":3000,
      "failedAttempts":3,
      "password":null,
      "subscriptionsPerConnection":5,
      "clientName":null,
      "loadBalancer":{
         "class":"org.redisson.connection.balancer.RoundRobinLoadBalancer"
      },
      "slaveSubscriptionConnectionMinimumIdleSize":1,
      "slaveSubscriptionConnectionPoolSize":25,
      "slaveConnectionMinimumIdleSize":5,
      "slaveConnectionPoolSize":100,
      "masterConnectionMinimumIdleSize":5,
      "masterConnectionPoolSize":100,
      "readMode":"SLAVE",
      "nodeAddresses":[
        "//172.31.160.110:7000",
        "//172.31.160.110:7001",
        "//172.31.160.112:7000",
        "//172.31.160.112:7001",
        "//172.31.160.111:7000",
        "//172.31.160.111:7001"
        ],
      "scanInterval":1000
   },
   "threads":0,
   "codec":null,
   "useLinuxNativeEpoll":false,
   "eventLoopGroup":null
}

Redis.conf:

port 7000
bind 172.31.160.110

cluster-enabled yes
cluster-config-file nodes.conf
cluster-node-timeout 5000
cluster-slave-validity-factor 1

maxmemory 2048mb
maxmemory-policy volatile-ttl
slave-read-only yes

save 900 1
save 300 10
save 60 10000
stop-writes-on-bgsave-error yes
rdbchecksum yes
dbfilename dump.rdb
appendonly yes

logfile redis.log
loglevel notice
slowlog-log-slower-than 10000
slowlog-max-len 64
latency-monitor-threshold 100

**Comment by mrniko** [comment]
Please provide Redis and Redisson versions

**Comment by nel10000** [comment]
Hello Mr Niko!
The Redis version is 3.0.7 and Redisson version is 2.2.11.
Please let us know if any further information is required.
Thanks!

**Comment by ybonda** [comment]
Hello Mr Niko!
The Redis version is 3.0.7 and Redisson version is 2.2.11.

**Comment by mrniko** [comment]
I have checked it. ClusterConnectionManager works correctly. Here is the log

12:29:16 [nioEventLoopGroup-2-4] INFO org.redisson.cluster.ClusterConnectionManager - changing master from //127.0.0.1:7002 to //127.0.0.1:7005 for [10923-16383]
12:29:16 [nioEventLoopGroup-2-15] INFO org.redisson.connection.pool.MasterConnectionPool - 5 connections initialized for /127.0.0.1:7005
12:29:18 [nioEventLoopGroup-2-4] INFO org.redisson.connection.MasterSlaveEntry - master 127.0.0.1:7005 used as slave
12:29:18 [nioEventLoopGroup-2-4] INFO org.redisson.cluster.ClusterConnectionManager - slave //127.0.0.1:7005 removed for slot ranges: [[10923-16383]]
12:29:18 [nioEventLoopGroup-2-4] INFO org.redisson.cluster.ClusterConnectionManager - [10923-16383] slot removed for 127.0.0.1/127.0.0.1:7005
12:29:18 [nioEventLoopGroup-2-4] INFO org.redisson.cluster.ClusterConnectionManager - [[10923-16383]] slots found to add

**Comment by mrniko** [comment]
Do you see `changing master from ` line in your logs?

**Comment by mrniko** [comment]
Also please check your Redis cluster configuration for each node

**Comment by mrniko** [comment]
Anyway, I found another bug with slots migration https://github.com/mrniko/redisson/issues/475

**Comment by ybonda** [comment]
In our scenario we have 3 machines on each machine is Master and Slave, like this:
M1S3, M2S1, M3S2

When I should down first machine with Master1 and Slave3 in 5 seconds Slave1 on second machine becomes a master (M1), but redisson requests fails. 
The Redis configuration is the same for all nodes (changes only in IP, port 7000 for masters and 7001 for slaves):

port 7000
bind 172.31.160.110

cluster-enabled yes
cluster-config-file nodes.conf
cluster-node-timeout 5000
cluster-slave-validity-factor 1

maxmemory 2048mb
maxmemory-policy volatile-ttl
slave-read-only yes

save 900 1
save 300 10
save 60 10000
stop-writes-on-bgsave-error yes
rdbchecksum yes
dbfilename dump.rdb
appendonly yes

logfile redis.log
loglevel notice
slowlog-log-slower-than 10000
slowlog-max-len 64
latency-monitor-threshold 100

**Comment by mrniko** [comment]
Try to switch Redisson logging level to `debug` and find this line `cluster nodes state from` before master change and after. Post it here, please

**Comment by ybonda** [comment]
Hi Niko,

This is the log, but in info level (redis server on first machine  being restarted)l:

18 Apr 2016 15:16:51  INFO  - Redisson 2.2.11
18 Apr 2016 15:16:52  INFO  - slaves: [//10.20.21.113:7001] added for slot ranges: [[0-5461]]
18 Apr 2016 15:16:52  INFO  - slaves: [//10.20.21.59:7001] added for slot ranges: [[5462-10922]]
18 Apr 2016 15:16:52  INFO  - slaves: [//10.20.21.44:7001] added for slot ranges: [[10923-16383]]
18 Apr 2016 15:16:52  INFO  - 5 connections initialized for /10.20.21.113:7000
18 Apr 2016 15:16:52  INFO  - master: //10.20.21.113:7000 added for slot ranges: [[5462-10922]]
18 Apr 2016 15:16:52  INFO  - 5 connections initialized for /10.20.21.44:7000
18 Apr 2016 15:16:52  INFO  - master: //10.20.21.44:7000 added for slot ranges: [[0-5461]]
18 Apr 2016 15:16:52  INFO  - 5 connections initialized for /10.20.21.59:7001
18 Apr 2016 15:16:52  INFO  - 5 connections initialized for /10.20.21.113:7001
18 Apr 2016 15:16:52  INFO  - 5 connections initialized for /10.20.21.44:7001
18 Apr 2016 15:16:52  INFO  - 5 connections initialized for /10.20.21.59:7000
18 Apr 2016 15:16:52  INFO  - master: //10.20.21.59:7000 added for slot ranges: [[10923-16383]]
18 Apr 2016 15:16:52  INFO  - 1 connections initialized for /10.20.21.59:7001
18 Apr 2016 15:16:52  INFO  - 1 connections initialized for /10.20.21.44:7001
18 Apr 2016 15:16:52  INFO  - 1 connections initialized for /10.20.21.113:7001
18 Apr 2016 15:20:43  WARN  - host /10.20.21.44:7000 disconnected due to failedAttempts=3 limit reached
18 Apr 2016 15:20:48  INFO  - master ip-10-20-21-59.ec2.internal:7000 used as slave
18 Apr 2016 15:20:48  WARN  - slave: //10.20.21.44:7001 has down for slot ranges: [[10923-16383]]
18 Apr 2016 15:20:50  INFO  - changing master from //10.20.21.44:7000 to //10.20.21.113:7001 for [0-5461]
18 Apr 2016 15:20:50  INFO  - master ip-10-20-21-113.ec2.internal:7001 used as slave
18 Apr 2016 15:20:50  INFO  - slave //10.20.21.113:7001 removed for slot ranges: [[0-5461]]
18 Apr 2016 15:20:50  INFO  - [0-5461] slot removed for ip-10-20-21-113.ec2.internal/10.20.21.113:7001
18 Apr 2016 15:20:50  INFO  - [[0-5461]] slots found to add
18 Apr 2016 15:20:50  INFO  - 5 connections initialized for ip-10-20-21-113.ec2.internal/10.20.21.113:7001
18 Apr 2016 15:20:50  INFO  - 5 connections initialized for /10.20.21.113:7001
18 Apr 2016 15:20:50  INFO  - master: //10.20.21.113:7001 added for slot ranges: [[0-5461]]
18 Apr 2016 15:24:53  INFO  - master ip-10-20-21-59.ec2.internal:7000 excluded from slaves
18 Apr 2016 15:24:53  INFO  - slave: //10.20.21.44:7001 has up for slot ranges: [[10923-16383]]
18 Apr 2016 15:25:01  INFO  - master ip-10-20-21-113.ec2.internal:7001 excluded from slaves
18 Apr 2016 15:25:01  INFO  - slave //10.20.21.44:7000 added for slot ranges: [[0-5461]]

**Comment by ybonda** [comment]
Here is the log with Debug level on same scenario:

18 Apr 2016 13:40:04  INFO  - master ip-10-20-21-59.ec2.internal:7000 used as slave
18 Apr 2016 13:40:04  WARN  - slave: //10.20.21.44:7001 has down for slot ranges: [[10923-16383]]
18 Apr 2016 13:40:05  DEBUG - cluster nodes state from /10.20.21.113:7000:
d7d45ad6d12dfe65dff2867be05eef678ef72f69 10.20.21.44:7000 master,fail - 1460986798993 1460986798893 1 disconnected
c034167f1ec790f4a5fdb28bb91843b03cbc77a0 10.20.21.113:7000 myself,master - 0 0 2 connected 5462-10922
bba828ee8151f5addb0cb3d3bf91db559837c13f 10.20.21.59:7000 master - 0 1460986804913 3 connected 10923-16383
69243875fc4a0dea0a95d559fbc8be8e8550c25f 10.20.21.59:7001 slave c034167f1ec790f4a5fdb28bb91843b03cbc77a0 0 1460986804413 5 connected
de0ecb56f8cd28fc99807d51851bc735887e5a0a 10.20.21.113:7001 master - 0 1460986805415 6 connected 0-5461
9a74b8c329437cb845d409b34222a3adbe6146d2 10.20.21.44:7001 slave,fail bba828ee8151f5addb0cb3d3bf91db559837c13f 1460986798993 1460986796887 4 disconnected

18 Apr 2016 13:40:05  INFO  - changing master from //10.20.21.44:7000 to //10.20.21.113:7001 for [0-5461]
18 Apr 2016 13:40:05  DEBUG - new connection created: RedisConnection [redisClient=[addr=/10.20.21.113:7001], channel=[id: 0x10ef6d45, L:/10.20.21.44:52360 - R:/10.20.21.113:7001]]
18 Apr 2016 13:40:05  DEBUG - new connection created: RedisConnection [redisClient=[addr=/10.20.21.113:7001], channel=[id: 0xe306a34b, L:/10.20.21.44:52361 - R:/10.20.21.113:7001]]
18 Apr 2016 13:40:05  DEBUG - new connection created: RedisConnection [redisClient=[addr=/10.20.21.113:7001], channel=[id: 0x3a1e2e32, L:/10.20.21.44:52362 - R:/10.20.21.113:7001]]
18 Apr 2016 13:40:05  INFO  - master ip-10-20-21-113.ec2.internal:7001 used as slave
18 Apr 2016 13:40:05  INFO  - slave //10.20.21.113:7001 removed for slot ranges: [[0-5461]]
18 Apr 2016 13:40:05  INFO  - [0-5461] slot removed for ip-10-20-21-113.ec2.internal/10.20.21.113:7001
18 Apr 2016 13:40:05  INFO  - [[0-5461]] slots found to add
18 Apr 2016 13:40:05  DEBUG - new connection created: RedisConnection [redisClient=[addr=ip-10-20-21-113.ec2.internal/10.20.21.113:7001], channel=[id: 0xe5ad2590, L:/10.20.21.44:52364 - R:ip-10-20-21-113.ec2.internal/10.20.21.113:7001]]
18 Apr 2016 13:40:05  DEBUG - new connection created: RedisConnection [redisClient=[addr=ip-10-20-21-113.ec2.internal/10.20.21.113:7001], channel=[id: 0x4f2225de, L:/10.20.21.44:52365 - R:ip-10-20-21-113.ec2.internal/10.20.21.113:7001]]
18 Apr 2016 13:40:05  INFO  - 5 connections initialized for ip-10-20-21-113.ec2.internal/10.20.21.113:7001
18 Apr 2016 13:40:05  DEBUG - new connection created: RedisConnection [redisClient=[addr=/10.20.21.113:7001], channel=[id: 0x8ebd9427, L:/10.20.21.44:52366 - R:/10.20.21.113:7001]]
18 Apr 2016 13:40:05  DEBUG - new connection created: RedisConnection [redisClient=[addr=/10.20.21.113:7001], channel=[id: 0xe3126f0a, L:/10.20.21.44:52368 - R:/10.20.21.113:7001]]
18 Apr 2016 13:40:05  DEBUG - new connection created: RedisConnection [redisClient=[addr=/10.20.21.113:7001], channel=[id: 0x883fe76b, L:/10.20.21.44:52367 - R:/10.20.21.113:7001]]
18 Apr 2016 13:40:05  DEBUG - new connection created: RedisConnection [redisClient=[addr=/10.20.21.113:7001], channel=[id: 0x8201e041, L:/10.20.21.44:52369 - R:/10.20.21.113:7001]]
18 Apr 2016 13:40:05  DEBUG - new connection created: RedisConnection [redisClient=[addr=/10.20.21.113:7001], channel=[id: 0xea947f35, L:/10.20.21.44:52370 - R:/10.20.21.113:7001]]
18 Apr 2016 13:40:05  INFO  - 5 connections initialized for /10.20.21.113:7001
18 Apr 2016 13:40:05  INFO  - master: //10.20.21.113:7001 added for slot ranges: [[0-5461]]
18 Apr 2016 13:40:06  DEBUG - cluster nodes state from /10.20.21.113:7000:
d7d45ad6d12dfe65dff2867be05eef678ef72f69 10.20.21.44:7000 master,fail - 1460986798993 1460986798893 1 disconnected
c034167f1ec790f4a5fdb28bb91843b03cbc77a0 10.20.21.113:7000 myself,master - 0 0 2 connected 5462-10922
bba828ee8151f5addb0cb3d3bf91db559837c13f 10.20.21.59:7000 master - 0 1460986804913 3 connected 10923-16383
69243875fc4a0dea0a95d559fbc8be8e8550c25f 10.20.21.59:7001 slave c034167f1ec790f4a5fdb28bb91843b03cbc77a0 0 1460986804413 5 connected
de0ecb56f8cd28fc99807d51851bc735887e5a0a 10.20.21.113:7001 master - 0 1460986805415 6 connected 0-5461
9a74b8c329437cb845d409b34222a3adbe6146d2 10.20.21.44:7001 slave,fail bba828ee8151f5addb0cb3d3bf91db559837c13f 1460986798993 1460986796887 4 disconnected

**Comment by mrniko** [comment]
> but jmeter shows that number of failed requests raised up.

Some commands will be lost during master change. Does failed requests rise infinitely?

**Comment by ybonda** [comment]
Hi Niko.
 
Thank you very much for your support,
According to what I saw it seems like Redis Cluster configuration issue, not Redisson.

Spasibo bratan!

**Comment by mrniko** [comment]
You're welcome!

Obrachaysa!

**Comment by RedWhiteMiko** [comment]
Hi @ybonda, could you explain what issue in your Redis Cluster configuration?
Thank you

**Comment by Lakshmihm** [comment]
Hi @ybonda  facing similar issue. Could you please provide more details what the issue was in Redis configuration?
