### ISSUE TITLE
Error if first node is down in 3 node Master-Master cluster 

### ISSUE THREAD

**Issue by MdSarfarazKhan** [mrniko/redisson#477]
I have a Master Master redis cluster of 3 (node1,node2,node3). Locking mechanism works fine if we block the network for node2 or node 3. But if we block node1's network then it fails with the below error

```
Exception in thread "main" org.redisson.client.RedisNodeNotFoundException: No node for slot: 15087 and command (EVAL)
at org.redisson.connection.MasterSlaveConnectionManager.getEntry(MasterSlaveConnectionManager.java:578)
at org.redisson.connection.MasterSlaveConnectionManager.connectionWriteOp(MasterSlaveConnectionManager.java:563)
at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:368)
at org.redisson.command.CommandAsyncService.evalAsync(CommandAsyncService.java:334)
at org.redisson.command.CommandAsyncService.evalWriteAsync(CommandAsyncService.java:282)
at org.redisson.RedissonLock.tryLockInnerAsync(RedissonLock.java:207)
at org.redisson.RedissonLock.tryAcquire(RedissonLock.java:139)
at org.redisson.RedissonLock.tryLock(RedissonLock.java:225)
at com.seamless.common.cache.distributed.LockManager.getLock(LockManager.java:37)
at com.testlock.app.App.main(App.java:34)
```

Below is how I'm creating the Redission client
`
import java.util.List;
import java.util.concurrent.TimeUnit;

import org.apache.log4j.Logger;
import org.redisson.ClusterServersConfig;
import org.redisson.Config;
import org.redisson.ReadMode;
import org.redisson.Redisson;
import org.redisson.RedissonClient;
import org.redisson.core.RLock;

public class LockManager {
	
	private static final Logger LOG = Logger.getLogger(LockManager.class);
	
	
	private RedissonClient redissonClient;

	LockManager(List<String> nodes){
		Config config = new Config();
		ClusterServersConfig serverConfig=config.useClusterServers();
		serverConfig.setReadMode(ReadMode.MASTER);
		
		for(String node :nodes){
			serverConfig.addNodeAddress(node);
		}
		redissonClient = Redisson.create(config);
		
	}
	
	public boolean getLock(final String lockKey,int timeout){
		RLock lock=redissonClient.getLock(lockKey);
		try {
			return lock.tryLock(0, timeout, TimeUnit.MILLISECONDS);
		} catch (InterruptedException e) {
			LOG.error("Error getting lock "+e.getMessage());
		}
		return false;
	}	
	
	public void releaseLock(final String lockKey){
		RLock lock=redissonClient.getLock(lockKey);
		if(lock.isHeldByCurrentThread())
			lock.unlock();
	}
}
`

**Comment by mrniko** [comment]
> Locking mechanism works fine if we block the network for node2 or node 3. But if we block node1's network then it fails with the below error

This error occurs because master for slot 15087 was shutdown. Failover did not work because you have no slave server for this master. Add slave servers for each master

**Comment by MdSarfarazKhan** [comment]
@mrniko Thanks for the quick response. But I have few question 
1) The [RedLock](http://redis.io/topics/distlock) algorithm mentioned is supposed to work with master master setup(without any slave)?
2) If I'm supposed to add slave for each master do I need to configure in the Redission config as well. Like instead of `ClusterServersConfig serverConfig=config.useClusterServers();` shall I use `config.useMasterSlaveServers() `. If so in the API I can only find methods to add only one master address.
Thanks in advance.

P.S I'm new to Redis.

**Comment by MdSarfarazKhan** [comment]
@mrniko so this means that Redission's Redlock algorithm will work only with Master-Slave model in terms of fail over ?There is no internal failover mechanism build in the client? Suppose I have 3 redis node cluster in master-master mode. I have created the client with round robin load balancer.Now in normal scenario if I try to acquire a lock it works fine. If now out of three 1 node goes down. Now if I go to acquire a lock should it fail or should it acquire in the active 2 nodes (according to the Redlock algorithm). 
P.S In my case it fails.

**Comment by mrniko** [comment]
If you talking about RedLock where you need to acquire N locks, then you need to use [RedissonMultiLock](https://github.com/mrniko/redisson/wiki/5.-distributed-objects#55-multilock) object

**Comment by MdSarfarazKhan** [comment]
@mrniko  Thanks .One quick question will RedLock algorithm work if 3 redis master nodes are connected in cluster mode or is it necessary that they are independent masters not connected in a cluster?

**Comment by mrniko** [comment]
@MdSarfarazKhan RedissonMultiLock doesn't depend on RLock source. So it should work in a cluster too.

**Comment by phoebechengz** [comment]
@MdSarfarazKhan What is your solution of this issue? I try to use RedissonMultiLock with 5 independent masters, But it will throw exception if I shutdown one of the nodes.

**Comment by dotrungduchd** [comment]
Any master has hashslot down -> cluster down -> exception

**Comment by phoebechengz** [comment]
@dotrungduchd  According to the  Redlock algorithm(http://redis.io/topics/distlock), if a redis instance is not available it should try to talk with next instance but not throw exception. Did I make  mistake in using RedissonMultiLock?

**Comment by phoebechengz** [comment]
Will solve this issue in 2.2.7. See issue #533
