### ISSUE TITLE
A bug about RScoredSortedSet#revRank method 

### ISSUE THREAD

**Issue by damacheng009** [mrniko/redisson#478]
public static void main(String[] args) {
		Config config = new Config();

		config.setCodec(new JsonJacksonCodec());
                config.useSingleServer().setAddress("127.0.0.1:6379");
        
                RedissonClient redisson = Redisson.create(config);
                RScoredSortedSet<Integer> set = redisson.getScoredSortedSet("test");
                set.add(1.0, 4);
        
                Integer rank = set.revRank(4); // no problem 
                System.out.println(rank);
                Integer rank1 = set.revRank(1); // throw java.lang.NullPointerException, I think rank1 should be null and not throw Exception 
                System.out.println(rank1 == null);

                redisson.shutdown();
	}

**Comment by mrniko** [comment]
Fixed
