### ISSUE TITLE
Connection pool exhausted! error in Redis Cluster

### ISSUE THREAD

**Issue by ybonda** [mrniko/redisson#479]
Hi Niko!

We constantly have "connection pool exhausted" errors on our env.
The configuration is : 3 machines with 1 master and 1 slave on each machine.

May be we should tune some configurations in our redisson config?

### Can you please explain briefly the meaning of these:
`  "slaveSubscriptionConnectionMinimumIdleSize":1,
      "slaveSubscriptionConnectionPoolSize":25,
      "slaveConnectionMinimumIdleSize":5,
      "slaveConnectionPoolSize":100,
      "masterConnectionMinimumIdleSize":5,
      "masterConnectionPoolSize":100,
      "readMode":"SLAVE",`

### This is our redisson config file:

{
   "clusterServersConfig":{
      "idleConnectionTimeout":10000,
      "pingTimeout":1000,
      "connectTimeout":1000,
      "timeout":1000,
      "retryAttempts":3,
      "retryInterval":1000,
      "reconnectionTimeout":3000,
      "failedAttempts":3,
      "password":null,
      "subscriptionsPerConnection":5,
      "clientName":null,
      "loadBalancer":{
         "class":"org.redisson.connection.balancer.RoundRobinLoadBalancer"
      },
      "slaveSubscriptionConnectionMinimumIdleSize":1,
      "slaveSubscriptionConnectionPoolSize":25,
      "slaveConnectionMinimumIdleSize":5,
      "slaveConnectionPoolSize":100,
      "masterConnectionMinimumIdleSize":5,
      "masterConnectionPoolSize":100,
      "readMode":"SLAVE",
      "nodeAddresses":[
	"//10.20.21.44:7000",
	"//10.20.21.44:7001",
	"//10.20.21.113:7000",
	"//10.20.21.113:7001",
	"//10.20.21.59:7000",
	"//10.20.21.59:7001"
	],
      "scanInterval":1000
   },
   "threads":0,
   "codec":null,
   "useLinuxNativeEpoll":false,
   "eventLoopGroup":null
}

### These are errors that we get: 

21 Apr 2016 12:16:43  ERROR - An error occurred when opening a session. Error: Connection pool exhausted! for slots: [[0-5461]] Disconnected hosts: [/10.20.21.44:7000]
21 Apr 2016 12:16:44  ERROR - An error occurred when opening a session. Error: Connection pool exhausted! for slots: [[0-5461]] Disconnected hosts: [/10.20.21.44:7000]
21 Apr 2016 12:19:31  ERROR - An error occurred when opening a session. Error: Connection pool exhausted! for slots: [[0-5461]] Hosts with fully busy connections: [ip-10-20-21-113.ec2.internal/10.20.21.113:7001]
21 Apr 2016 12:19:31  ERROR - An error occurred when opening a session. Error: Connection pool exhausted! for slots: [[10923-16383]] Hosts with fully busy connections: [ip-10-20-21-59.ec2.internal/10.20.21.59:7000]
21 Apr 2016 12:19:31  ERROR - An error occurred when opening a session. Error: Connection pool exhausted! for slots: [[5462-10922]] Hosts with fully busy connections: [/10.20.21.113:7000]
21 Apr 2016 12:19:31  ERROR - An error occurred when opening a session. Error: Connection pool exhausted! for slots: [[10923-16383]] Hosts with fully busy connections: [ip-10-20-21-59.ec2.internal/10.20.21.59:7000]
21 Apr 2016 12:19:31  ERROR - An error occurred when opening a session. Error: Connection pool exhausted! for slots: [[10923-16383]] Hosts with fully busy connections: [ip-10-20-21-59.ec2.internal/10.20.21.59:7000]
21 Apr 2016 12:19:31  ERROR - An error occurred when opening a session. Error: Connection pool exhausted! for slots: [[10923-16383]] Hosts with fully busy connections: [ip-10-20-21-59.ec2.internal/10.20.21.59:7000]
21 Apr 2016 12:19:31  ERROR - An error occurred when closing a session. Error: Connection pool exhausted! for slots: [[10923-16383]] Hosts with fully busy connections: [ip-10-20-21-59.ec2.internal/10.20.21.59:7000]
21 Apr 2016 12:19:31  ERROR - An error occurred when closing a session. Error: Connection pool exhausted! for slots: [[5462-10922]] Hosts with fully busy connections: [/10.20.21.113:7000]
21 Apr 2016 12:19:31  ERROR - An error occurred when closing a session. Error: Connection pool exhausted! for slots: [[10923-16383]] Hosts with fully busy connections: [ip-10-20-21-59.ec2.internal/10.20.21.59:7000]
21 Apr 2016 12:19:31  ERROR - An error occurred when opening a session. Error: Connection pool exhausted! for slots: [[10923-16383]] Hosts with fully busy connections: [ip-10-20-21-59.ec2.internal/10.20.21.59:7000]
21 Apr 2016 12:19:31  ERROR - An error occurred when closing a session. Error: Connection pool exhausted! for slots: [[5462-10922]] Hosts with fully busy connections: [/10.20.21.113:7000]
21 Apr 2016 12:19:31  ERROR - An error occurred when opening a session. Error: Connection pool exhausted! for slots: [[10923-16383]] Hosts with fully busy connections: [ip-10-20-21-59.ec2.internal/10.20.21.59:7000]
21 Apr 2016 12:19:31  ERROR - An error occurred when opening a session. Error: Connection pool exhausted! for slots: [[5462-10922]] Hosts with fully busy connections: [/10.20.21.113:7000]
21 Apr 2016 12:19:31  ERROR - An error occurred when opening a session. Error: Connection pool exhausted! for slots: [[10923-16383]] Hosts with fully busy connections: [ip-10-20-21-59.ec2.internal/10.20.21.59:7000]
21 Apr 2016 12:19:31  ERROR - An error occurred when opening a session. Error: Connection pool exhausted! for slots: [[10923-16383]] Hosts with fully busy connections: [ip-10-20-21-59.ec2.internal/10.20.21.59:7000]
21 Apr 2016 12:19:31  ERROR - An error occurred when opening a session. Error: Connection pool exhausted! for slots: [[0-5461]] Hosts with fully busy connections: [ip-10-20-21-113.ec2.internal/10.20.21.113:7001]
21 Apr 2016 12:19:31  ERROR - An error occurred when closing a session. Error: Connection pool exhausted! for slots: [[10923-16383]] Hosts with fully busy connections: [ip-10-20-21-59.ec2.internal/10.20.21.59:7000]
21 Apr 2016 12:19:31  ERROR - An error occurred when opening a session. Error: Connection pool exhausted! for slots: [[5462-10922]] Hosts with fully busy connections: [/10.20.21.113:7000]
21 Apr 2016 12:19:31  ERROR - An error occurred when opening a session. Error: Connection pool exhausted! for slots: [[5462-10922]] Hosts with fully busy connections: [/10.20.21.113:7000]
21 Apr 2016 12:19:31  ERROR - An error occurred when opening a session. Error: Connection pool exhausted! for slots: [[10923-16383]] Hosts with fully busy connections: [ip-10-20-21-59.ec2.internal/10.20.21.59:7000]
21 Apr 2016 12:19:31  ERROR - An error occurred when opening a session. Error: Connection pool exhausted! for slots: [[0-5461]] Hosts with fully busy connections: [ip-10-20-21-113.ec2.internal/10.20.21.113:7001]
21 Apr 2016 12:19:31  ERROR - An error occurred when opening a session. Error: Connection pool exhausted! for slots: [[10923-16383]] Hosts with fully busy connections: [ip-10-20-21-59.ec2.internal/10.20.21.59:7000]
21 Apr 2016 12:19:31  ERROR - An error occurred when opening a session. Error: Connection pool exhausted! for slots: [[10923-16383]] Hosts with fully busy connections: [ip-10-20-21-59.ec2.internal/10.20.21.59:7000]
21 Apr 2016 12:19:31  ERROR - An error occurred when opening a session. Error: Connection pool exhausted! for slots: [[10923-16383]] Hosts with fully busy connections: [ip-10-20-21-59.ec2.internal/10.20.21.59:7000]
21 Apr 2016 12:19:31  ERROR - An error occurred when opening a session. Error: Connection pool exhausted! for slots: [[10923-16383]] Hosts with fully busy connections: [ip-10-20-21-59.ec2.internal/10.20.21.59:7000]
21 Apr 2016 12:19:31  ERROR - An error occurred when opening a session. Error: Connection pool exhausted! for slots: [[0-5461]] Hosts with fully busy connections: [ip-10-20-21-113.ec2.internal/10.20.21.113:7001]
21 Apr 2016 12:19:31  ERROR - An error occurred when opening a session. Error: Connection pool exhausted! for slots: [[0-5461]] Hosts with fully busy connections: [ip-10-20-21-113.ec2.internal/10.20.21.113:7001]

**Comment by ybonda** [comment]
After further investigation we found out that increasing slaveConnectionPoolSize and masterConnectionPoolSize to 500 solved the problem.
 
Thanks :8ball:

**Comment by mrniko** [comment]
100 connections per node is just default value. It's important to tune your connection pool size according your load.
