### ISSUE TITLE
Rlock performance issue

### ISSUE THREAD

**Issue by yuvalamar** [mrniko/redisson#486]
Hi

I am using reddison Rlock with a cluster setup , and sometimes I see latency( up to 1000ms)  when trying to acquire the lock or unlock.
I saw this issue opened by zhxjouc  (https://github.com/mrniko/redisson/issues/455) with a similar problem  and I am working with 2.2.13 but I am still getting latency when a thread is trying  lock a key.
My code is running with Java thread pool for accessing redis, I notice that if I work with pool of size 1-2
almost no latency when getting the lock, but working with 30-50 threads cause the lock delay.
It could be thread overhead issue but I think that 1000ms is too long for that.
Any help on how can I get better performance when locking an unlocking?.

Thanks

**Comment by mrniko** [comment]
Hi!

What RLock methods do you use?

**Comment by yuvalamar** [comment]
I tried :
lock.tryLock(1000,1000,TimeUnit.MILLISECONDS);
and
lock.tryLock(1000,TimeUnit.MILLISECONDS);

**Comment by mrniko** [comment]
How did you measure delay?

**Comment by mrniko** [comment]
According your code example tryLock will wait exactly 1000 ms to acquire lock

**Comment by yuvalamar** [comment]
the trylock() method returns fasle. 
 when false is returned I log an error.
I also tried the lock.lock() and loged the time before the lock and after the lock and somtimes I got over 1000ms.
 The code between lock ... unlock is empty

**Comment by mrniko** [comment]
Try to add some time counters to inner methods like subscribe and unsubscribe and tryAcquire methods. Like if timeout > 500ms then log it.

**Comment by mrniko** [comment]
Could you please provide your config too?

**Comment by yuvalamar** [comment]
Hi , sorry for the delayed response 
I am using a simple config:
        Config config = new Config();
        config.useClusterServers()
                .addNodeAddress(ips) //ips = list of cluster ips
                .setMasterConnectionPoolSize(100);

I want to add the time counters to the code , but I am not sure where exactly should add it 
can you please provide a code example?

**Comment by yuvalamar** [comment]
Also I think the following code reproduces the problem(at least on my system):

`public class TestRedisson {
    public static ExecutorService redisExecutor;
    static RedissonClient client;

    public static void main(String[] args) throws InterruptedException {
        Config config = new Config();
        config.useClusterServers()
                .addNodeAddress("10.10.18.120:7001","10.10.18.120:7002", "10.10.18.122:7003", "10.10.18.122:7004", "10.10.18.124:7005", "10.10.18.124:7006")
                .setMasterConnectionPoolSize(100);

        client = Redisson.create(config);
        System.out.println(client.getConfig().isClusterConfig());

        System.out.println("GO");
        redisExecutor = Executors.newFixedThreadPool(100);
        long s = System.currentTimeMillis();
        Set<Callable<String>> tasks = new HashSet<Callable<String>>();
        for(int j=0;j<100;j++)
        {
            for (int i=0;i<500;i++)
             {
                RedissonTask t = new RedissonTask();
                 redisExecutor.submit(t);
             }
            Thread.sleep(2);
        }

        System.out.println("done "+(System.currentTimeMillis() - s));

        redisExecutor.shutdown();;
        redisExecutor.awaitTermination(10,TimeUnit.MINUTES);
        System.out.println("Shutdown redis! total time: "+ (System.currentTimeMillis()-s));
        client.shutdown();

        }
    }

`
**Lock and Unlock Task:**

`
public class RedissonTask implements Callable
{
    String lockKey;
    long startTime;
    RLock lock;

    public Object call() throws Exception {
        String pp = "key_"+UUID.randomUUID().toString();
        lock = TestRedisson.client.getLock(pp);
        long startTime = System.currentTimeMillis();
        try {

            if(!lock.tryLock(1000 ,1000, TimeUnit.MILLISECONDS)){
                System.err.println("Failed to get lock in time ");
                return "ERROR";
            }
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        if((System.currentTimeMillis() -startTime)>500){
            System.err.println("took to long to get key "+ (System.currentTimeMillis() -startTime));
        }

        if (lock != null && lock.isHeldByCurrentThread()) {

            long unlockTime = System.currentTimeMillis();
            lock.unlock();
            if((System.currentTimeMillis() -unlockTime)>700){
                System.err.println("took to long to UNLOCK key "+ (System.currentTimeMillis() -startTime));
            }
        }
        return "OK";
    }

    }
`

**Comment by mrniko** [comment]
Try to change your GC to Concurrent Mark Sweep with Serial collector for young gen. Add those params to JVM: -XX:+UseConcMarkSweepGC -XX:-UseParNewGC

**Comment by yuvalamar** [comment]
I am already using those parameters on my load system

**Comment by mrniko** [comment]
I see the problem in GC pauses

**Comment by yuvalamar** [comment]
are you using this jvm param ?   
MaxGCPauseMillis

**Comment by mrniko** [comment]
This doesn't help

**Comment by mrniko** [comment]
Could you check please, do you really use UseParNewGC with minus? -XX:-UseParNewGC

**Comment by yuvalamar** [comment]
This is my full vm params config ( I am using Wrapper service to run my app)

When you run it on your system with -XX:-UseParNewGC , does it solve the problem?


wrapper.java.additional.4=-XX:NewRatio=5
wrapper.java.additional.5=-XX:SurvivorRatio=6
wrapper.java.additional.6=-XX:MaxTenuringThreshold=4
wrapper.java.additional.7=-XX:CMSInitiatingOccupancyFraction=30
wrapper.java.additional.8=-XX:+UseCMSInitiatingOccupancyOnly
wrapper.java.additional.9=-XX:+DisableExplicitGC
wrapper.java.additional.10=-XX:+UseConcMarkSweepGC
wrapper.java.additional.11=-XX:+CMSClassUnloadingEnabled
**wrapper.java.additional.12=-XX:+UseParNewGC**
wrapper.java.additional.13=-XX:+CMSConcurrentMTEnabled
wrapper.java.additional.14=-XX:ParallelGCThreads=13
wrapper.java.additional.15=-XX:MaxGCPauseMillis=100
#wrapper.java.additional.16=-XX:+CMSParallelRemarkEnabled

**Comment by mrniko** [comment]
with -XX:+UseParNewGC I have 1000ms delay, with -XX:-UseParNewGC I have ~200ms delay

**Comment by mrniko** [comment]
I know it's not a solution. I'm on the way to find out it

**Comment by yuvalamar** [comment]
Thanks for your help :)
I did not understand which GC config are you using to ger ~200ms  , you wrote :  
with -XX:+**UseParNewGC**   I have 1000ms delay, with -XX:-**UseParNewGC**  I have ~200ms delay

Can you please  provide me with  your full JVM params so I can  run my system on the same setup (GC , heap size ,Ratio ...)

**Comment by mrniko** [comment]
There is only two params which I wrote before.

**Comment by mrniko** [comment]
Does it help?

**Comment by mrniko** [comment]
Here is my workaround. Call it before running your test, to warmup the redisson.
```java
redisson.getNodesGroup().pingAll();
```
Use follow jvm params: 
```
-server -XX:+UseConcMarkSweepGC -XX:-UseParNewGC -XX:MaxNewSize=30m
```
Anyway, depends on your application memory consumption play and memory amount play with `-XX:MaxNewSize` param or `-XX:NewRatio`

**Comment by yuvalamar** [comment]
I will try your config when I get access to the load system(in 1-2 days) and update if the workaround works on my system.
But I think those JVM params combination (-XX:+UseConcMarkSweepGC -XX:-UseParNewGC)
is **deprecated** in java 8 (http://www.oracle.com/technetwork/java/javase/8-compatibility-guide-2156366.html#A1000033)
I will try to play with the generation size  as you proposed.
Did you try to use he UseG1GC  flag instead of  UseConcMarkSweepGC  ?

**Comment by mrniko** [comment]
Try those params for G1GC: `-server -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1MaxNewSizePercent=5`

**Comment by yuvalamar** [comment]
The GC params  did not solve the problem :( 
Also when I profile the app I see that " io.netty.channel.nio.NioEventLoop.select()"
method takes a lot of cpu and thare is about 40 thread called "nioEventLoopGroup" and the all of the threads always RUNNABLE
`"nioEventLoopGroup-2-48" prio=10 tid=0x0000000005950800 nid=0x1b62 runnable [0x00007fee9ee13000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
	- locked <0x000000071aacb800> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x000000071aac2858> (a java.util.Collections$UnmodifiableSet)
	- locked <0x000000071aac2c20> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:639)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:325)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
`
Could it be related?

**Comment by mrniko** [comment]
Have you tried to switch from epoll selector?

**Comment by yuvalamar** [comment]
How do I  switch from epoll selector?

**Comment by mrniko** [comment]
You can try `useLinuxNativeEpoll` option

**Comment by yuvalamar** [comment]
Any update?

**Comment by mrniko** [comment]
Have you tried a netty-transport-native-epoll?

**Comment by yuvalamar** [comment]
I am having problems adding netty to  java.library.path
As I understand the useLinuxNativeEpoll can help to cpu usage and not to lock delay (GC problem)
Do you think you can find a solution for the lock delay ?

**Comment by mrniko** [comment]
I need to profile application to understand the cause. In my tests this problem tied with GC settings. you can also add `-verbose:gc` to see does this affect it your application?

**Comment by mrniko** [comment]
Also try to set `setSlaveSubscriptionConnectionPoolSize` param to 100 or more

**Comment by yuvalamar** [comment]
no change with setSlaveSubscriptionConnectionPoolSize  param :(

**Comment by mrniko** [comment]
> Here is my workaround. Add this code before your test code, to warmup the redisson:
redisson.getNodesGroup().pingAll();

DId you try it?

**Comment by mrniko** [comment]
I have just run [your code](https://github.com/mrniko/redisson/issues/486#issuecomment-217698896)

My output is:
```
true
GO
done 310
Shutdown redis! total time: 25230
```

**Comment by mrniko** [comment]
@yuvalamar Fixed. Please check

**Comment by yuvalamar** [comment]
Thanks  :) ,  I will check and update.
