### ISSUE TITLE
RedissonRemoteService: executorsAmount vs invokeMethod

### ISSUE THREAD

**Issue by pierredavidbelanger** [mrniko/redisson#493]
This is more a question than an issue, and please excuse me if this is a dumb question, I may be wrong, I am just beginning to dig into the code.

Here I suppose that the clients are able to issue calls more quickly that the servers can respond to.

In [RedissonRemoteService](https://github.com/mrniko/redisson/blob/redisson-2.2.13/src/main/java/org/redisson/RedissonRemoteService.java), is it possible that the server ends up [invoking](https://github.com/mrniko/redisson/blob/redisson-2.2.13/src/main/java/org/redisson/RedissonRemoteService.java#L129) simultaneously more than the expected [executorsAmount](https://github.com/mrniko/redisson/blob/redisson-2.2.13/src/main/java/org/redisson/RedissonRemoteService.java#L70) given that it re-[subscribe](https://github.com/mrniko/redisson/blob/redisson-2.2.13/src/main/java/org/redisson/RedissonRemoteService.java#L101) before the [invokeMethod](https://github.com/mrniko/redisson/blob/redisson-2.2.13/src/main/java/org/redisson/RedissonRemoteService.java#L121), and even before the [ack](https://github.com/mrniko/redisson/blob/redisson-2.2.13/src/main/java/org/redisson/RedissonRemoteService.java#L112) ?

**Comment by mrniko** [comment]
Hi!

`invokeMethod` can be concurrently called not more than `executorsAmount`. Because request object can be taken only one time from queue.

**Comment by pierredavidbelanger** [comment]
I am sorry, I do not understand your answer.

Here is an simple example for what I was trying to explain:

You have only one server that exposes a service like that:
```java
int executorsAmount = 1;
Redisson.create().getRemoteSerivce()
    .register(RemoteInterface.class, new RemoteImpl(), executorsAmount);
```

In `RemoteImpl`, the `timeoutMethod` method is defined like that:
```java
public void timeoutMethod() throws InterruptedException {
    Thread.sleep(2000);
}
```

Then, you have 10 clients (differents threads, JVMs or even machines) that calls **simultaneously** the service like that:

```java
Redisson.create().getRemoteSerivce()
    ..get(RemoteInterface.class).timeoutMethod();
```

In my limited understanding of the code, if the above scenario executes, the server will ends up with 10 threads sleeping in the `timeoutMethod`.

Maybe the problem here is that I do not understand what is the use for `executorsAmount` :) I guess I think I see the `executorsAmount` as a way to throttle the server ...

**Comment by mrniko** [comment]
You defined `int executorsAmount = 1;` so only one invocation could be processed simultaneously.

> In my limited understanding of the code, if the above scenario executes, the server will ends up with 10 threads sleeping in the timeoutMethod.

In this case 1 task will be processed and 9 other calls will be in requests queue.

**Comment by mrniko** [comment]
Did I answer to your question?

**Comment by pierredavidbelanger** [comment]
Sure.
I understand that the `executorsAmount ` should work as I expect.

I will try to familiarise myself more with the code now.

Thank you.
