### ISSUE TITLE
RedissonRemoteService ideas

### ISSUE THREAD

**Issue by pierredavidbelanger** [mrniko/redisson#494]
Here, two things that would be great additions (I think) to the RedissonRemoteService.

**1) Be able to choose the remote service interface prefix**

Right now its hardcoded to `redisson_remote_service:`. 

The use case is simple: for example I want to be able to deploy the same worker application (that expose the same service) on two types of instances (say some AWS m3-* for standard use, and some c4-* for hardcore use).

So on the server side I would call:
```java
String servicePrefix = System.getProperty("SERVICE_PREFIX"); // whatever where this come from
RRemoteService remoteService = client.getRemoteSerivce(servicePrefix);
remoteService.register(...) // as usual
```

And on the client side:
```java
String servicePrefix = /* whatever code that decide if its a standard call or an hardcore one */;
RRemoteService remoteService = client.getRemoteSerivce(servicePrefix);
remoteService.get(...) // as usual
```

**2) Be able to issue one-way call (ie: wait for the ack, but not the actual response)**

This could be a client side only change, for example, by having a new set of `RRemoteService.get(...)` methods, that takes a `boolean waitForResponse`...

Or, maybe, re-use the `RRemoteService.get(...)`'s `long executionTimeout`, where a value of `executionTimeout < 0` would indicate to the client to wait for the ack, but not the actual response.

**Comment by pierredavidbelanger** [comment]
point 1 was not to hard to [code](https://github.com/pierredavidbelanger/redisson/commit/b49364eee6cf6c9f73d7402861844cfcd5d46183).

I can create the PR if you want.

**Comment by mrniko** [comment]
> I can create the PR if you want.

:+1: I want :)

**Comment by mrniko** [comment]
I would like to implement an asynchronous way of RemoteService object methods invocations. Need to think about it more deeply

**Comment by jackygurui** [comment]
> I would like to implement an asynchronous way of RemoteService object methods invocations. Need to think about it more deeply

**Comment by pierredavidbelanger** [comment]
@mrniko Yeah, my point 2 is more like, as @jackygurui suggested, a fire and forget.

But asynchronous RemoteService would be great too, though I do not know how one would implements this. 

A thought: if the client side detect that the a service interface method has a return value class `Future` , it then could magically switch in async mode.

So the programmer that make the interface can choose which methods he would like to be asynchronous:

```java
public interface Greeter {

    String greet(String name);

    Future<String> greetAsync(String name);

}
```

**Comment by mrniko** [comment]
I think to start from implementation of async calls support. I suggest follow way to make it.

We have some interface:
```java
public interface MyService {
     String someMethod1(String name);
     String someMethod2(String name);
}
```
To make an async call of `someMethod1` method all you need is to create an interface which repeats those methods which need to be called in async way.
```java
public interface MyServiceAsync {
     Future<String> someMethod1(String name);
}
```

and finally get those methods:
```java
MyServiceAsync asyncService = remoteService.getAsync(MyService.class, MyServiceAsync.class);
```
The reason why `MyService.class` is required because we need to check methods signature matching.

What do you think? @jackygurui @pierredavidbelanger

**Comment by pierredavidbelanger** [comment]
One thing I see:

With your suggestion, given that one would not be able to do something like that (because of the incompatible return type):

```java
public class MyServiceImpl implements MyService, MyServiceAsync {}
```

this will make refactoring harder (or code harder to follow).

Imagine changing a signature in `MyService`  but not in `MyServiceAsync` 

```java
public interface MyService {
     String someMethod1Renamed(String name);
     String someMethod2(String name);
}
public interface MyServiceAsync {
     Future<String> someMethod1(String name);
}
```

This will make the code compile, execute, but fail at runtime when `MyServiceAsync.someMethod1` is called.

**Comment by mrniko** [comment]
> This will make the code compile, execute, but fail at runtime when MyServiceAsync.someMethod1 is called.

Redisson will check it during `get()` operation invocation

**Comment by jackygurui** [comment]
This is what I am thinking:
```
public class MyClass {
      String someMethod1(String name);
      String someMethod2(String name);
      void someMethod3();
}

RRemoteService remoteService = redisson.getRemoteSerivce();
remoteService.register(MyClass.class);
MyClass instance = remoteService.get(MyClass.class)
remoteService.registerAsyncExec(instance, "someMethod2", new FutureListener<String>() {
            @Override
            public void operationComplete(Future< String > future) throws Exception {
               
            }
        });

remoteService.registerAsyncExec(instance, "someMethod3", new FutureListener<Void>() {
            @Override
            public void operationComplete(Future< Void > future) throws Exception {
               
            }
        });
```

Now calling someMethod2 and someMethod3 will return straight away, with null or void.

**Comment by pierredavidbelanger** [comment]
What do you think of something like that:

```java

RRemoteService remoteService = Redisson.create().getRemoteSerivce();

RRemoteServiceAsync<MyClass> myClassAsync = remoteService.getAsync(MyClass.class);

myClassAsync.with(new FutureListener<String>() {
    @Override
    public void operationComplete(Future<String> future) throws Exception {
        String result = future.get();
    }
}).someMethod1("HelloWorld");
```

**Comment by jackygurui** [comment]
All method future goes to the same listener?

**Comment by pierredavidbelanger** [comment]
In my last snippet, yeah, indeed, one should not re-use the return value of `myClassAsync.with(...)`, or else, every invocation future will be listened by the same `FutureListener`.

If one want to call many methods, he would have to do this:

```java
myClassAsync.with(new FutureListener<String>() {
    @Override
    public void operationComplete(Future<String> future) throws Exception {
        String result1 = future.get();
    }
}).someMethod1("HelloWorld");

myClassAsync.with(new FutureListener<String>() {
    @Override
    public void operationComplete(Future<String> future) throws Exception {
        String result2 = future.get();
    }
}). someMethod2("HelloWorld");
```

**Comment by pierredavidbelanger** [comment]
With my suggestion, you will need to introduce in the API:

This new signature in `RRemoteService`:
```java
<T> RRemoteServiceAsync<T> getAsync(Class<T> remoteInterface);
```

And this new class:
```java
public interface RRemoteServiceAsync<T> {
    T with(FutureListener futureListener);
}
```

**Comment by jackygurui** [comment]
The problem is you effectively have two independent instances. Not going to be suitable for every case.

How about this as a compromise:
```
myClassAsyncBuilder.with("someMethod1", new FutureListener<String>() {
    @Override
    public void operationComplete(Future<String> future) throws Exception {
        String result1 = future.get();
    }
});

myClassAsyncBuilder.with(new FutureListener<String>() {
    @Override
    public void operationComplete(Future<String> future) throws Exception {
        String result2 = future.get();
    }
});

MyClass myClass = myClassAsyncBuilder.build();
myClass.someMethod1("HelloWorld"); //returns null immediately
myClass.someMethod2("HelloMe"); //returns null immediately

```

**Comment by jackygurui** [comment]
Maybe we can have both? 

Have to say your proposal is neater than mine, since you don't have to mess with method names in string format.

**Comment by pierredavidbelanger** [comment]
I like the idea of a builder to register multiple listeners 👍 

But I am not a fan of hardcoding method name as string.

This is what I was trying to escape with my suggestion.

**Comment by jackygurui** [comment]
Totally understand, your concern.

My worry is people can forget to swap instances:

```
MyClass mc1 = myClassAsync.with(new FutureListener<String>() {
    @Override
    public void operationComplete(Future<String> future) throws Exception {
        String result1 = future.get();
    }
});
MyClass mc2 = myClassAsync.with(new FutureListener<String>() {
    @Override
    public void operationComplete(Future<String> future) throws Exception {
        String result2 = future.get();
    }
})

mc1.someMethod1("HelloWorld"); 
mc1.someMethod1("HelloWorld"); 
mc1.someMethod1("HelloWorld"); 
mc1.someMethod1("HelloWorld"); 
mc1.someMethod1("HelloWorld"); 
mc2.someMethod2("HelloMe"); 
mc2.someMethod2("HelloMe"); 
mc1.someMethod1("HelloWorld"); 
mc2.someMethod2("HelloMe"); 
mc2.someMethod2("HelloMe"); 
mc1.someMethod1("HelloWorld"); 
mc2.someMethod2("HelloMe"); 
mc1.someMethod1("HelloWorld"); 
mc2.someMethod2("HelloMe"); 
mc2.someMethod2("HelloMe"); 
mc1.someMethod1("HelloWorld"); 
mc1.someMethod2("HelloMe"); // oops !!
```

**Comment by jackygurui** [comment]
And imaging you have this situation:
```
public void doSomeStuff(MyClass mc) {
    mc.someMethod1("HelloWorld");
    mc.someMethod2("HelloMe");
    mc.someMethod3("Hello3");
    mc.someMethod4("Hello4");
    mc.someMethod5("Hello5");
}
```

It will end up like this: 
```
public void doSomeStuff(MyClass mc1, MyClass mc2, MyClass mc3, MyClass mc4, MyClass mc5, ) {
    mc1.someMethod1("HelloWorld");
    mc2.someMethod2("HelloMe");
    mc3.someMethod3("Hello3");
    mc4.someMethod4("Hello4");
    mc5.someMethod5("Hello5");
}
```

That does not look very neat any more.

**Comment by pierredavidbelanger** [comment]
Yeah, this is a very good point.. 

I guess, with my suggestion, one would need to pass around the `RRemoteServiceAsync<MyClass>` instance, instead. And this will be no more neat nor convenient than your last `doSomeStuff ` method ..

I dont know .. this is puzzling me.
I will leave this problem to others :) 

Anyway, in my applications, I like to control the client side thread pool, so I will not be the one using this async remote service feature anyways.

I will probably end up doing things in the old (not Redisson managed) way:

```java
ExecutorService executorService = ...;
MyClass myClass = redisson.getRemoteSerivce().get(MyClass.class);
Future future = executorService.submit(() -> myClass. someMethod1("HelloWorld"));
```

**Comment by mrniko** [comment]
> I will probably end up doing things in the old (not Redisson managed) way

And get a thread busy per call?

**Comment by pierredavidbelanger** [comment]
@mrniko indeed, with this method I will lose the great Netty nio features ..

**Comment by jackygurui** [comment]
It is a shame that in java you can't subclass a final class. This wouldn't be an issue if it could. You could just return a subclass that implements Future.

**Comment by mrniko** [comment]
> can't subclass a final class.

I guess you can remove it via reflection

**Comment by pierredavidbelanger** [comment]
Also, I think you can create such a proxy:
```java
Object returnValue = Proxy.newProxyInstance(classLoader, 
        new Class[] {method.getReturnType(), Future.class}, 
        handler);
```

The `handler` will need to know about that though.

Also, the user will need to cast :
```java
MyClass myClass = redisson.getRemoteSerivce().get(MyClass.class);
String result = myClass.someMethod1();
Future resultFuture = (Future) result;
```

Is this something you had in mind @jackygurui  ?

**Comment by mrniko** [comment]
Why we can't do it like [Jackson MixIn's](http://wiki.fasterxml.com/JacksonMixInAnnotations)?

**Comment by pierredavidbelanger** [comment]
@mrniko so, something like your first proposal :

```java
public interface MyService {
     String someMethod1(String name);
     String someMethod2(String name);
}

public interface MyServiceAsync {
     Future<String> someMethod1(String name);
}

MyServiceAsync asyncService = remoteService.getAsync(MyService.class, MyServiceAsync.class);
```

The `MyServiceAsync` class act kind of like Jackson mixins.

In retrospect, I like your idea.
I guess you were right from the beginning :)

**Comment by mrniko** [comment]
I can rewrite it in MixIn style:

```java
public interface MyService {
     String someMethod1(String name);
     String someMethod2(String name);
}

@RRemoteMixIn(MyService.class)
public interface MyServiceAsync {
     Future<String> someMethod1(String name);
}

MyServiceAsync asyncService = remoteService.get(MyServiceAsync.class);
```

So you can use usual `get()` method. Redisson will validate MyServiceAsync during `get()` invocation.

**Comment by pierredavidbelanger** [comment]
Very nice 👍 
I like that a lot.

The only drawback (that also exists with Jackson Mixins) is that signatures must match and no IDE can help you.

**Comment by mrniko** [comment]
> The only drawback (that also exists with Jackson Mixins) is that signatures must match and no IDE can help you.

Yep. But it's the only drawback, as I see. And minimalistic solution in terms of coding from user point of view.

**Comment by pierredavidbelanger** [comment]
Also, indeed, Redisson can help the user, during `get()` invocation, by validating that:

if the `remoteInterface` class is annotated with `RRemoteMixIn`, every methods in `remoteInterface` (ie: `MyServiceAsync`) exists with the same parameters in the declared `@RRemoteMixIn`'s value (ie: `MyService`) and returns `Future`.

This way the code will fail fast in dev.

**Comment by mrniko** [comment]
Of course, I suggested that "Redisson will validate MyServiceAsync during get() invocation"

**Comment by mrniko** [comment]
I have just finished async interface support in #513. So I think we have implemented all ideas :)

**Comment by jackygurui** [comment]
Well done. Thank you!
