### ISSUE TITLE
Asynchronous lock release

### ISSUE THREAD

**Issue by avivcortica** [mrniko/redisson#503]
Hi,
I'm trying to create an infrastructure where different machines acquire shared locks through Redisson. Once the lock is acquired, some async tasks gets done, finally, when I finish the job, I'm releasing the Redisson lock through the thread currently running - but i receive the following error

`java.lang.IllegalMonitorStateException: attempt to unlock lock, not locked by current thread by node id: xxxxx thread-id: 57`

So, I understand the meaning of that, but since I want to perform asynchronous work, I cannot use the acquiring thread to perform the release.

Is there a solution for asynchronous programming? Should I not use Redisson Lock?
I also references the issue on [SO](http://stackoverflow.com/questions/37374878/redisson-release-lock-from-different-threads)

Thanks.

**Comment by mrniko** [comment]
Hi!
Lock should released by the same lock it was locked

**Comment by avivcortica** [comment]
Thanks.
Is there any other design pattern in Redisson that can fit my needs? locking and unlocking without validating the thread id?

I'm asking because Redisson seems to have a wide support for async programming, but the async operations in Lock seems to be redundant in this case, let me show you by an example:

```
RLock lock = ...;
Future<Void> future = lock.lockAsync();
future.addListener(ignored -> {
    // here i perform some tasks, and when i'm done, i call lock.unlockAsync() or lock.unlock()
    // the problem is, that since this whole block is a callback for the finish of the future,
    // the thread running it is a Redisson thread in this case, or any other thread if i keep
    // performing async operations here. I this case it is highly in effective at best, or even
    // impossible to find the original locking thread to perform the unlocking
});
```

**Comment by avivcortica** [comment]
PS, I'm thinking about allocating a single thread to handle all the locking and unlocking, since everything inside is non-blocking it could be done and actually be quite effective, but, it seems to me like not what you intended in the first place, and also expose some maintenance overhead, so i wanted to check what in your opinion is the proper way to do it.

Thanks again.

**Comment by mrniko** [comment]
> but the async operations in Lock seems to be redundant in this case

I think async version of RSemaphore can satisfy your needs, but it's not implemented yet.

**Comment by avivcortica** [comment]
OK thanks, i'll keep following
