### ISSUE TITLE
FstCodec: FSTObjectOutput proper usage

### ISSUE THREAD

**Issue by pierredavidbelanger** [mrniko/redisson#505]
Juste a little something.

In the `FstCodec`, when an object in encoded, an `FSTObjectOutput` is first borrowed from the `FSTConfiguration`, then used to write the object and then [closed](https://github.com/mrniko/redisson/blob/master/src/main/java/org/redisson/codec/FstCodec.java#L75).

In the FST Serialization [Recommended threadsafe Use](https://github.com/RuedigerMoeller/fast-serialization/wiki/Serialization#recommended-threadsafe-use), they recommend, when using the factory method, not closing this stream in order for it to be reused.

I think that only an `oos.flush()` instead of a `oos.close()` will do the job here.

Not a big deal, but still....

**Comment by mrniko** [comment]
My mistake. Thank you!
