### ISSUE TITLE
RedissonSortedSet's order seems broken

### ISSUE THREAD

**Issue by fransiskusx** [mrniko/redisson#514]
Hi, we have been using RedissonSortedSet and just found that on certain cases the order can be broken and I assume RedissonSortedSet is supposedly thread safe.

Assuming RedissonSortedSet of integers are added with the following integers : 103, 101, 102. RedissonSortedSet state (list in the redis server) should be: 101, 102, 103. However, there are cases when it is not. It may become 102, 101, 103 instead. And looking at RedissonSortedSet's source code, it uses binary search that requires the list/state to be always sorted. Therefore it breaks many other functionality.

The use case that breaks (in my case) is when we are adding multiple items and there is another thread that delete an item in between. Looking the source code implementation briefly, it may be because when removing an item it does not consider getCurrentVersion() (just a quick guess).

**Comment by mrniko** [comment]
I have just reviewed a `RedissonSortedSet.remove` source. There is a bug LRANGE defined before `MULTI` command. So it's not participate in transaction.

**Comment by mrniko** [comment]
Fixed

**Comment by fransiskusx** [comment]
thanks for the quick response. when will 2.2.15 be deployed?

**Comment by mrniko** [comment]
At Friday

**Comment by mrniko** [comment]
I add `ConcurrentRedissonSortedSetTest.testAddRemove_SingleInstance` test for your case. But found NPE instead of broken order. Now it's fixed.

**Comment by SandyKarunia** [comment]
@mrniko why do you implement sorted set using list instead of redis sorted set (http://redis.io/commands/#sorted_set)?

**Comment by mrniko** [comment]
@SandyKarunia because it uses comparator

**Comment by mrniko** [comment]
@fransiskusx did you try master branch version?

**Comment by fransiskusx** [comment]
tried but could not get it properly running. I ran "mvn deploy" and used the exported jars. However, i got java.lang.NoClassDefFoundError: io/netty/buffer/ByteBufInputStream

I might be missing some steps

**Comment by mrniko** [comment]
@fransiskusx I think you missed netty lib in classpath

**Comment by fransiskusx** [comment]
should not it already be included in redisson source code pom.xml? And when i mvn deploy should be part of the jar?

**Comment by mrniko** [comment]
@fransiskusx no, it's just a dependency like other libs.

**Comment by fransiskusx** [comment]
maybe adding the dependency requirement on the readme?

btw i tested it out with master code base and it seems the new change fixed the sorting problem

**Comment by mrniko** [comment]
I supposed you'll use maven to build it. Thank you
