### ISSUE TITLE
RKeys.getKeysByPattern infinite scan when no keys are present

### ISSUE THREAD

**Issue by ursbrbalaji** [mrniko/redisson#515]
After updating to version 2.2.14 RKeys.getKeysByPattern is doing infinite scans when there is not even 1 key by this pattern. It was working fine earlier.
 
1464601787.027739 [0 127.0.0.1:53406] "SCAN" "14" "MATCH" "XXX_*"
1464601787.027892 [0 127.0.0.1:53405] "SCAN" "0" "MATCH" "XXX_*"
1464601787.028022 [0 127.0.0.1:53401] "SCAN" "14" "MATCH" "XXX_*"
1464601787.028161 [0 127.0.0.1:53402] "SCAN" "0" "MATCH" "XXX_*"
1464601787.028317 [0 127.0.0.1:53407] "SCAN" "14" "MATCH" "XXX_*"
1464601787.028456 [0 127.0.0.1:53406] "SCAN" "0" "MATCH" "XXX_*"
1464601787.028631 [0 127.0.0.1:53405] "SCAN" "14" "MATCH" "XXX_*"
1464601787.028775 [0 127.0.0.1:53401] "SCAN" "0" "MATCH" "XXX_*"
1464601787.028944 [0 127.0.0.1:53402] "SCAN" "14" "MATCH" "XXX_*"
1464601787.029096 [0 127.0.0.1:53407] "SCAN" "0" "MATCH" "XXX_*"
1464601787.029262 [0 127.0.0.1:53406] "SCAN" "14" "MATCH" "XXX_*"

It works fine when there is at least 1 key with this pattern

**Comment by mrniko** [comment]
Can't reproduce it. Could you provide a test case?

**Comment by ursbrbalaji** [comment]
redis version 2.8.4, redisson version 2.2.14

The function never returns after we call  redisson.getKeys().getKeysByPattern("test?").iterator().

public void testKeysIterablePatternForEmpty() {
        Iterator<String> iterator = redisson.getKeys().getKeysByPattern("test?").iterator();
        if (!iterator.hasNext()) {
            System.out.println("Correct");
        }else{
        	System.out.println("Fail");
        }
    }

If you check redis-cli monitor it will be doing infinite scans as below:

1464662341.843608 [0 127.0.0.1:35974] "SCAN" "0" "MATCH" "test?"
1464662341.843755 [0 127.0.0.1:35972] "SCAN" "30" "MATCH" "test?"
1464662341.843906 [0 127.0.0.1:35969] "SCAN" "0" "MATCH" "test?"
1464662341.844015 [0 127.0.0.1:35973] "SCAN" "30" "MATCH" "test?"
1464662341.844161 [0 127.0.0.1:35970] "SCAN" "0" "MATCH" "test?"
1464662341.844312 [0 127.0.0.1:35974] "SCAN" "30" "MATCH" "test?"
1464662341.844438 [0 127.0.0.1:35972] "SCAN" "0" "MATCH" "test?"
1464662341.844577 [0 127.0.0.1:35969] "SCAN" "30" "MATCH" "test?"
1464662341.844677 [0 127.0.0.1:35973] "SCAN" "0" "MATCH" "test?"
1464662341.844809 [0 127.0.0.1:35970] "SCAN" "30" "MATCH" "test?"
1464662341.844948 [0 127.0.0.1:35974] "SCAN" "0" "MATCH" "test?"
1464662341.845070 [0 127.0.0.1:35972] "SCAN" "30" "MATCH" "test?"
1464662341.845196 [0 127.0.0.1:35969] "SCAN" "0" "MATCH" "test?"
1464662341.845312 [0 127.0.0.1:35973] "SCAN" "30" "MATCH" "test?"
1464662341.845437 [0 127.0.0.1:35970] "SCAN" "0" "MATCH" "test?"
1464662341.846069 [0 127.0.0.1:35974] "SCAN" "30" "MATCH" "test?"
1464662341.846846 [0 127.0.0.1:35972] "SCAN" "0" "MATCH" "test?"

Let me know if you require more info.

**Comment by mrniko** [comment]
Still can't reproduce. Could you tell me what does SCAN command return?

**Comment by ursbrbalaji** [comment]
127.0.0.1:6379> scan 0 match test?
1) "17"
2) (empty list or set)
127.0.0.1:6379> scan 17 match test?
1) "0"
2) (empty list or set)
127.0.0.1:6379>

**Comment by mrniko** [comment]
Which Redis connection mode do you use?

**Comment by ursbrbalaji** [comment]
Single Instance Mode
// connecting to 127.0.0.1:6379
Config config = new Config();
config.useSingleServer().setAddress("127.0.0.1:6379");
RedissonClient redisson = Redisson.create(config);

**Comment by mrniko** [comment]
Fixed. Please check it. I haven't checked it because can't reproduce it. But made some change which should resolve this issue.

**Comment by ursbrbalaji** [comment]
Tested working fine with 2.2.15 release
