### ISSUE TITLE
Redisson cannot recover from password protected rebooted redis server

### ISSUE THREAD

**Issue by fransiskusx** [mrniko/redisson#518]
Steps:
1. Redis Server up. 
2. Client is up connecting and connected to Redis Server. It required AUTH password
3. Redis Server down and passed the failedAttemps, so the server is excluded.
4. Redis goes back up
5. Client is trying to reconnect, but the mechanism to check if server is alive is broken for password protected server.

I think the following line of code can be improved by including authentication:
https://github.com/mrniko/redisson/blob/master/src/main/java/org/redisson/connection/pool/ConnectionPool.java#L329

**Comment by fransiskusx** [comment]
I was planning to start a pr but could not get to setup the project

**Comment by mrniko** [comment]
which ide do you use?

**Comment by fransiskusx** [comment]
https://github.com/mrniko/redisson/pull/520

**Comment by fransiskusx** [comment]
@mrniko will 2.2.15 be released today as scheduled? The fixes on that version would be very helpful for us

**Comment by mrniko** [comment]
@fransiskusx I'm waiting for confirmation from author of last issue in 2.2.15 version

**Comment by fransiskusx** [comment]
can we set a time for him to reply? it seems he has not responded since couple days ago. https://github.com/mrniko/redisson/issues/515

**Comment by fransiskusx** [comment]
@mrniko any update?

**Comment by mrniko** [comment]
@fransiskusx I hope to release it during this week
