### ISSUE TITLE
Support for ssdb as a replacement of redis.

### ISSUE THREAD

**Issue by doggie1989** [mrniko/redisson#519]

**Comment by jackygurui** [comment]
SSDB is an interesting contender however it does not support LUA script, as far as I understand. Unfortunately Redisson is heavily depend on this feature for many of its functionalities.

**Comment by doggie1989** [comment]
In some of my case, the memory is so expensive ...How about ardb?

**Comment by jackygurui** [comment]
A quick scan of ardb, I couldn't find any information about supporting LUA script either.

Another important redis feature the Redisson is heavily utilising is the PUB/SUB which is also missing from SSDB and others alike.

**Comment by jackygurui** [comment]
Just out of my interest, what is your use case? How much data are you planning to store in redis or SSDB?

**Comment by doggie1989** [comment]
a very big queue...and a big map...

**Comment by jackygurui** [comment]
Just one queue and one map? (0.0)

I think @mrniko may have a solution for you.

**Comment by doggie1989** [comment]
no...not a queue. a lot of queues.
Maybe 500GB -1000GB..
Currently I am just using BlockingQueue(pointer of s3 key) in redisson and json data in s3...
But I do not want to use kafka for lots of reasons

**Comment by jackygurui** [comment]
What codec are you using at the moment? Have you tried to use Snappy codec?

**Comment by doggie1989** [comment]
I use jdk's...

**Comment by jackygurui** [comment]
You can try the Snappy codec with redisson, this should save you a lot memory space in my own opinion.

Information about the Snappy codec can be found here: https://github.com/google/snappy

**Comment by doggie1989** [comment]
Thanks mate,I will have a try.

**Comment by jackygurui** [comment]
Another interesting question, what is your average number of items/entries in a queue or a map in your use case?

**Comment by doggie1989** [comment]
queue size is around 1000w, producer rate is around 2000/s, consumer rate is around 500/s depends on networking, it's a email sending system.

**Comment by jackygurui** [comment]
1000w is 10 million right? Is that all in one redis node?

**Comment by mrniko** [comment]
@doggie1989 
> I use jdk

It's better to use FST code rather than JDK due to performance.

**Comment by doggie1989** [comment]
@jackygurui 
Yes,10 million.with per entity size around 200k.

**Comment by jackygurui** [comment]
> producer rate is around 2000/s, consumer rate is around 500/s

> It's better to use FST code rather than JDK due to performance.

I think using FST is going to make his situation worse. It's already too fast for him 😄 

Snappy codec is going to slow it down a little and at the same time saves him a bit memory space.

> Yes,10 million.with per entity size around 200k.

About 2TB memory storage! Looks like you could use some Pro features there. I would go and give @mrniko a nudge. He has kept some gems in his purse as far as I can tell.

**Comment by doggie1989** [comment]
For memory, it is still not cheaper...

**Comment by jackygurui** [comment]
> producer rate is around 2000/s, consumer rate is around 500/s

Money could be better spent on getting consumer rate up, because this looks like it is only going to get bigger.

**Comment by doggie1989** [comment]
the consumer rate depends on lots of things...from 100/s to 500/s,can not be more...

**Comment by mrniko** [comment]
@doggie1989 have you looked to https://github.com/siddontang/ledisdb ?
