### ISSUE TITLE
Storing simple key/value pairs in RMap vs. RBucket

### ISSUE THREAD

**Issue by smigfu** [mrniko/redisson#521]
Sorry for using an issue for my question, but I couldn't find a mailing list to post this question to :)

I am using Redisson to store key/value pairs and was wondering whether it makes more sense to use just plain RBuckets for each pair or a single RMap. I am especially interested in the possibility of sharding these across nodes in a cluster setup (PRO feature?). The key/value pairs are immutable and I would expect a lof of PUTs and DELETEs of them. Any pros and cons?

I do also use a lot of different "types" (around 8) of caches (with different serializations and TTLs). Currently I am using a different redis databases  for each type. This means I have to create a new connection (aka RedisonClient) for each of these. This also means a lot of Threads in the different ThreadPools, though I am already sharing the EventLoopGroup between the instances. Would there be any particular drawback in storing all of these in just one database to avoid the Thread overhead?

Thanks in advance!

**Comment by jackygurui** [comment]
> I am using Redisson to store key/value pairs and was wondering whether it makes more sense to use just plain RBuckets for each pair or a single RMap. I am especially interested in the possibility of sharding these across nodes in a cluster setup (PRO feature?). The key/value pairs are immutable and I would expect a lof of PUTs and DELETEs of them. Any pros and cons?

This question, to be honest, is not directly related to Redisson rather a design decision when you architect your application around Redis itself. Based on [recommendations](http://redis.io/topics/memory-optimization#use-hashes-when-possible) made by the author of Redis, it is advised to use small hashes where possible, and you could use 

> up to 10 times less memory (with 5 time less memory used being the average saving)

The PRO feature will no doubt reduce the design complexity when it comes to sharding 

> I do also use a lot of different "types" (around 8) of caches (with different serializations and TTLs). Currently I am using a different redis databases for each type. This means I have to create a new connection (aka RedisonClient) for each of these. This also means a lot of Threads in the different ThreadPools, though I am already sharing the EventLoopGroup between the instances. Would there be any particular drawback in storing all of these in just one database to avoid the Thread overhead?

You don't need to have 8 different RedissonClient. Redisson objects can be created with different codecs, can you can set TTLs on each separate objects and/or entries if it is a (Map/Set/List)Cache

**Comment by mrniko** [comment]
> I am especially interested in the possibility of sharding these across nodes in a cluster setup (PRO 
feature?).

I think Redisson PRO sharding fits well for your needs. You can easily manage partitions amount in config.

**Comment by smigfu** [comment]
Cool, thanks for your input.
