### ISSUE TITLE
Conflicting setter definitions for property "masterAddress

### ISSUE THREAD

**Issue by narkesn** [mrniko/redisson#526]
Hi,

I am getting below error while creating instance of config through json ObjectMapper.

Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: Conflicting setter definitions for property "masterAddress": org.redisson.MasterSlaveServersConfig#setMasterAddress(1 params) vs org.redisson.MasterSlaveServersConfig#setMasterAddress(1 params)

I tried both yml and json but still facing the same issue with both.

Please let me know, what I am missing in config.

Thanks,
Sid

**Comment by mrniko** [comment]
Hi!

Could you show your config file?

**Comment by narkesn** [comment]
elasticacheServersConfig: 
  idleConnectionTimeout: 10000
  pingTimeout: 1000
  connectTimeout: 1000
  timeout: 1000
  retryAttempts: 3
  retryInterval: 1000
  reconnectionTimeout: 3000
  failedAttempts: 3
  password: null
  subscriptionsPerConnection: 5
  clientName: "GBClient"
  slaveSubscriptionConnectionMinimumIdleSize: 1
  slaveSubscriptionConnectionPoolSize: 25
  slaveConnectionMinimumIdleSize: 5
  slaveConnectionPoolSize: 100
  masterConnectionMinimumIdleSize: 5
  masterConnectionPoolSize: 100
  readMode: "SLAVE"
  nodeAddresses:
  - //host:port
  scanInterval: 1000
  database: 0  

I have appended above config to my dropwizard config yml. I even tried to enclose above config as
config:


For workaround right now I am setting elasticacheServersConfig using reflection.

**Comment by mrniko** [comment]
Is this an yaml format?

**Comment by narkesn** [comment]
yes

**Comment by mrniko** [comment]
Here is a sample of config https://github.com/mrniko/redisson/wiki/2.-configuration#282-master-slave-json-and-yaml-config-format

**Comment by mrniko** [comment]
try it

**Comment by narkesn** [comment]
I have tried from [https://github.com/mrniko/redisson/wiki/2.-configuration/#252-elasticache-json-and-yaml-config-format] .

 I am using elasticache config, but when I dropwizard starts loading yml config, I am getting error for MasterSlaveServersConfig. 

If you want, I can share sample dropwizard code with you.

**Comment by mrniko** [comment]
Let's take a look at your code sample

**Comment by mrniko** [comment]
As I see from your config.xml why did you include `config` and `server` nodes?

**Comment by narkesn** [comment]
Hi Nikita, 

I tried with that and passing elasticacheServersConfig as argument to useElasticacheServers.

That method is deprecated and it creates new instance of elasticacheServersConfig  instead of using method argument.
And server configuration is for dropwizard application. I have appended redis config to same yml file.

Thanks,
Siddheshwar

**Comment by mrniko** [comment]
How did you load config? 
In this manner?
```java
Config config = Config.fromYAML(new File("config.yaml"));  
RedissonClient redisson = Redisson.create(config);
```

**Comment by narkesn** [comment]
Hi,

That was the problem. I was using custom dropwizard's object mapper to parse yml. 
Config.fromYAML(new File("config.yaml")); this works fine.

Thanks for your help.

Regards,
Siddheshwar

**Comment by mrniko** [comment]
@narkesn 
You're welcome!
