### ISSUE TITLE
Local cache for Redission

### ISSUE THREAD

**Issue by Scisaga** [mrniko/redisson#53]
Does redisson support local cache?

For some usage scenario, local read is very heavy, local write is not much, and the delay of data synchronization can be tolerated in seconds. Some configurable cache mechanism could be helpful.

**Comment by kringol** [comment]
Not 100% sure if the feature discussed here is this, but and discussiong looked like it
There are cases were some data is 99% of the times just being read and it's doesn't change very often, and sometimes that data is costly to serialize/deserialize or involves some network traffic that is unnecessary. 
For those cases is usually better to keep a copy of that data locally on the app, to avoid the before mentioned costs. But simple "local cache" solutions like Guava Cache are of course "not in sync" between different app nodes/clients. Solutions like Hazelcast allow to create a memory grid near-cache mode for this case, but you need to add Hazelcast into the mix. 
Of course this can be manually implemented by a combination of Guava Cache and listening/pushing events by Redisson Topics or any Event system solution. But I believe it would be nice for Redisson to provide some sort of out of the box distributed-synced collections using pub-sub events.

**Comment by mrniko** [comment]
@kringol Currently I'm working on this task https://github.com/mrniko/redisson/issues/592

**Comment by mrniko** [comment]
Done

**Comment by kringol** [comment]
Awesome!!
Thanks @mrniko

**Comment by jackygurui** [comment]
@mrniko Great job mate!

**Comment by mrniko** [comment]
@kringol @jackygurui Thank you guys!
