### ISSUE TITLE
Writing to Redis failed without any exception

### ISSUE THREAD

**Issue by nareshsankapellyfkrt** [mrniko/redisson#531]
Hi,

I'm using Redisson version2.1.5. Writing (Synchronously) to Redis has failed without throwing an exception. Is there any known issue?

**Comment by mrniko** [comment]
Hi! You're using very old version. I suggest you to update it to latest 2.2.16 and try again

**Comment by nareshsankapellyfkrt** [comment]
I understand. Version 2.1.5 has been in production for quite some time. I have faced this for the first time. Are there any known issues with 2.1.5?

**Comment by mrniko** [comment]
Here is the full [changelog](https://github.com/mrniko/redisson/blob/master/CHANGELOG.md) of the project. You can find there all resolved issues after 2.1.5 release.
