### ISSUE TITLE
A type based codec for json

### ISSUE THREAD

**Issue by andrejserafim** [mrniko/redisson#532]
The current JacksonJsonCodec embeds the class information into the json payload, therefore coupling the redis data with the java client. 

What do you think about me adding a codec dedicated to a specific type, so we can get away with clean json?

Thanks

**Comment by mrniko** [comment]
Without class information it would be impossible to instantiate an object. Why do you need it?

**Comment by andrejserafim** [comment]
The class information can be supplied either in the json like it is done in the JsonJacksonCodec or during deserialization - `mapper.readValue(bytes, MyClass.class)`. If the codec is created for this specific class only (through a constructor), the json payload doesn't need to carry the class information. My specific use case is an RMap, the class of the values is very well known in this case. Most maps are fairly homogeneous.

I have this working locally for my use case, so my question is would it be useful as part of this library in a more generic sense?

So in bare bones in the codec would look like 

```java
public class JsonJacksonClassCodec<T> extends JsonJacksonCodec {
    private final ObjectMapper mapper;
    private Class<T> valueClass;

    public JsonJacksonClassCodec(Class<T> valueClass) {
        this.valueClass = valueClass;
        this.mapper = initObjectMapper();
    }

    @Override
    public Decoder<Object> getMapValueDecoder() {
        return (buf, state) -> mapper.readValue(new ByteBufInputStream(buf), valueClass);
    }
}
```

And then we can do `Redisson.getMap("map", new JsonJacksonClassCodec<>(MyClass.class));`

Of course serialization would need to be changed to not include the meta information, etc. But this is the basic idea.

**Comment by mrniko** [comment]
I think this class could be useful. Could you make a PR for this feature?

**Comment by andrejserafim** [comment]
Certainly, give me some time to put a proper one together.
