### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by pengfei-xu** [mrniko/redisson#535]
2016-06-23 19:59:45,137 ERROR [nioEventLoopGroup-2-1] io.netty.util.ResourceLeakDetector Slf4JLogger.java:171 error LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 2
#2:
        io.netty.buffer.AdvancedLeakAwareByteBuf.toString(AdvancedLeakAwareByteBuf.java:741)
        org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:212)
        org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:114)
        io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:368)
        io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:243)
        io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:335)
        io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327)
        io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:335)
        io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327)
        io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1336)
        io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:335)
        io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
        io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
        io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:544)
        io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:485)
        io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:399)
        io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:371)
        io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
        io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
        java.lang.Thread.run(Thread.java:745)
#1:
        io.netty.buffer.AdvancedLeakAwareByteBuf.writeBytes(AdvancedLeakAwareByteBuf.java:603)
        io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:827)
        io.netty.handler.codec.ReplayingDecoderByteBuf.readBytes(ReplayingDecoderByteBuf.java:577)
        org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:212)
        org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:114)
        io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:368)
        io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:243)
        io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:335)
        io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327)
        io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:335)
        io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327)
        io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1336)
        io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)

**Comment by jackygurui** [comment]
What version of Redisson are you using?

**Comment by pengfei-xu** [comment]
2.2.16  the lastest version

**Comment by jackygurui** [comment]
Did you get this by switching on the `-Dio.netty.leakDetectionLevel=PARANOID` JVM options?

**Comment by pengfei-xu** [comment]
no   I set it  with    -Dio.netty.leakDetectionLevel = advanced

**Comment by jackygurui** [comment]
Thanks. I can see the same exception with both ADVANCED and PARANOID settings. Need to see if I can find out the cause and solution.

**Comment by jackygurui** [comment]
Tested the fix with PARANOID settings and not observing any of those LEAK messages during a few selected tests which failed before.

**Comment by pengfei-xu** [comment]
Thanks.I will tested the fix to  see whether there will be the same problem !

**Comment by mrniko** [comment]
@jackygurui Thank you a lot! @pengfei-xu we are waiting for your confirmation

**Comment by mrniko** [comment]
@pengfei-xu Sorry I forgot to merge bug fix to master branch. Now you can try it
