### ISSUE TITLE
Scalability of Channels (Pub/Sub)

### ISSUE THREAD

**Issue by pjebs** [mrniko/redisson#539]
I'm building a real-time text based chat program where people can chat with ONLY 1 other person.
Each person can chat with 1 other person, but the aim is they can chat with Many people at once. (i.e. MANY one to one chats with different people). The aim is to have it scaleable, not necessarily to snapchat's level, but enough for 1 City.

I'm just wondering what is more scaleable:

* Having 1 channel for the **entire** application and filtering who the **message is for** and **who sent the message** based on the data encoded in the message

OR

* Having 1 channel for **each** person and all the different people sending messages to that person send their messages through that channel with data encoding **who sent the message**

OR

* Have an individual channel for EACH Chat between 2 people.

OR

* For Option 1 (1 channel for entire app), perhaps an intermediate solution of having 1 channel per city.

I'm wondering what approach is best for Java and Redis. If there is no clear cut answer, what the conditions/criteria are for making the decision.

**Comment by pjebs** [comment]
If option 2, the viability of having 1 subscriber connection listening to all relevant channels rather than a different connection per channel

**Comment by jackygurui** [comment]
Serve one City of people? Lets assume there are N people in a city to enable the to chat with as many as you can on a one to one session, you would have as many as N*(N-1)/2 sessions if I have done my math right. This number could be quite large.

You have to consider how busy the system is going to be, at its busiest times. Of course you won't realistically expecting all of them starting to send message to N-1 people at the same time. You would still need to project a busiest scenario where a lot of people could be sending messages to a number of others in a short period time. This would be a prediction of the maximum message/sec work load, Mps.

The reason I am emphasis this is, when you architecting you application, you need to understand the way redis cluster distributes pub/sub messages from one client to another: As of redis 3.2.1, each pub/sub message is broadcasted to all other cluster node, which may become a bit problem when the Mps is a large number. 

You could consider using blocking queue as an alternative to pub/sub, which can be a better solution for a few good reasons: First, message goes in and out of a blocking queue is happening to just one redis node.  Second, message is sequential and can be persisted. Three, you could even keep a historical log with very little effort by using BRPOPLPUSH command. 

To demonstrate what I mean, lets assume you have a client A and a client B, you then create a blocking queue named `A=>B` as the name suggests it is a queue for A send message to B, A LPUSH to the queue and B can RPOP from it. The same for B send message to A, you may have another queue for `B=>A` .

**Comment by pjebs** [comment]
Thanks @jackygurui 
When someone writes a message, I immediately save to nongod but database.
With blocking queue would each currently logged in subscriber have to continually poll the queue rather than it getting pushed like in pub sub?

**Comment by jackygurui** [comment]
If the queue is empty, a client is blocked on a queue and wait until a message is available. You need to re-block to receive another message. You can have multiple thread to block on the same queue to process message from A to B, for instance, when the Mps rate is very high, and perhaps reduce it down when it is less busy.

**Comment by mrniko** [comment]
Also you should take in account that complexity of publish operation is O(N+M) http://redis.io/commands/publish So as many peoples you have in a chat as heavy publish process will be.
