### ISSUE TITLE
RedissonRedLock.unlock() is using forceUnlockAsync()

### ISSUE THREAD

**Issue by phoebechengz** [mrniko/redisson#542]
RedissonRedlLock overrides unlock() of RedissonMultiLock and it will force to unlock all instances. 
Is it more reasonable to use unlock method of RedissonMultiLock?

**Comment by mrniko** [comment]
According to `Releasing the lock` section of http://redis.io/topics/distlock current RedissonRedlLock.unlock method implemented correctly.

**Comment by phoebechengz** [comment]
In the section Correct implementation with a single instance, it describes the right approach to release a lock. The Redlock algorithm shall use the same release lock approch on all instances.

`Using just DEL is not safe as a client may remove the lock of another client. With the above script instead every lock is “signed” with a random string, so the lock will be removed only if it is still the one that was set by the client trying to remove it.`

**Comment by mrniko** [comment]
Fixed
