### ISSUE TITLE
RedissonLock.isHeldByCurrentThread() doesn't check properly.

### ISSUE THREAD

**Issue by Mavlarn** [mrniko/redisson#545]
I am using RedissonLock in my system.
The lock realted logic in service is like this:
```
    public boolean tryLock(String key, long time, TimeUnit unit) {
        RLock lock = redissonClient.getLock(key);
        try {
            if(lock.tryLock(time, lockExpireSecond, unit)) {
                LOG.debug("Got lock for:{}", key);
                return true;
            } else {
                LOG.debug("Can not get lock for:{}", key);
                return false;
            }
        } catch (InterruptedException e) {
            LOG.error(e.getMessage(), e);
            return false;
        }
    }

    public void unlock(String key) {
        RLock lock = redissonClient.getLock(key);
        if (lock.isHeldByCurrentThread()) {
            LOG.debug("Unlock for:{}", key);
            lock.unlock();
        } else {
            LOG.debug("Not hold lock for:{}", key);
        }
    }
```

But in the log I found:
```
2016-07-04 15:15:39,533 DEBUG [http-nio-18090-exec-2] OrderService: Got lock for:ticket.lock.order.86
2016-07-04 15:15:39,541 DEBUG [http-nio-18090-exec-2] OrderService: Not hold lock for:ticket.lock.order.86
```
I can see the the thread name is same, so the thread got the lock and the thread try to unlock is same thread.   
Is there any problem in my code? Or in the logic of `lock.isHeldByCurrentThread()` ?

**Comment by mrniko** [comment]
I don't see it at first glance. What is the lockExpireSecond and unit? maybe they are too small? Which redis configuration do you use?

**Comment by Mavlarn** [comment]
The expire time is 60 seconds.
From the log I can see the time between the lock and unlock is about 8ms. Is it possible that the duration is too small, and there is some synchronization problem?
I have 2 redis server, 1 master and 1 slave, and run ing sentinel mode.

**Comment by mrniko** [comment]
It seems like slave node didn't get data in time. According redis docs such situation is possible. `However, because Redis uses asynchronous replication it is not possible to ensure the slave actually received a given write, so there is always a window for data loss.` You can set `readMode` to MASTER as workaround.

**Comment by mrniko** [comment]
Fixed
