### ISSUE TITLE
ConnectionListener.onConnect()/onDisconnect() are not invoked when redis server becomes active/inactive.

### ISSUE THREAD

**Issue by Yipei** [mrniko/redisson#547]
I am trying to utilize ConnectionListener to monitor connections to redis servers. The way I add connection listener is pretty similar to the sample code showing in wiki 9.1:
```
NodesGroup nodesGroup = redisson.getNodesGroup();
nodesGroup.addConnectionListener(new ConnectionListener() {
    public void onConnect(InetSocketAddress addr) {
       // Redis server connected
    }
    public void onDisconnect(InetSocketAddress addr) {
       // Redis server disconnected
    }
});
```
The way I test it:
1) start two redis server on port 6379, 6380, let server on port 6380 to be the slave
2) setup and start redis client. I am using ElasticacheServersConfig here.
3) Once all connections are stable, kill redis master server and check output.

However, what I saw is onDisconnect() of my listener is never invoked after I shut down my redis server. If I restart my redis server again, I can see connectionEventHub.fireConnect() is called. But since the check `maps.get(addr) == Status.CONNECTED` always return true, my listener.onConnect() is also not invoked.

Can anybody help explain why this happens? Did I misunderstand what connection listeners should be used for? Thanks in advance.

The version I am using is redisson-2.2.13
Below is the console output after master is down. 
DEBUG [2016-07-05 20:19:31,715] org.redisson.connection.ElasticacheConnectionManager: Current master: //127.0.0.1:6379
DEBUG [2016-07-05 20:19:31,924] org.redisson.client.handler.ConnectionWatchdog: reconnecting RedisConnection@274136027 [redisClient=[addr=/127.0.0.1:6379], channel=[id: 0x767c23f5, 0.0.0.0/0.0.0.0:56141]] to /127.0.0.1:6379 
DEBUG [2016-07-05 20:19:31,925] org.redisson.client.handler.ConnectionWatchdog: reconnecting RedisConnection@315015763 [redisClient=[addr=/127.0.0.1:6379], channel=[id: 0xe02beb0c, 0.0.0.0/0.0.0.0:56145]] to /127.0.0.1:6379 
DEBUG [2016-07-05 20:19:31,925] org.redisson.client.handler.ConnectionWatchdog: reconnecting RedisConnection@37417717 [redisClient=[addr=/127.0.0.1:6379], channel=[id: 0xba92b187, 0.0.0.0/0.0.0.0:56146]] to /127.0.0.1:6379 
DEBUG [2016-07-05 20:19:31,926] org.redisson.client.handler.ConnectionWatchdog: reconnecting RedisConnection@1396687106 [redisClient=[addr=/127.0.0.1:6379], channel=[id: 0x4d0ceba1, 0.0.0.0/0.0.0.0:56143]] to /127.0.0.1:6379 
DEBUG [2016-07-05 20:19:31,926] org.redisson.client.handler.ConnectionWatchdog: reconnecting RedisConnection@1472480975 [redisClient=[addr=/127.0.0.1:6379], channel=[id: 0x3fa13888, 0.0.0.0/0.0.0.0:56144]] to /127.0.0.1:6379 
DEBUG [2016-07-05 20:19:31,926] org.redisson.client.handler.ConnectionWatchdog: reconnecting RedisConnection@505461609 [redisClient=[addr=/127.0.0.1:6379], channel=[id: 0x3e7120a1, 0.0.0.0/0.0.0.0:56142]] to /127.0.0.1:6379 
ERROR [2016-07-05 20:19:32,718] org.redisson.connection.ElasticacheConnectionManager: Command execution timeout for /127.0.0.1:6379
! org.redisson.client.RedisTimeoutException: Command execution timeout for /127.0.0.1:6379
! at org.redisson.client.RedisConnection.await(RedisConnection.java:128) ~[redisson-2.2.13.jar:na]
! at org.redisson.client.RedisConnection.sync(RedisConnection.java:147) ~[redisson-2.2.13.jar:na]
! at org.redisson.connection.ElasticacheConnectionManager$1.run(ElasticacheConnectionManager.java:134) ~[redisson-2.2.13.jar:na]
! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_92]
! at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:126) [netty-all-4.0.34.Final.jar:4.0.34.Final]
! at io.netty.util.concurrent.GlobalEventExecutor$TaskRunner.run(GlobalEventExecutor.java:236) [netty-all-4.0.34.Final.jar:4.0.34.Final]
! at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [netty-all-4.0.34.Final.jar:4.0.34.Final]
! at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92]

**Comment by mrniko** [comment]
Hi!

I think problem at ConnectionEventsHub:60 disconnect method triggered with different `addr`. Could you please debug it?

**Comment by Yipei** [comment]
Hi!
Thanks for helping on this.

I think I found the reason. I add connection listener after the very first `hub.fireConnect()` gets called, which causes first update to `map` is skipped since `listenersMap` was empty. Then when I shutdown my redis server, `maps.replace` in `hub.fireDisconnect` doesn't work because the `addr` is still not included in `map`.

Another question I have is, looks like hub.fireDisconnect() will only be triggered when there is an action requiring a connection to redis server and it's failed? Does it mean if my redisson client only acts as a subscriber in a PUBSUB flow, my connection listener will never get a onDisconnect() callback when redis server is down, unless I send another command to that server? Is it correct?

Thanks!

**Comment by mrniko** [comment]
> I add connection listener after the very first hub.fireConnect() gets called, which causes first update to map is skipped since listenersMap was empty. 
> Does it mean if my redisson client only acts as a subscriber in a PUBSUB flow, my connection listener will never get a onDisconnect() callback when redis server is down, unless I send another command to that server? 

It was a bug. Now it's fixed.

**Comment by mxscho** [comment]
http://stackoverflow.com/questions/40056494/listen-for-redisson-connect-disconnect-or-reconnect

Due to the lack of anyone who is able to help me:
I don't know if this is the right place for this, but could it be that this is somehow also related to my problem?
If not, just ignore it. (However, other answers on SO are also very much appreciated.)
