### ISSUE TITLE
redisson org.redisson.client.RedisException: NOAUTH Authentication required. exception in 2.1.0

### ISSUE THREAD

**Issue by GeoffreyFx** [mrniko/redisson#549]
I got redisson org.redisson.client.RedisException: NOAUTH Authentication required. exception in 2.1.0

exception: org.redisson.client.RedisException: NOAUTH Authentication required.. channel: [id: 0xa6edb1fd, /10.254.60.191:54741 => /10.0.0.43:6367], dubbo version: 2.5.3, current host: 10.254.60.191
org.redisson.client.RedisException: NOAUTH Authentication required.. channel: [id: 0xa6edb1fd, /10.254.60.191:54741 => /10.0.0.43:6367]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:172)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:106)
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:370)

......
exception: org.redisson.client.RedisConnectionClosedException: channel: [id: 0xd1403d09, /10.254.60.191:36526 :> /10.0.0.43:6367] closed, dubbo version: 2.5.3, current host: 10.254.60.191
org.redisson.client.RedisConnectionClosedException: channel: [id: 0xd1403d09, /10.254.60.191:36526 :> /10.0.0.43:6367] closed
        at org.redisson.CommandExecutorService$5.operationComplete(CommandExecutorService.java:378)
        at org.redisson.CommandExecutorService$5.operationComplete(CommandExecutorService.java:373)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:567)
~~~~~~~~~~~~~~~~
My redis is configed to set timeout to 300 (seconds)

The codes I used with Redisson are like this:


in the spring-config.xml, I pass in the redis info:

    <bean id="redissonManager" class="com.wlqq.ms2.util.RedissonManager" init-method="init">
        <property name="pwd" value="${redis_pass_common}"></property>
        <property name="ip" value="${redis_host_common}"></property>
        <property name="port" value="${redis_port_common}"></property>
    </bean>


public class RedissonManager {
    private static final String RAtomicName = "genId_";
    private static Config config = new Config();
    private static Redisson redisson = null;

    private String pwd;
    private String ip;
    private String port;

    public  void init(){
        try {

            config.useSingleServer().setAddress(getIp()+":"+getPort()).setPassword(getPwd());

            redisson = Redisson.create(config);

            RAtomicLong atomicLong = redisson.getAtomicLong(RAtomicName);
            atomicLong.set(1);
        }catch (Exception e){
            e.printStackTrace();
        }
    }

    public static Redisson getRedisson(){
        return redisson;
    }

    /** 获取redis中的原子ID */
    public static Long nextID(){
        RAtomicLong atomicLong = getRedisson().getAtomicLong(RAtomicName);
        atomicLong.incrementAndGet();
        return atomicLong.get();
    }

    public String getPwd() {
        return pwd;
    }

    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    public String getPort() {
        return port;
    }

    public void setPort(String port) {
        this.port = port;
    }

    public String getIp() {
        return ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }
}

public class DistributedRedisLock {
    private static Redisson redisson = RedissonManager.getRedisson();
    private static final String LOCK_TITLE = "redisLock_";

    public static void lock(String lockName){
        String key = LOCK_TITLE + lockName;
        RLock mylock = redisson.getLock(key);
        mylock.lock(2, TimeUnit.SECONDS); //lock提供带timeout参数，timeout结束强制解锁，防止死锁
    }

    public static void unLock(String lockName){
        String key = LOCK_TITLE + lockName;
        RLock mylock = redisson.getLock(key);
        mylock.unlock();
    }
}

When I try to call DistributedRedisLock.lock, it throws the exception described above

**Comment by mrniko** [comment]
There was a lot authentication fixes since 2.1.0 version. Did you try latest version?
