### ISSUE TITLE
Command execution timeout for command

### ISSUE THREAD

**Issue by nareshsankapellyfkrt** [mrniko/redisson#556]
I started getting RedisTimeoutException("Command execution timeout for command") for put operation on RMap. I have been using Redisson in production for 6 months. I'm seeing this exception now. I'm using Sentine mode with the following configuration. 

Timeout : 5s
RetryInterval: 5s
RetryAttempts:5

What could be the reason for it?

**Comment by mrniko** [comment]
Have you checked CPU usage, GC activity, network latency?

**Comment by mrniko** [comment]
Which objects do you use?

**Comment by nareshsankapellyfkrt** [comment]
Redisson version is 2.1.5. I'm using RSet and RList as well. There is no issue with CPU usage (Load average is ~0.3) and GC. I will check if there is any issue with network latency.

**Comment by mrniko** [comment]
I think connection pool regression bug fixed in 2.1.6 could be related to your issue

**Comment by nareshsankapellyfkrt** [comment]
Ok. Can you share the details?

**Comment by mrniko** [comment]
https://github.com/mrniko/redisson/commit/bbef215c11045878cda7440ff7d125d9a5c4f2c1

**Comment by nareshsankapellyfkrt** [comment]
Thanks. Are there any known issues with 2.2.21? What is the latest stable version?

**Comment by mrniko** [comment]
The only known issues is https://github.com/mrniko/redisson/issues/557 but you can easily fix it changing netty version to 4.0.37 until 2.2.22 goes to release.

**Comment by mrniko** [comment]
@nareshsankapellyfkrt  2.2.22 has out

**Comment by nareshsankapellyfkrt** [comment]
Thanks.

**Comment by mrniko** [comment]
@nareshsankapellyfkrt You're welcome!
