### ISSUE TITLE
Redisson map get makes the thread waiting forever

### ISSUE THREAD

**Issue by shaharco** [mrniko/redisson#561]
The map is a regular <Integer, String> map, and by calling a get on some key we see the following thread trace:

`{code}`
"catalina-exec-140" #1291 daemon prio=5 os_prio=0 tid=0x00007fa0f0c21000 nid=0x7977 waiting on condition [0x00007fa0df19a000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x0000000685c35698> (a java.util.concurrent.CountDownLatch$Sync)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
        at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
        at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:93)
        at org.redisson.RedissonObject.get(RedissonObject.java:55)
        at org.redisson.RedissonMap.get(RedissonMap.java:138)
        at com.datorama.core.service.dist.impl.redis.RedisDistributedMapImpl.get(RedisDistributedMapImpl.java:78)

`{code}`

**Comment by mrniko** [comment]
Which Redisson version do you use?

**Comment by shaharco** [comment]
2.2.22

**Comment by mrniko** [comment]
Do you see any errors above in logs?

**Comment by shaharco** [comment]
Above that no. We are having 2 big issues with migration to Reddison - the biggest is we have many timeout exceptions:

`
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (RPUSH) with params: [lower_priority_lz_queue_3, message type = LZ_STAT, Message id = 2777709]
at org.redisson.command.CommandAsyncService$7.run(CommandAsyncService.java:460)
at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:588)
at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:662)
at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:385)
at java.lang.Thread.run(Thread.java:745)
`

The commands varies depending on the action we do. We are having difficulties understanding what are those timeouts. 
The other big issue is thread being stuck on map get or lock that is unlocked.

**Comment by mrniko** [comment]
> We are having difficulties understanding what are those timeouts. 

Those command can't be send during timeout.

**Comment by mrniko** [comment]
Have you try to profile it?

**Comment by shaharco** [comment]
> Those command can't be send during timeout.
I'm not sure i understand what do you mean by 'during timeout'
We didn't try to profile it.
Another exception stuck trace you can see:
`
Exception:
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (EVAL) with params: [local value = redis.call('hget', KEYS[1], ARGV[2]); if value == false then return nil; end; local t, val = struct.unpack('dLc0', value); local expireDate = 92233720368547758; local expireDateScore = redis.call('zscore', KEYS[2], ARGV[2]); if expireDateScore ~= false then expireDate = tonumber(expireDateScore) end; if t ~= 0 then local expireIdle = redis.call('zscore', KEYS[3], ARGV[2]); if expireIdle ~= false then if tonumber(expireIdle) > tonumber(ARGV[1]) then local value = struct.pack('dLc0', t, string.len(val), val); redis.call('hset', KEYS[1], ARGV[2], value); redis.call('zadd', KEYS[3], t + tonumber(ARGV[1]), ARGV[2]); end; expireDate = math.min(expireDate, tonumber(expireIdle)) end; end; if expireDate <= tonumber(ARGV[1]) then return nil; end; return val; , 3, all_users_map, redisson__timeout__set__{all_users_map}, redisson__idle__set__{all_users_map}, 1470037126357, 1544]
at org.redisson.command.CommandAsyncService$7.run(CommandAsyncService.java:460)
at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:588)
at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:662)
at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:385)
at java.lang.Thread.run(Thread.java:745)
`

**Comment by mrniko** [comment]
> I'm not sure i understand what do you mean by 'during timeout'

Each command has timeout = config.retryInterval * config.retryAttempts (ms) During this timeout Redisson tries to send command `config.retryAttempts` attempts. Each attempt occurs after `config.retryInterval`. If command sent successfully it starts to count response timeout `config.timeout` if not it throws an exception like in your case.

**Comment by shaharco** [comment]
So if i understand correctly onfig.retryInterval * config.retryAttempts (ms) is a request timeout and config.timeout is a response timeout? so if we'll increase those params it should help solving the timeouts exceptions?

**Comment by mrniko** [comment]
@shaharco You're right. But default settings should enough

**Comment by shaharco** [comment]
If the default setting should be enough then we have a different problem since we see many timeout exceptions in many different commands. Currently the settings we are working with are:
+  connectTimeout: 3000
+  timeout: 5000
+  retryInterval: 2000
+  reconnectionTimeout: 3000

**Comment by mrniko** [comment]
I reproduced such case only when I has very slow Redis-server and had network latencies.

**Comment by shaharco** [comment]
We have Redis-server that should be very fast (AWS elastic cache and Redis labs) which should also eliminate network latency.

**Comment by mrniko** [comment]
you can try to rise `*ConnectionMinimumIdleSize`

**Comment by shaharco** [comment]
Can you please explain the meaning of this parameter?
Thanks

**Comment by mrniko** [comment]
it's a ready-to-use connections amount which initialized during Redisson start. This leads to absence of need to create connection additional connections in runtime which is expensive in terms of time.

**Comment by shaharco** [comment]
@mrniko does the following error tell you something, or is it the same as above?
`Exception:
java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: org.redisson.client.RedisTimeoutException: Redis server response timeout (5000 ms) occured for command: (EVAL) with params: [local value = redis.call('hget', KEYS[1], ARGV[2]); if value == false then return nil; end; local t, val = struct.unpack('dLc0', value); local expireDate = 92233720368547758; local expireDateScore = redis.call('zscore', KEYS[2], ARGV[2]); if expireDateScore ~= false then expireDate = tonumber(expireDateScore) end; if t ~= 0 then local expireIdle = redis.call('zscore', KEYS[3], ARGV[2]); if expireIdle ~= false then if tonumber(expireIdle) > tonumber(ARGV[1]) then local value = struct.pack('dLc0', t, string.len(val), val); redis.call('hset', KEYS[1], ARGV[2], value); redis.call('zadd', KEYS[3], t + tonumber(ARGV[1]), ARGV[2]); end; expireDate = math.min(expireDate, tonumber(expireIdle)) end; end; if expireDate <= tonumber(ARGV[1]) then return nil; end; return val; , 3, dingo_brand_5284, redisson__timeout__set__{dingo_brand_5284}, redisson__idle__set__{dingo_brand_5284}, 1470050700534, 61642f3c92287392b9101f25ed406ce1] channel: [id: 0x583fd8f1, L:/172.31.12.214:45513 - R:redis.stg.datorama.com/172.31.2.18:6379]
at java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.util.concurrent.FutureTask.get(FutureTask.java:192)
at com.datorama.core.service.process.GoalProcessService.runQueryAndProcessGoal(GoalProcessService.java:126)`

**Comment by mrniko** [comment]
> does the following error tell you something, or is it the same as above?

No it's not the same. Now it's response timeout. Redisson didn't get response during defined timeout.

**Comment by mrniko** [comment]
Timeouts also arises during GC pause on major collection

**Comment by shaharco** [comment]
So increasing the config.timeout can help?

**Comment by mrniko** [comment]
> So increasing the config.timeout can help?
Yes
