### ISSUE TITLE
attempt to unlock lock, not locked by current thread by node id

### ISSUE THREAD

**Issue by sosojustdo** [mrniko/redisson#562]
redisson version:2.2.21
implement code:
public class DistributedLock {
	private static Logger logger = LoggerFactory.getLogger(DistributedLock.class);

	private static Config config = new Config();
	private static RedissonClient redisson = null;

	private static void init() {
		if (redisson == null) {
			config.useSingleServer().setAddress("ip:port");
			redisson = Redisson.create(config);
		}
	}
	
	public static void lock(String key){
		init();

		logger.info("try to lock : " + key);
		try {
			RLock mylock = redisson.getLock(key);

			while (mylock.isLocked()) {
				Thread.sleep(10);
			}

			mylock.lock();
			logger.info("to lock : " + key + " success...");
		} catch (Exception e) {
			logger.warn("DistributedLock lock :" + key + "error:" + e.getMessage());
		}
	}

	public static boolean tryLock(String key) {
		init();

		logger.info("try to lock : " + key);
		try {
			RLock mylock = redisson.getLock(key);

			while (mylock.isLocked()) {
				Thread.sleep(10);
			}

			mylock.lock(10, TimeUnit.SECONDS);// 10s超时
			logger.info("try to lock : " + key + " success...");
			return true;
		} catch (Exception e) {
			logger.warn("DistributedLock try lock :" + key + "error:" + e.getMessage());
			return false;
		}
	}

	public static boolean tryLock(String key, long timeout) {
		init();

		logger.info("try to lock : " + key);
		try {
			RLock mylock = redisson.getLock(key);

			while (mylock.isLocked()) {
				Thread.sleep(10);
			}

			mylock.lock(timeout, TimeUnit.SECONDS);
			logger.info("try to lock : " + key + " success...");
			return true;
		} catch (Exception e) {
			logger.warn("DistributedLock try lock :" + key + "error:" + e.getMessage());
			return false;
		}
	}

	public static void releaseLock(String key) {
		logger.info("try to release lock : " + key);
		RLock mylock = redisson.getLock(key);
		mylock.unlock();
	}
}

test unit code:
public class RedissonLockTest {
	public static void main(String[] args) {
		final String key = "test_lock";
		for(int i=1; i<=5; i++){
			new Thread(new Runnable() {
				public void run() {
					DistributedLock.lock(key);
					System.out.println("当前线程已获取锁:" + Thread.currentThread().getName());
					try {
						Thread.sleep(2000L);
					} catch (InterruptedException e) {
						e.printStackTrace();
					}
					DistributedLock.releaseLock(key);
					System.out.println("当前线程已释放锁:" + Thread.currentThread().getName());
				}
			}).start();
		}
	}
}

redis lock key ttl info(**loop range:20-30 why?)**:
127.0.0.1:6379> ttl test_lock
(integer) 23
127.0.0.1:6379> ttl test_lock
(integer) 21
127.0.0.1:6379> ttl test_lock
(integer) 20
127.0.0.1:6379> ttl test_lock
(integer) 30
127.0.0.1:6379> ttl test_lock
(integer) 29
127.0.0.1:6379> ttl test_lock
(integer) 28
127.0.0.1:6379> ttl test_lock
(integer) 28
127.0.0.1:6379> ttl test_lock
(integer) 27
127.0.0.1:6379> ttl test_lock
(integer) 26
127.0.0.1:6379> ttl test_lock
(integer) 26
127.0.0.1:6379> ttl test_lock
(integer) 25
127.0.0.1:6379> ttl test_lock
(integer) 24
127.0.0.1:6379> ttl test_lock
(integer) 24
127.0.0.1:6379> ttl test_lock
(integer) 23
127.0.0.1:6379> ttl test_lock
(integer) 22
127.0.0.1:6379> ttl test_lock
(integer) 21

**Comment by mrniko** [comment]
Could you please describe your problem?

**Comment by mrniko** [comment]
Redisson uses expiration of lock object by default to avoid "hanged" locks if you use `lock()` method without lease time parameter. This expiration is renewal every 30 seconds by internal scheduler, take a look at `RedissonLock.scheduleExpirationRenewal()`. In your case you're using such `lock` method at DistributedLock:34

**Comment by mrniko** [comment]
Redisson uses expiration of lock object by default to avoid "hanged" locks if you use `lock()` method without lease time parameter. This expiration is renewal every 30 seconds by internal scheduler, take a look at `RedissonLock.scheduleExpirationRenewal()`. In your case you're using such `lock` method at DistributedLock:34 so this behavior is correct

**Comment by sosojustdo** [comment]
@mrniko 
RedissonLockTest  test unit code ,have exception: attempt to unlock lock, not locked by current thread by node id: uuid Thread-15, however lock and unlock method with one thread invoked.

**Comment by mrniko** [comment]
Can't reproduce your problem. Here is my log:
```
[Thread-3] INFO org.redisson.DistributedLock - try to lock : test_lock
[Thread-2] INFO org.redisson.DistributedLock - try to lock : test_lock
[Thread-0] INFO org.redisson.DistributedLock - try to lock : test_lock
[Thread-1] INFO org.redisson.DistributedLock - try to lock : test_lock
[Thread-4] INFO org.redisson.DistributedLock - try to lock : test_lock
tread:Thread-2
[Thread-2] INFO org.redisson.DistributedLock - to lock : test_lock success...
[Thread-2] INFO org.redisson.DistributedLock - try to release lock : test_lock
tread:Thread-2
[Thread-3] INFO org.redisson.DistributedLock - to lock : test_lock success...
tread:Thread-3
[Thread-3] INFO org.redisson.DistributedLock - try to release lock : test_lock
tread:Thread-3
[Thread-4] INFO org.redisson.DistributedLock - to lock : test_lock success...
tread:Thread-4
[Thread-4] INFO org.redisson.DistributedLock - try to release lock : test_lock
tread:Thread-4
[Thread-0] INFO org.redisson.DistributedLock - to lock : test_lock success...
tread:Thread-0
[Thread-0] INFO org.redisson.DistributedLock - try to release lock : test_lock
tread:Thread-0
tread:Thread-1
[Thread-1] INFO org.redisson.DistributedLock - to lock : test_lock success...
[Thread-1] INFO org.redisson.DistributedLock - try to release lock : test_lock
tread:Thread-1
```

**Comment by mrniko** [comment]
@sosojustdo Did you resolve it?

**Comment by daur88** [comment]
@sosojustdo you cannot unlock the lock from other thread. These locks are supposed to be locked and unlocked withing single thread. Try using semaphores.

**Comment by sosojustdo** [comment]
@mrniko, you can add threads, and try run test unit several times, "attempt to unlock lock, not locked by current thread by node id" exception still reproduced.

occasionally, the following exception:
Can't init enough connections amount! Only 0 from 5 were initialized

so I add ConnectionMinimumIdleSize value, config set for:
config.useSingleServer().setAddress("10.144.34.228:6379")
	        .setPassword("myredis")
	        .setConnectionMinimumIdleSize(100)
	        .setConnectionPoolSize(1000)
	        .setConnectTimeout(10);
	        redisson = Redisson.create(config);

**Comment by sosojustdo** [comment]
@daur88 why unlock changed for other thread? 
`public static void lockBySemaphore(String key){
		init();
		logger.info("releaseLock : " + key);
	    try {
	    	RSemaphore semaphore = redisson.getSemaphore(key);
	    	semaphore.acquire();
	        logger.info("releaseLock : " + key + " success...");
	    } catch (Exception e) {
	        logger.warn("DistributedLock lock :" + key + "error:" + e.getMessage());
	    }
	}`

`public static void releaseLockBySemaphore(String key){
		init();
		logger.info("releaseLockBySemaphore : " + key);
	    try {
	    	RSemaphore semaphore = redisson.getSemaphore(key);
	    	semaphore.release();
	        logger.info("releaseLockBySemaphore : " + key + " success...");
	    } catch (Exception e) {
	        logger.warn("DistributedLock lock :" + key + "error:" + e.getMessage());
	    }
	}`

**Comment by sosojustdo** [comment]
@daur88 why unlock changed for other thread? 
I use semaphore.acquire()  replace lock method, and semaphore.release() replace unlock method,
but test unit  forever blocking semaphore.acquire(), How to use semaphore implment distributed lock?

test unit code:
public static void main(String[] args) {
		final String key = "test_lock";
		for (int i = 1; i <= 10; i++) {
			new Thread(new Runnable() {
				public void run() {
					DistributedLock.lockBySemaphore(key);
					//DistributedLock.lock(key);
					System.out.println("thread name:" + Thread.currentThread().getName());
					try {
						Thread.sleep(1000L);
					} catch (InterruptedException e) {
						e.printStackTrace();
					}
					DistributedLock.releaseLockBySemaphore(key);
					//DistributedLock.releaseLock(key);
					System.out.println("thread name:" + Thread.currentThread().getName());
				}
			}).start();
		}
	}

**Comment by sosojustdo** [comment]
@mrniko, "attempt to unlock lock, not locked by current thread by node id"  problem is resolved, due to reason is invoke lock an unlock method for RLock object instance different.

But add more thread item, throw Exception in thread "Thread-50" org.redisson.client.RedisConnectionException: Can't init enough connections amount! Only 53 from 100 were initialized. Server: /ip:6379

public static RedissonClient getRedisson() {
        config.useSingleServer().setAddress("ip:6379")
        .setPassword("myredis")
        .setConnectionMinimumIdleSize(100)
        .setConnectionPoolSize(1000)
        .setConnectTimeout(5000);
        return Redisson.create(config);
}

redis version:3.0.1, redis.conf need optimized timeout config?

**Comment by daur88** [comment]
@sosojustdo there are unit tests, which describe how to use Semaphores. Have a look at https://github.com/mrniko/redisson/blob/master/src/test/java/org/redisson/RedissonSemaphoreTest.java

**Comment by sosojustdo** [comment]
@daur88, yeah! thanks you. howerever  resolved it problem.

**Comment by hermitcai** [comment]
> @mrniko, "attempt to unlock lock, not locked by current thread by node id" problem is resolved, due to reason is invoke lock an unlock method for RLock object instance different.

Haha, I just saw that you re-acquired a lock when you unlocked, so the locked and unlocked instances are different
