### ISSUE TITLE
Help needed with elastic cache configuration

### ISSUE THREAD

**Issue by shaharco** [mrniko/redisson#564]
Hi @mrniko , we are checking the work with AWS elastiCache instead of Redis-labs, and wanted to check if the following parameters seems ok in that case:

`
elasticacheServersConfig:
 idleConnectionTimeout: 10000
 pingTimeout: 1000
 connectTimeout: 1000
 timeout: 600000
 retryAttempts: 3
 retryInterval: 600000
 reconnectionTimeout: 3000
 failedAttempts: 3
 password: null
 subscriptionsPerConnection: 5
 clientName: null
 loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
 slaveSubscriptionConnectionMinimumIdleSize: 1
 slaveSubscriptionConnectionPoolSize: 25
 slaveConnectionMinimumIdleSize: 10
 slaveConnectionPoolSize: 3000
 masterConnectionMinimumIdleSize: 10
 masterConnectionPoolSize: 3000
 readMode: "SLAVE"
 nodeAddresses:

   "<address>"
 scanInterval: 1000
 database: 0
threads: 0
codec: !<org.redisson.codec.KryoCodec> {}
#codec: !<org.redisson.codec.JsonJacksonCodec> {}
useLinuxNativeEpoll: false
eventLoopGroup: null
`

Thanks

**Comment by mrniko** [comment]
Looks good. I might increased `idleConnectionTimeout`. Connection will be closed automatically if it has not been used during this timeout.

**Comment by mrniko** [comment]
@shaharco could you please email me (nkoksharov@redisson.org) ? I have some question for you.
