### ISSUE TITLE
redisson can't subscribe to the slot after fix Redis Cluster PubSub  Scalability Issues

### ISSUE THREAD

**Issue by carlvine500** [mrniko/redisson#572]
redis PubSub Scalability issure: 
[https://github.com/antirez/redis/issues/2672](https://github.com/antirez/redis/issues/2672)
fixed code: 
[https://github.com/slact/redis/commit/905dc012e942a43375da467971e6739f66e684b2](https://github.com/slact/redis/commit/905dc012e942a43375da467971e6739f66e684b2)

after fixed it , redisson can't receive message becauseof following code: 

MasterSlaveConnectionManager.java
```
    private void connect(final Codec codec, final String channelName, final RedisPubSubListener listener,
            final Promise<PubSubConnectionEntry> promise, final PubSubType type) {
        final int slot = 0; // <----------------
        // final int slot = CRC16.crc16(channelName.getBytes()) % MAX_SLOT;
```

**Comment by mrniko** [comment]
Do you have any suggestion how to resolve it?

**Comment by mrniko** [comment]
Fixed
