### ISSUE TITLE
"Command execution timeout" for INFO replication

### ISSUE THREAD

**Issue by someshj1** [mrniko/redisson#576]
Hi @mrniko,

I am getting the `Command execution timeout` when my application comes up. Looks like the first `INFO replication` command is being timed out. Same command I have tried from the command and the same command works well in almost no time. Can you please suggest if there is any such open issue? I am using `2.2.24` of the library. 

Following is the stack trace:

```
Aug 10 09:44:08 ip-<<masked>> docker/589d207f4a55[2574]: 2016-08-10 09:44:08.792 UTC ERROR rid=NA 5 --- [entExecutor-1-1] o.r.c.ElasticacheConnectionManager       : Command execution timeout for <<masked>>.0001.use1.cache.amazonaws.com/<<masked>>:6379
Aug 10 09:44:08 ip-<<masked>> docker/589d207f4a55[2574]: 
Aug 10 09:44:08 ip-<<masked>> docker/589d207f4a55[2574]: org.redisson.client.RedisTimeoutException: Command execution timeout for <<masked>>.use1.cache.amazonaws.com/10.74.44.236:6379
Aug 10 09:44:08 ip-<<masked>> docker/589d207f4a55[2574]: #011at org.redisson.client.RedisConnection.await(RedisConnection.java:127) ~[<<masked>>:0.1.0-SNAPSHOT]
Aug 10 09:44:08 ip-<<masked>> docker/589d207f4a55[2574]: #011at org.redisson.client.RedisConnection.sync(RedisConnection.java:159) ~[<<masked>>:0.1.0-SNAPSHOT]
Aug 10 09:44:08 ip-<<masked>> docker/589d207f4a55[2574]: #011at org.redisson.client.RedisConnection.sync(RedisConnection.java:145) ~[<<masked>>:0.1.0-SNAPSHOT]
Aug 10 09:44:08 ip-<<masked>> docker/589d207f4a55[2574]: #011at org.redisson.connection.ElasticacheConnectionManager$1.run(ElasticacheConnectionManager.java:134) ~[<<masked>>:0.1.0-SNAPSHOT]
Aug 10 09:44:08 ip-<<masked>> docker/589d207f4a55[2574]: #011at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_60]
Aug 10 09:44:08 ip-<<masked>> docker/589d207f4a55[2574]: #011at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:126) [<<masked>>:0.1.0-SNAPSHOT]
Aug 10 09:44:08 ip-<<masked>> docker/589d207f4a55[2574]: #011at io.netty.util.concurrent.GlobalEventExecutor$TaskRunner.run(GlobalEventExecutor.java:237) [<<masked>>:0.1.0-SNAPSHOT]
Aug 10 09:44:08 ip-<<masked>> docker/589d207f4a55[2574]: #011at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) [<<masked>>:0.1.0-SNAPSHOT]
Aug 10 09:44:08 ip-<<masked>> docker/589d207f4a55[2574]: #011at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
```

**Comment by mrniko** [comment]
Hi!

Such timeout occurs due to network delay.

**Comment by someshj1** [comment]
Agreed, but there problem is that network is stable. I tried with running the same command from redis-cli and it works well.

**Comment by mrniko** [comment]
Network delays could happen non permanently. Which timeout settings do you have?

**Comment by Himanshu4** [comment]
@mrniko : We are using the following connection settings to connect to our elastic cache servers. This is coming very frequently. We have found that the command "info replication" gets timedout. Could this be a timeout issue or connection setup issue.

 public RedissonClient redissonClient() {
        Config config = new Config();
        config.useElasticacheServers().setLoadBalancer(new RoundRobinLoadBalancer()).setScanInterval(5000).
                setSlaveSubscriptionConnectionPoolSize(0).setSlaveSubscriptionConnectionMinimumIdleSize(0).setSubscriptionsPerConnection(0).
                setMasterConnectionPoolSize(100).setSlaveConnectionPoolSize(100).
                setSlaveConnectionMinimumIdleSize(10).setMasterConnectionMinimumIdleSize(10).
                setIdleConnectionTimeout(60000).setReconnectionTimeout(30000).
                setReadMode(ReadMode.MASTER_SLAVE).setConnectTimeout(30000).setTimeout(30000).addNodeAddress(redisHostName);
        return Redisson.create(config);
    }

**Comment by mrniko** [comment]
@Himanshu4 

> Could this be a timeout issue or connection setup issue.

I don't think so. ElastiCacheManager uses RedisClient which used by Redisson for connection setup and command execution.

**Comment by mrniko** [comment]
Command timeout = `retryInterval * retryAttempts` Try to increase `retryInterval`. ElastiCacheManager used hardcoded timeout = `60 seconds` before I fixed it to correct timeout calculation formula.
