### ISSUE TITLE
Replace Future interface to RFuture for async methods

### ISSUE THREAD

**Issue by mrniko** [mrniko/redisson#577]

**Comment by techthumb** [comment]
Hi @mrniko 

Can you talk about the motivation to replace `java.util.concurrent.Future` with `RFuture`?

Additionally, if we have an interface that returns either `java.util.concurrent.Future` or `java.util.concurrent.CompletionStage` will the call the service  be non blocking?

**Comment by mrniko** [comment]
@techthumb 

Hi,

Introducing `RFuture` interface is the only way to provide flexible compatiblity for `java.util.concurrent.Future` and `java.util.concurrent.CompletionStage` interfaces. RRemoteService call through async method is always non-blocking for calling side.

**Comment by techthumb** [comment]
Thanks @mrniko 

We want to use the RemoteService feature.

Our interfaces currently return `CompletableFuture`.

We want usage to be seamless when exposing a service remotely.

Is there a way you suggest we can achieve this without using `@RRemoteAsync`?

**Comment by mrniko** [comment]
@techthumb 

> Is there a way you suggest we can achieve this without using @RRemoteAsync?

I'm afraid no.
