### ISSUE TITLE
Q: To use RedissonRedLock locking mechanism do we need to create multiple locks?

### ISSUE THREAD

**Issue by tankchintan** [mrniko/redisson#588]
My use case is simple (I think). I need to make sure that for a specific keyspace, only one client can create an entry i.e. akey with value for it. If multiple threads/clients etc access the "creation" method at the very same time, then only the first one should get access to create the entry & all others should be rejected.

I was trying to accomplish using the following code snippet.

```
    /*
    * 1. Test if the object with the specified identifiers does not exist already.
    * */
    if (exists(objectIdentifiers)) {
      throw new DuplicateObjectCreationRequestException(message);
    }

    /*
      * 2. Acquire a distributed Redis lock, auto-expire it after reasonable amount of time.
    * */
    RLock redissonRLock = redissonClient.getLock("lock-unique-id");
    RedissonRedLock locker = new RedissonRedLock(redissonRLock);
    locker.lock(5, TimeUnit.SECONDS);

    /*
      * 3. Guard against clients which got access to this block of code, after the first client already created the entry.
    * */
    if (exists(objectIdentifiers)) {
      throw new DuplicateObjectCreationRequestException(message);
    }

    //create entry

    locker.unlock();
  }
```

But this seems to not work at all. I executed this method using executor service, where I ran 2 threads in parallel.

And it seems that one of the threads gets is able create the lock, do the work & unlock it. But the second one is not even able to get the lock & the method never finishes execution.

After I changed the locking mechanism to *Fair Lock* things work as expected.

I am not sure why this is? Is it because of the fact that the RedissonRedLock expects multiple locks? But I dont think I would need that in my case.

FYI here is the snippet of code I use to paralelly start 2 executions.

```
Callable<Entry> callable_1 = new Callable<Entry>() {
      @Override public Entry call() {
        try {
          return datastoreManagementService.createEntry(key1, key2);
        } catch (DuplicateObjectCreationRequestException | InvalidRequestException ex) {
          ex.printStackTrace();
        }

        return null;
      }
    };


    Callable<Entry> callable_2 = new Callable<Entry>() {
      @Override public Entry call() {

        try {
          return datastoreManagementService.createEntry(key1, key2);
        } catch (DuplicateObjectCreationRequestException | InvalidRequestException ex) {
          ex.printStackTrace();
        }
        return null;
      }
    };

    ExecutorService executor = Executors.newCachedThreadPool();
    executor.invokeAll(Arrays.asList(callable_1, callable_2));
```

Am I doing something wrong?

**Comment by mrniko** [comment]
Which Redisson version do you use?

**Comment by jackygurui** [comment]
Why do you have to use lock instead of to just use trySet method in the RBucket?

**Comment by tankchintan** [comment]
@mrniko I am using `2.2.24`.

@jackygurui The requirement is to not allow the second set operation AND also to let the client know about it. This should happen regardless of how many clients are trying to perform the same `set` operation at the very same time. Hence I think `trySet` will not work. Does `trySet` internally have a synchronized block?

**Comment by tankchintan** [comment]
Also wanted to ask, does Redisson itself make a determination on whether a node is a master or slave? Or it uses the first node in the list as master and all others as slave?

**Comment by mrniko** [comment]
@tankchintan 
> Does trySet internally have a synchronized block?

It works atomically in one operation.

> Also wanted to ask, does Redisson itself make a determination on whether a node is a master or slave

Only in redis cluster mode.

**Comment by jackygurui** [comment]
@tankchintan

```java
public boolean trySet(V value);
```
this is perfect for your case, to further extend what @mrniko has described, redis is only a single thread system, that means only one command is executed at any given time, regardless how many it receives at the same time. The trySet method uses `SETNX key value` command under the hood and from the boolean return value, your client will know if it has been accepted or not.

There is no need to create complicated locking or synchronising by yourself.

**Comment by tankchintan** [comment]
@mrniko I think I did not clarify I am using Elasticache mode. Here is my configuration that I explicitly set.
````
  config:
    elasticacheServersConfig:
      nodeAddresses:
        - "//sample.1.cache.amazonaws.com"
        - "//sample.2.cache.amazonaws.com"
````
Having said that will it automatically figure out what is master and what is slave? And if elasticache makes changes on one of those nodes.. form master to slave... for service degradation reasons, will Redisson automagically figure it out & update it's settings?


@jackygurui Thanks for the explanation. It does makes sense to use `trySet` instead. Just one more clarification. You mentioned that redis is single threaded. But what about in cluster mode or the elasticache mode? Because the requests can go to any node, right? Will operations still work as expected?

**Comment by jackygurui** [comment]
@tankchintan
In cluster mode, elasticache mode or master-slave mode, your write operation can only be done on master nodes, i.e. your trySet will be executed on a master. In cluster mode, for any given key, it can only reside on one (hash) slot. So the answer to your questions are: No, the requests wouldn't go to any node, it would only go to the master node which manages the slot contains the key; Yes, the `trySet` operation should still work as expected.

**Comment by tankchintan** [comment]
Thanks for the great explanation @jackygurui. I just now finished writing few test cases to verify this behavior & it works as expected.

**Comment by tankchintan** [comment]
I think I can close this ticket, but the original question still remains a mystery (of if we need multiple distinct RLock objects for a RedissionRedLock object to lock & unlock properly).

**Comment by mrniko** [comment]
> I think I can close this ticket, but the original question still remains a mystery (of if we need multiple distinct RLock objects for a RedissionRedLock object to lock & unlock properly).

I think it's not necessary to use RedLock with single lock, because it's designed for N locks not for one. For single lock use a `RLock` instance.

**Comment by tankchintan** [comment]
@jackygurui @mrniko I wanted to run something by you. As you suggested we have been using the `trySet` method for making sure that only one copy of a specific key is ever created. And that if someone attempts to create another key it will throw exception, even if both creation requests are made at the very same millisecond.

After implementing this system, thus far we have seen very small amount of duplicates getting created. Like 10 in the last couple of months it has been in production. Granted this is a very small number, I wanted to make sure that this is not happening because of `trySet` usage & coulod be because of some other application code we are using. 

I was reading through `SETNX` doc, which I think is being used under the hood for `trySet`. In the `handling deadlocks` section, it mentions that there is a possibility in a race condition that 2 clients can acquire a lock on the same key & that breaks down the protection. Is this applicable to Redisson's usage of `trSet`?

**Comment by mrniko** [comment]
Could you please list all methods of `RLock` you use?

**Comment by tankchintan** [comment]
@mrniko Actually I ended up not using `RLock` at all. Based on @jackygurui suggestion, `trySet` serves my scenario perfectly, hence I ended up using that instead.

```
bucket.trySet(object, ttlInSeconds, TimeUnit.SECONDS)
```

**Comment by mrniko** [comment]
So you use only `RBucket.trySet` method only, right? I'm asking because if you use `RBucket.get` too this maybe the reason of your problem

**Comment by tankchintan** [comment]
Yeah @mrniko we use `trySet` directly.

**Comment by mrniko** [comment]
do you use `null` values as argument for `trySet` method?

**Comment by tankchintan** [comment]
Nope. None of the params can be null vy the time we reach this Redisson call.

FYI what set of alarms for us was the following description in SETNX,
```C1 and C2 read lock.foo to check the timestamp, because they both received 0 after executing SETNX, as the lock is still held by C3 that crashed after holding the lock.
C1 sends DEL lock.foo
C1 sends SETNX lock.foo and it succeeds
C2 sends DEL lock.foo
C2 sends SETNX lock.foo and it succeeds
ERROR: both C1 and C2 acquired the lock because of the race condition.```

We are wondering how come both C1 & C2 can acquire the lock & it succeeds.

**Comment by mrniko** [comment]
Such deadlocks possible if you use `delete` & `trySet` methods. RLock uses lua script to avoid such situation. Are you using `delete` method and then `trySet` like in this scenario?

**Comment by tankchintan** [comment]
Yeah, ok that makes sense. To answer your question, nope we dont `delete` and then do `trySet`.

**Comment by mrniko** [comment]
> Like 10 in the last couple of months it has been in production

Just wondering. Did you encounter Redis fail-over process during this period of time?

**Comment by tankchintan** [comment]
@mrniko Nope. We did not.
