### ISSUE TITLE
Duplicate objects in a set

### ISSUE THREAD

**Issue by nickcodefresh** [mrniko/redisson#589]
Hi,

I seem to be able to create duplicate POJO objects in a Redisson distributed set. The implementation doesn't seem to call equals(), which I find odd. I've tried the sorted set implementation too, which calls compare(), but I can get duplicates there as well. Am I missing some implementation details?

Thnkas

Nick

**Comment by mrniko** [comment]
Hi,

Redisson Set compares objects by their serialized state not by `equals` method. As written in [wiki](https://github.com/mrniko/redisson/wiki/7.-distributed-collections#73-set) `Keeps elements uniqueness via element state comparison`

But Redisson Sorted Set uses comparator. Could you provide some test to reproduce it?
