### ISSUE TITLE
possible memory leak due to unlimited io.netty.util.internal.MpscLinkedQueue size

### ISSUE THREAD

**Issue by sunshinechaos** [mrniko/redisson#591]
as the titles tells, when the qps is big enough, say 30000, the MpscLinkedQueue size may run out of control and worse, even full GC can not save any capacity。

and this is code 
`Config config = new Config();
					SingleServerConfig singleSerververConfig = config.useSingleServer();
					singleSerververConfig.setAddress(address);
					singleSerververConfig.setPassword(password);
					singleSerververConfig.setConnectionPoolSize(connectionPoolSize);
					singleSerververConfig.setTimeout(timeout);
					singleSerververConfig.setConnectTimeout(connectTimeout);
					redisson = Redisson.create(config);`

connectionPoolSize is 200, timeout and connectTimeout both set to 1000。

**Comment by mrniko** [comment]
> size may run out of control and worse

How big is queue? This queue is necessary part of framework. It's not possible to handle async commands without it. 
How many Redisson instances do you use?

**Comment by sunshinechaos** [comment]
I used singleton approach to make sure that only one  Redisson instance exists in jvm , and here is the complete code ：
`	public RedissonClient getRedisson() {

		if (redisson == null) {
			synchronized (RedissonManager.class) {
				if (redisson == null) {
					Config config = new Config();
					SingleServerConfig singleSerververConfig = config.useSingleServer();
					singleSerververConfig.setAddress(address);
					singleSerververConfig.setPassword(password);
					singleSerververConfig.setConnectionPoolSize(connectionPoolSize);
					singleSerververConfig.setTimeout(timeout);
					singleSerververConfig.setConnectTimeout(connectTimeout);
					redisson = Redisson.create(config);
				}
			}
		}
		return redisson;

	}`

and  below is the heap dump statistics

class io.netty.util.internal.MpscLinkedQueue @ 0x78b93fac8
24 (shallow size)
2,874,854,400 (retained size)
and that's 81.34% of the total size

**Comment by mrniko** [comment]
This is unusual size. How big is your objects you sending to Redis?

**Comment by sunshinechaos** [comment]
there are two types of object ：
1. "index" which is stored in zset, it only has two properties:
 long timestamp;
 int id; 
2. "Comment" which is a complex object which is normally 0.2k

**Comment by mrniko** [comment]
How many entries does MpscLinkedQueue have?

**Comment by sunshinechaos** [comment]
I was not able to read the entry count , however this may help , there are 28 
io.netty.util.HashedWheelTimer$HashedWheelTimeout object there.

**Comment by mrniko** [comment]
Let's start from this point. HashedWheelTimer created per Redisson instance or RedisClient instance. How many RedisClient instances do you use?

**Comment by sunshinechaos** [comment]
I'm afraid that this may not be the right clue。the heap dump claims that there is only one Redisson object ，and those io.netty.util.HashedWheelTimer$HashedWheelTimeout objects are in the MpscLinkedQueue object。

**Comment by mrniko** [comment]
Current netty version, which Redisson use, doesn't use MpscLinkedQueue. Which netty version do you use?

**Comment by sunshinechaos** [comment]
Redisson version 2.2.24

there are two netty dependency
io.netty:netty:jar:3.6.3.Final:compile
io.netty:netty-all:jar:4.0.20.Final:compile

**Comment by mrniko** [comment]
Only one netty lib should be in dependency. It seems like some other lib adds 3.6.3 version. Please update it to netty-4.0.40

**Comment by sunshinechaos** [comment]
ok , I got to exclude those lower version and give a pressure test to see the result.
and by the way , you mean the netty 3.6.3 version may cause this memory leak?

**Comment by mrniko** [comment]
I think two netty libs of different version could lead to incorrect work of Redisson.
