### ISSUE TITLE
Implement LocalCachedMap

### ISSUE THREAD

**Issue by mrniko** [mrniko/redisson#592]
Supports LRU and LFU eviction policy.
Supports time to live and max idle time support.
Supports size limitation. If cache max size reached then elements evicted according eviction policy and/or object TTL.
If element has been added/removed then invalidation message sent to all LocalCachedMap instances and element evicted in all of them.
Implements only `java.util.Map`

**Comment by doggie1989** [comment]
guava cache!

**Comment by mrniko** [comment]
@doggie1989  I think guava cache is overcomplicated and too heavy as dependency for Redisson

**Comment by doggie1989** [comment]
@mrniko it is simple,we are using guava cache as local cache for redisson.

**Comment by ben-manes** [comment]
> Supports LRU and LFU eviction policy.

You might want to consider [TinyLFU](http://highscalability.com/blog/2016/1/25/design-of-a-modern-cache.html) to capture frequency in a efficient, compact manner. Or you might try Redis' experimental [approach](http://antirez.com/news/109).

If you also want concurrency than [off-the-shelf](https://github.com/ben-manes/caffeine) is probably preferable.

**Comment by mrniko** [comment]
@ben-manes Thanks for advice. I'm really appreciate it!

**Comment by innocentliny** [comment]
Is "LocalCachedMap" the "near cache" that mentioned at ["Moving from Hazelcast to Redis"](https://engineering.datorama.com/moving-from-hazelcast-to-redis-b90a0769d1cb)?

**Comment by jackygurui** [comment]
Yes

**Comment by mrniko** [comment]
@innocentliny there is also LocalCachedMapCache for MapCache object

**Comment by johnou** [comment]
Unfortunately the Redis hash in LocalCachedMapCache is unbounded which depending on usage may not be suitable. We created a simple bounded hash available here https://github.com/redisson/redisson/pull/985
