### ISSUE TITLE
Could not initialize class org.redisson.codec.JsonJacksonCodec 

### ISSUE THREAD

**Issue by Ducker15** [mrniko/redisson#598]
Hello,

I`m having the next issue (trying to use an Elasticache-Server):

StandardWrapperValve[Login]: Servlet.service() for servlet Session threw exception
java.lang.NoClassDefFoundError: Could not initialize class org.redisson.codec.JsonJacksonCodec
	at org.redisson.config.Config.<init>(Config.java:70)
	at org.redisson.Redisson.<init>(Redisson.java:101)
	at org.redisson.Redisson.create(Redisson.java:133)
	at com.mx.oax.xhuncoescolar.Session.doGet(Login.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        ...

My dependencies:

       <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson</artifactId>
            <version>2.3.0</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.8.1</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>2.8.1</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.8.1</version>
        </dependency>

Server conf:
64bit Debian jessie v2.1.6 running GlassFish 4.1 Java 8 (Preconfigured - Docker)

**Comment by mrniko** [comment]
I haven't test it with 2.8.x version of Jackson yet.

**Comment by Ducker15** [comment]
Now works fine! Thanks.
