### ISSUE TITLE
RedissonList

### ISSUE THREAD

**Issue by shmosel** [mrniko/redisson#60]
`RedissonList.subList()` doesn't conform to the specifications of `java.util.List`, which states that `subList()` returns a *view* backed by the current list.

On a related note, it would be nice to also have access to some of the buffered collections in addition to the redisson wrapper collections. If you're expecting to read all or most of a list, it would be wasteful to have to call `RedissonList.get()` for each element, resulting in another redis query each time. (Currently you can get a buffered list by calling `subList()`, but that's a workaround unique to the list collection, and it shouldn't really work that way - as mentioned above.)

**Comment by mrniko** [comment]
Buffered methods will be implemented in https://github.com/mrniko/redisson/issues/374
