### ISSUE TITLE
Need to be able to set expiry on a Live Object

### ISSUE THREAD

**Issue by davidtinker** [mrniko/redisson#607]
I haven't been able to find a way to EXPIRE the key for a live object. I am working around this by extracting the underlying RMap field with reflection and calling expire on that.

    public static RMap extractLiveObjectLiveMap(Object o) throws Exception {
        Field f = o.getClass().getDeclaredField("liveObjectLiveMap");
        f.setAccessible(true);
        return (RMap)f.get(o);
    }

    extractLiveObjectLiveMap(liveObject).expire(24, TimeUnit.HOURS)

Obviously thats not a great solution :)

**Comment by jackygurui** [comment]
A solution is coming shortly.

**Comment by jackygurui** [comment]
This should cover it.

https://github.com/mrniko/redisson/pull/609

**Comment by davidtinker** [comment]
Nice! Thanks a stack!
