### ISSUE TITLE
rlock error report

### ISSUE THREAD

**Issue by BreathOfRain** [mrniko/redisson#612]
`org.redisson.client.RedisException:TRYAGAIN Multiple keys request during rehashing of slot. channel: [id: 0x1a63eaee, L:/xxx.xx.xx.xx:25185 - R:/xxx.xx.xx.xx:6384] command: CommandData [promise=ImmediateEventExecutor$ImmediatePromise@1f512134(incomplete), command=(EVAL), params=[if (redis.call('exists', KEYS[1]) == 0) then redis.call('publish', KEYS[2], ARGV[1]); return 1; end;if (redis.call('hexists', KEYS[1], ARGV[3]) == 0) then return nil;end; local counter = redis.call('hincrby', KEYS[1], ARGV[3], -1); if (counter > 0) then redis.call('pexpire', KEYS[1], ARGV[2]); return 0; else redis.call('del', KEYS[1]); redis.call('publish', KEYS[2], ARGV[1]); return 1; end; return nil;, 2, schedule:lock:10:295569, redisson_lock__channel__{schedule:lock:10:295569}, 0, 600000, 6c59087f-9c3a-4d81-be00-3a0b45bdec8a:80886], codec=org.redisson.client.codec.LongCodec@200af465]`

**Comment by mrniko** [comment]
Thanks! I'll add TRYAGAIN error handling

**Comment by mrniko** [comment]
Done

**Comment by BreathOfRain** [comment]
awesome
