### ISSUE TITLE
Lua Script Evaluation Support

### ISSUE THREAD

**Issue by lrezek** [mrniko/redisson#73]
Hey, I was wondering if there is any way to execute a LUA script in redisson. I can do it through the connection manager, using something like this:
```Java
ConnectionManager cm;
	    
try{
    Field field = Redisson.class.getDeclaredField("connectionManager");
    field.setAccessible(true);
    cm = (ConnectionManager) field.get(redisson);
}
catch(Exception e){}

cm.connectionReadOp(0).eval(script, type, keys);
```
But obviously that's not the cleanest solution. Would it be possible to add a public `evalScript()` method, or something of the sort to the `Redisson` class? Thanks!

**Comment by mrniko** [comment]
I'll implement it in next few days

**Comment by mrniko** [comment]
Done
