### ISSUE TITLE
Redisson keys should be objects

### ISSUE THREAD

**Issue by shmosel** [mrniko/redisson#79]
Since `RedissonCodec` supports any type of serialized key, `RedissonObject.name` should be of type `Object` so that we can invoke `Redisson.getList(someSerializableObject)` etc.

**Comment by pdeschen** [comment]
@shmosel I think it wouldn't be inline with the [general](http://redis.io/topics/data-types-intro#redis-keys) [principles](http://stackoverflow.com/a/6971415/475884) and conventions behind keys.
